export const LIVE_PROJECTION_INVALID_SOURCE_ERROR_CODE = "LIVE_PROJECTION_INVALID_SOURCE" as const;
export const LIVE_PROJECTION_DUPLICATE_KEY_ERROR_CODE = "LIVE_PROJECTION_DUPLICATE_KEY" as const;
export const LIVE_PROJECTION_MISSING_IDENTITY_ERROR_CODE = "LIVE_PROJECTION_MISSING_IDENTITY" as const;
export const LIVE_PROJECTION_INVALID_BRANCH_ERROR_CODE = "LIVE_PROJECTION_INVALID_BRANCH" as const;
export const LIVE_PROJECTION_BRANCH_ATTACHED_ERROR_CODE = "LIVE_PROJECTION_BRANCH_ATTACHED" as const;
export const LIVE_PROJECTION_MAPPING_CONFLICT_ERROR_CODE = "LIVE_PROJECTION_MAPPING_CONFLICT" as const;
export const LIVE_PROJECTION_DISPOSED_ERROR_CODE = "LIVE_PROJECTION_DISPOSED" as const;
export const LIVE_PROJECTION_SOURCE_REPLACEMENT_ERROR_CODE = "LIVE_PROJECTION_SOURCE_REPLACEMENT_FAILED" as const;
export const LIVE_PROJECTION_UNSUPPORTED_OPERATION_ERROR_CODE = "LIVE_PROJECTION_UNSUPPORTED_OPERATION" as const;
export const LIVE_PROJECTION_RENDERER_CREATE_ERROR_CODE = "LIVE_PROJECTION_RENDERER_CREATE_FAILED" as const;
export const LIVE_PROJECTION_RENDERER_UPDATE_ERROR_CODE = "LIVE_PROJECTION_RENDERER_UPDATE_FAILED" as const;
export const LIVE_PROJECTION_HOST_NOT_EMPTY_ERROR_CODE = "LIVE_PROJECTION_HOST_NOT_EMPTY" as const;

export type LiveProjectionErrorCode =
  | typeof LIVE_PROJECTION_INVALID_SOURCE_ERROR_CODE
  | typeof LIVE_PROJECTION_DUPLICATE_KEY_ERROR_CODE
  | typeof LIVE_PROJECTION_MISSING_IDENTITY_ERROR_CODE
  | typeof LIVE_PROJECTION_INVALID_BRANCH_ERROR_CODE
  | typeof LIVE_PROJECTION_BRANCH_ATTACHED_ERROR_CODE
  | typeof LIVE_PROJECTION_MAPPING_CONFLICT_ERROR_CODE
  | typeof LIVE_PROJECTION_DISPOSED_ERROR_CODE
  | typeof LIVE_PROJECTION_SOURCE_REPLACEMENT_ERROR_CODE
  | typeof LIVE_PROJECTION_UNSUPPORTED_OPERATION_ERROR_CODE
  | typeof LIVE_PROJECTION_RENDERER_CREATE_ERROR_CODE
  | typeof LIVE_PROJECTION_RENDERER_UPDATE_ERROR_CODE
  | typeof LIVE_PROJECTION_HOST_NOT_EMPTY_ERROR_CODE;

/** Stable classified failure raised by the experimental projection engine. */
export class LiveProjectionError extends Error {
  public readonly code: LiveProjectionErrorCode;
  public readonly cause: unknown;

  public constructor(code: LiveProjectionErrorCode, message: string, cause?: unknown) {
    super(message);
    this.name = "LiveProjectionError";
    this.code = code;
    this.cause = cause;
  }
}
