export const DOCUMENT_BINDING_REVISION_GAP_ERROR_CODE = "DOCUMENT_BINDING_REVISION_GAP" as const;
export const DOCUMENT_BINDING_UNSUPPORTED_OPERATION_ERROR_CODE = "DOCUMENT_BINDING_UNSUPPORTED_OPERATION" as const;
export const DOCUMENT_BINDING_TARGET_MISSING_ERROR_CODE = "DOCUMENT_BINDING_TARGET_MISSING" as const;
export const DOCUMENT_BINDING_QUID_MISMATCH_ERROR_CODE = "DOCUMENT_BINDING_QUID_MISMATCH" as const;
export const DOCUMENT_BINDING_NODE_KIND_MISMATCH_ERROR_CODE = "DOCUMENT_BINDING_NODE_KIND_MISMATCH" as const;
export const DOCUMENT_BINDING_DOM_MAPPING_MISMATCH_ERROR_CODE = "DOCUMENT_BINDING_DOM_MAPPING_MISMATCH" as const;
export const DOCUMENT_BINDING_PROJECTION_FAILED_ERROR_CODE = "DOCUMENT_BINDING_PROJECTION_FAILED" as const;
export const DOCUMENT_BINDING_ALREADY_BOUND_ERROR_CODE = "DOCUMENT_BINDING_ALREADY_BOUND" as const;
export const DOCUMENT_BINDING_DISPOSED_ERROR_CODE = "DOCUMENT_BINDING_DISPOSED" as const;
export const DOCUMENT_BINDING_CONTENT_PATH_INVALID_ERROR_CODE = "DOCUMENT_BINDING_CONTENT_PATH_INVALID" as const;
export const DOCUMENT_BINDING_CONTENT_INDEX_INVALID_ERROR_CODE = "DOCUMENT_BINDING_CONTENT_INDEX_INVALID" as const;
export const DOCUMENT_BINDING_CONTENT_MISMATCH_ERROR_CODE = "DOCUMENT_BINDING_CONTENT_MISMATCH" as const;
export const DOCUMENT_BINDING_QUID_COLLISION_ERROR_CODE = "DOCUMENT_BINDING_QUID_COLLISION" as const;
export const DOCUMENT_BINDING_REUSE_INCOMPATIBLE_ERROR_CODE = "DOCUMENT_BINDING_REUSE_INCOMPATIBLE" as const;
export const DOCUMENT_BINDING_STRUCTURAL_PROJECTION_FAILED_ERROR_CODE = "DOCUMENT_BINDING_STRUCTURAL_PROJECTION_FAILED" as const;
export const DOCUMENT_BINDING_DELEGATION_UNSUPPORTED_ERROR_CODE = "DOCUMENT_BINDING_DELEGATION_UNSUPPORTED" as const;
export const DOCUMENT_BINDING_DELEGATION_TARGET_INVALID_ERROR_CODE = "DOCUMENT_BINDING_DELEGATION_TARGET_INVALID" as const;
export const DOCUMENT_BINDING_DELEGATION_ROOT_FORBIDDEN_ERROR_CODE = "DOCUMENT_BINDING_DELEGATION_ROOT_FORBIDDEN" as const;
export const DOCUMENT_BINDING_ROOT_MATERIAL_MISSING_ERROR_CODE = "DOCUMENT_BINDING_ROOT_MATERIAL_MISSING" as const;
export const DOCUMENT_BINDING_ROOT_KIND_MISMATCH_ERROR_CODE = "DOCUMENT_BINDING_ROOT_KIND_MISMATCH" as const;
export const DOCUMENT_BINDING_ROOT_QUID_CONFLICT_ERROR_CODE = "DOCUMENT_BINDING_ROOT_QUID_CONFLICT" as const;
export const DOCUMENT_BINDING_ROOT_VALIDATION_FAILED_ERROR_CODE = "DOCUMENT_BINDING_ROOT_VALIDATION_FAILED" as const;
export const DOCUMENT_BINDING_ROOT_REPLACEMENT_FAILED_ERROR_CODE = "DOCUMENT_BINDING_ROOT_REPLACEMENT_FAILED" as const;
export const DOCUMENT_BINDING_SNAPSHOT_REVISION_MISMATCH_ERROR_CODE = "DOCUMENT_BINDING_SNAPSHOT_REVISION_MISMATCH" as const;
export const DOCUMENT_BINDING_SNAPSHOT_CAPTURE_FAILED_ERROR_CODE = "DOCUMENT_BINDING_SNAPSHOT_CAPTURE_FAILED" as const;

export type DocumentLiveTreeBindingErrorCode =
  | typeof DOCUMENT_BINDING_REVISION_GAP_ERROR_CODE
  | typeof DOCUMENT_BINDING_UNSUPPORTED_OPERATION_ERROR_CODE
  | typeof DOCUMENT_BINDING_TARGET_MISSING_ERROR_CODE
  | typeof DOCUMENT_BINDING_QUID_MISMATCH_ERROR_CODE
  | typeof DOCUMENT_BINDING_NODE_KIND_MISMATCH_ERROR_CODE
  | typeof DOCUMENT_BINDING_DOM_MAPPING_MISMATCH_ERROR_CODE
  | typeof DOCUMENT_BINDING_PROJECTION_FAILED_ERROR_CODE
  | typeof DOCUMENT_BINDING_ALREADY_BOUND_ERROR_CODE
  | typeof DOCUMENT_BINDING_DISPOSED_ERROR_CODE
  | typeof DOCUMENT_BINDING_CONTENT_PATH_INVALID_ERROR_CODE
  | typeof DOCUMENT_BINDING_CONTENT_INDEX_INVALID_ERROR_CODE
  | typeof DOCUMENT_BINDING_CONTENT_MISMATCH_ERROR_CODE
  | typeof DOCUMENT_BINDING_QUID_COLLISION_ERROR_CODE
  | typeof DOCUMENT_BINDING_REUSE_INCOMPATIBLE_ERROR_CODE
  | typeof DOCUMENT_BINDING_STRUCTURAL_PROJECTION_FAILED_ERROR_CODE
  | typeof DOCUMENT_BINDING_DELEGATION_UNSUPPORTED_ERROR_CODE
  | typeof DOCUMENT_BINDING_DELEGATION_TARGET_INVALID_ERROR_CODE
  | typeof DOCUMENT_BINDING_DELEGATION_ROOT_FORBIDDEN_ERROR_CODE
  | typeof DOCUMENT_BINDING_ROOT_MATERIAL_MISSING_ERROR_CODE
  | typeof DOCUMENT_BINDING_ROOT_KIND_MISMATCH_ERROR_CODE
  | typeof DOCUMENT_BINDING_ROOT_QUID_CONFLICT_ERROR_CODE
  | typeof DOCUMENT_BINDING_ROOT_VALIDATION_FAILED_ERROR_CODE
  | typeof DOCUMENT_BINDING_ROOT_REPLACEMENT_FAILED_ERROR_CODE
  | typeof DOCUMENT_BINDING_SNAPSHOT_REVISION_MISMATCH_ERROR_CODE
  | typeof DOCUMENT_BINDING_SNAPSHOT_CAPTURE_FAILED_ERROR_CODE;

/** Internal classified failure for the experimental document projection proof. */
export class DocumentLiveTreeBindingError extends Error {
  public constructor(
    public readonly code: DocumentLiveTreeBindingErrorCode,
    message: string,
    public override readonly cause?: unknown,
  ) {
    super(message, cause === undefined ? undefined : { cause });
    this.name = "DocumentLiveTreeBindingError";
  }
}
