export const LIVE_INSPECTOR_UNSUPPORTED_SOURCE_ERROR_CODE = "LIVE_INSPECTOR_UNSUPPORTED_SOURCE" as const;
export const LIVE_INSPECTOR_INVALID_ROOT_ERROR_CODE = "LIVE_INSPECTOR_INVALID_ROOT" as const;
export const LIVE_INSPECTOR_SOURCE_REPLACEMENT_ERROR_CODE = "LIVE_INSPECTOR_SOURCE_REPLACEMENT_FAILED" as const;
export const LIVE_INSPECTOR_DISPOSED_ERROR_CODE = "LIVE_INSPECTOR_DISPOSED" as const;
export const LIVE_INSPECTOR_INVALID_PATH_ERROR_CODE = "LIVE_INSPECTOR_INVALID_PATH" as const;
export const LIVE_INSPECTOR_NON_STRUCTURAL_EXPANSION_ERROR_CODE = "LIVE_INSPECTOR_NON_STRUCTURAL_EXPANSION" as const;
export const LIVE_INSPECTOR_MISSING_ARRAY_KEY_ERROR_CODE = "LIVE_INSPECTOR_MISSING_ARRAY_KEY" as const;
export const LIVE_INSPECTOR_DUPLICATE_ARRAY_KEY_ERROR_CODE = "LIVE_INSPECTOR_DUPLICATE_ARRAY_KEY" as const;
export const LIVE_INSPECTOR_UNSUPPORTED_SERIALIZATION_ERROR_CODE = "LIVE_INSPECTOR_UNSUPPORTED_SERIALIZATION" as const;
export const LIVE_INSPECTOR_UNREPRESENTABLE_CONVERSION_ERROR_CODE = "LIVE_INSPECTOR_UNREPRESENTABLE_CONVERSION" as const;
export const LIVE_INSPECTOR_SPECIALIZATION_ERROR_CODE = "LIVE_INSPECTOR_SPECIALIZED_RENDERER_FAILED" as const;
export const LIVE_INSPECTOR_RENDERER_HOOK_ERROR_CODE = "LIVE_INSPECTOR_RENDERER_HOOK_FAILED" as const;
export const LIVE_INSPECTOR_PROJECTION_ERROR_CODE = "LIVE_INSPECTOR_PROJECTION_FAILED" as const;
export const LIVE_INSPECTOR_OBSERVER_ERROR_CODE = "LIVE_INSPECTOR_OBSERVER_FAILED" as const;
export const LIVE_INSPECTOR_EXPAND_LIMIT_ERROR_CODE = "LIVE_INSPECTOR_EXPAND_LIMIT_EXCEEDED" as const;

export type LiveInspectorErrorCode =
  | typeof LIVE_INSPECTOR_UNSUPPORTED_SOURCE_ERROR_CODE
  | typeof LIVE_INSPECTOR_INVALID_ROOT_ERROR_CODE
  | typeof LIVE_INSPECTOR_SOURCE_REPLACEMENT_ERROR_CODE
  | typeof LIVE_INSPECTOR_DISPOSED_ERROR_CODE
  | typeof LIVE_INSPECTOR_INVALID_PATH_ERROR_CODE
  | typeof LIVE_INSPECTOR_NON_STRUCTURAL_EXPANSION_ERROR_CODE
  | typeof LIVE_INSPECTOR_MISSING_ARRAY_KEY_ERROR_CODE
  | typeof LIVE_INSPECTOR_DUPLICATE_ARRAY_KEY_ERROR_CODE
  | typeof LIVE_INSPECTOR_UNSUPPORTED_SERIALIZATION_ERROR_CODE
  | typeof LIVE_INSPECTOR_UNREPRESENTABLE_CONVERSION_ERROR_CODE
  | typeof LIVE_INSPECTOR_SPECIALIZATION_ERROR_CODE
  | typeof LIVE_INSPECTOR_RENDERER_HOOK_ERROR_CODE
  | typeof LIVE_INSPECTOR_PROJECTION_ERROR_CODE
  | typeof LIVE_INSPECTOR_OBSERVER_ERROR_CODE
  | typeof LIVE_INSPECTOR_EXPAND_LIMIT_ERROR_CODE;

export class LiveInspectorError extends Error {
  public readonly code: LiveInspectorErrorCode;
  public readonly cause: unknown;

  public constructor(code: LiveInspectorErrorCode, message: string, cause?: unknown) {
    super(message);
    this.name = "LiveInspectorError";
    this.code = code;
    this.cause = cause;
  }
}
