import assert from "node:assert/strict";
import { Hson } from "../src/hson-authoring.ts";
import { discover_hson_tagged_templates } from "../src/internal/embedded-hson/discover-hson-tagged-templates.ts";
import { interpolation_site, map_interpolation_range } from "../src/internal/trusted-schema-diagnostics/interpolation-source.ts";
import { capture_interpolation, reset_interpolation_captures, read_interpolation_captures } from "../src/internal/trusted-schema-diagnostics/interpolation-capture.ts";
import { emit_hson_live_test_completion } from "./launcher-completion.mjs";
let checks=0;
const check=(name:string,run:()=>void)=>{run();console.log(`ok ${++checks} - ${name}`);};
function evaluate(body:string, values:unknown[] = [37]) {
  reset_interpolation_captures();
  const text='import { Hson } from "hson-live/hson"; const result=Hson`'+body+'`;';
  const source=discover_hson_tagged_templates('/project/test.ts',text).interpolated[0]!;
  const site=interpolation_site(source,'file:///project/test.ts');
  const tag=(strings:TemplateStringsArray,...values:readonly (string|number|boolean|null)[])=>capture_interpolation(site,Hson,strings,values).canonical;
  try { Function('Hson','v', 'return Hson`'+body+'`;')(tag,values); } catch {}
  const capture=read_interpolation_captures()[0]!;
  assert.ok(capture);
  const map=(start:number,end:number,precision:'exact'|'anchor'|'unresolved'='exact')=>map_interpolation_range(site,capture.segments,{start,end,precision});
  return {text,site,capture,map};
}
check('one evaluated primitive completes source',()=>assert.equal(evaluate('<age ${v[0]}>').capture.source,'<age 37>'));
check('literal interval maps to authored characters',()=>{const r=evaluate('<age ${v[0]}>');const o=r.map(1,4);assert.equal(o.kind,'literal-exact');assert.equal(r.text.slice(o.range.start,o.range.end),'age');});
check('substitution token maps to expression body',()=>{const r=evaluate('<age ${v[0]}>');const o=r.map(5,7);assert.equal(o.kind,'substitution-expression');assert.equal(r.text.slice(o.range.start,o.range.end),'v[0]');});
check('substitution subrange remains semantic',()=>assert.equal(evaluate('<age ${v[0]}>').map(5,6).kind,'substitution-expression'));
check('multiple substitutions have independent origins',()=>{const r=evaluate('<a ${v[0]} b ${v[1]}>',[37,true]);assert.deepEqual(r.capture.segments.filter(s=>s.kind==='substitution').map(s=>s.scalarKind),['number','boolean']);});
check('string encoding expansion uses real encoder',()=>assert.equal(evaluate('<age ${v[0]}>',['Ada "Danger"']).capture.source,'<age "Ada \\"Danger\\"">'));
check('string expansion maps whole expression',()=>{const r=evaluate('<age ${v[0]}>',['Ada "Danger"']);assert.equal(r.map(7,12).kind,'substitution-expression');});
check('finite number encoding',()=>assert.equal(evaluate('${v[0]}',[1.25]).capture.source,'1.25'));
check('negative zero preserved',()=>assert.equal(evaluate('${v[0]}',[-0]).capture.source,'-0'));
check('boolean encoding',()=>assert.equal(evaluate('${v[0]}',[false]).capture.source,'false'));
check('null encoding',()=>assert.equal(evaluate('${v[0]}',[null]).capture.source,'null'));
check('raw backslashes remain raw',()=>assert.ok(evaluate('<a "\\n" b ${v[0]}>').capture.source.includes('\\n')));
check('physical CRLF normalizes with host boundaries',()=>{const r=evaluate('<a\r\n${v[0]}>');const o=r.map(2,3);assert.equal(r.text.slice(o.range.start,o.range.end),'\r\n');});
check('physical lone CR normalizes',()=>assert.equal(evaluate('<a\r${v[0]}>').capture.source,'<a\n37>'));
check('escaped backticks retain backslash spelling',()=>assert.ok(evaluate('<a "\\`" b ${v[0]}>').capture.source.includes('\\`')));
check('escaped interpolation opener is literal',()=>{const r=evaluate('<a "\\${literal}" b ${v[0]}>');assert.equal(r.site.expressions.length,1);assert.ok(r.capture.source.includes('\\${literal}'));});
check('astral offsets use UTF16',()=>{const r=evaluate('<a "😀" b ${v[0]}>');const o=r.map(4,6);assert.equal(r.text.slice(o.range.start,o.range.end),'😀');});
check('cross-origin interval is composite',()=>assert.equal(evaluate('<age ${v[0]}>').map(1,7).kind,'composite'));
check('EOF maps before closing host backtick',()=>{const r=evaluate('<age ${v[0]}>');const o=r.map(r.capture.source.length,r.capture.source.length);assert.deepEqual(o.range,{start:r.site.templateRange.end-1,end:r.site.templateRange.end-1});});
check('empty trailing literal maps EOF',()=>{const r=evaluate('${v[0]}');assert.equal(r.map(2,2).range.start,r.site.templateRange.end-1);});
check('anchor in literal retains anchor status',()=>assert.equal(evaluate('<age ${v[0]}>').map(7,8,'anchor').kind,'anchor'));
check('unresolved remains template-level',()=>assert.equal(evaluate('<age ${v[0]}>').map(0,0,'unresolved').kind,'unresolved'));
check('invalid interval fails closed',()=>assert.equal(evaluate('<age ${v[0]}>').map(-1,99).kind,'unresolved'));
check('source revision changes on expression edit',()=>assert.notEqual(evaluate('<age ${v[0]}>').site.sourceRevision,evaluate('<age ${(v[0])}>').site.sourceRevision));
check('source revision changes on literal edit',()=>assert.notEqual(evaluate('<age ${v[0]}>').site.sourceRevision,evaluate('<age  ${v[0]}>').site.sourceRevision));
emit_hson_live_test_completion('hson-d5-mapping',checks,checks,0);
