// @hson-live-external-test
import assert from "node:assert/strict";
import { emit_hson_live_test_completion } from "./launcher-completion.mjs";
import { hson } from "../src/index.ts";
import { canonical_hson_graph_equal } from "../src/core/canonical-hson-equal.ts";
import { set_livemap_projected_quid_candidate_source_for_tests } from "../src/api/livemap/livemap.projected.identity-handle.ts";
import { set_livemap_document_quid_candidate_source_for_tests } from "../src/api/livemap/livemap.document.registration.ts";
import { livemap_identity_epoch_accounting } from "../src/api/livemap/livemap.identity-epoch.ts";
import { element } from "./helpers/reflect-unit6.mts";
import { acquire_document_identity, acquire_projected_identity } from "./helpers/livemap-identity-internal.mts";

const Q1 = "0000000000004b01";
const Q2 = "0000000000004b02";
let checks = 0;
const check = (name: string, run: () => void) => { run(); checks += 1; process.stdout.write(`ok ${checks} - ${name}\n`); };
const map = (value: unknown) => hson.liveMap.fromJson(value as never);
const target = (...path: number[]) => Object.freeze({ kind: "path" as const, path: Object.freeze(path) });
const errorCode = (code: string) => (error: unknown) => typeof error === "object" && error !== null && "code" in error && error.code === code;

check("a retired projected handle never reactivates for an unrelated node", () => { const m = map({ a: { old: true }, b: { fresh: true } }); set_livemap_projected_quid_candidate_source_for_tests(m, () => Q1); const stale = acquire_projected_identity(m, ["a"]); m.delete(["a"]); let calls = 0; set_livemap_projected_quid_candidate_source_for_tests(m, () => ++calls === 1 ? Q1 : Q2); const fresh = acquire_projected_identity(m, ["b"]); assert.equal(stale.active, false); assert.equal(stale.snap(), undefined); assert.deepEqual(fresh.snap(), { fresh: true }); });
check("a retired document handle never reactivates for an unrelated element", () => { const m = element(`<main <a/> <b/>/>`); set_livemap_document_quid_candidate_source_for_tests(m.document, () => Q1); const stale = acquire_document_identity(m.document, target(0, 0)); m.document.content.remove(target(0), 0); let calls = 0; set_livemap_document_quid_candidate_source_for_tests(m.document, () => ++calls === 1 ? Q1 : Q2); const fresh = acquire_document_identity(m.document, target(0, 0)); assert.equal(stale.active, false); assert.equal(stale.snap(), undefined); assert.equal(fresh.snap()?.$_tag, "b"); });
check("document.byQuid is absent after retirement", () => { const m = element(`<main <a/> <b/>/>`); set_livemap_document_quid_candidate_source_for_tests(m.document, () => Q1); acquire_document_identity(m.document, target(0, 0)); m.document.content.remove(target(0), 0); assert.equal(m.document.byQuid(Q1), undefined); });
check("a stale raw-QUID mutation target cannot retarget", () => { const m = element(`<main <a/> <b/>/>`); set_livemap_document_quid_candidate_source_for_tests(m.document, () => Q1); acquire_document_identity(m.document, target(0, 0)); m.document.content.remove(target(0), 0); assert.throws(() => m.document.attrs.set({ kind: "quid", quid: Q1 }, "x", true), errorCode("DOCUMENT_TARGET_NOT_FOUND")); });
check("projected candidate reuse retries before claiming an unrelated node", () => { const m = map({ a: {}, b: {} }); set_livemap_projected_quid_candidate_source_for_tests(m, () => Q1); acquire_projected_identity(m, ["a"]); m.delete(["a"]); let calls = 0; set_livemap_projected_quid_candidate_source_for_tests(m, () => ++calls === 1 ? Q1 : Q2); acquire_projected_identity(m, ["b"]); assert.equal(calls, 2); });
check("document candidate reuse retries before claiming unrelated content", () => { const m = element(`<main <a/> <b/>/>`); set_livemap_document_quid_candidate_source_for_tests(m.document, () => Q1); acquire_document_identity(m.document, target(0, 0)); m.document.content.remove(target(0), 0); let calls = 0; set_livemap_document_quid_candidate_source_for_tests(m.document, () => ++calls === 1 ? Q1 : Q2); acquire_document_identity(m.document, target(0, 0)); assert.equal(calls, 2); });
check("repeated projected retired candidates exhaust atomically", () => { const m = map({ a: {}, b: {} }); set_livemap_projected_quid_candidate_source_for_tests(m, () => Q1); const stale = acquire_projected_identity(m, ["a"]); m.delete(["a"]); const before = m.root(); set_livemap_projected_quid_candidate_source_for_tests(m, () => Q1); assert.throws(() => acquire_projected_identity(m, ["b"]), errorCode("PROJECTED_IDENTITY_ALLOCATOR_EXHAUSTED")); assert.equal(stale.active, false); assert.equal(canonical_hson_graph_equal(before, m.root()), true); });
check("repeated document retired candidates exhaust atomically", () => { const m = element(`<main <a/> <b/>/>`); set_livemap_document_quid_candidate_source_for_tests(m.document, () => Q1); const stale = acquire_document_identity(m.document, target(0, 0)); m.document.content.remove(target(0), 0); const rev = m.rev; set_livemap_document_quid_candidate_source_for_tests(m.document, () => Q1); assert.throws(() => acquire_document_identity(m.document, target(0, 0)), errorCode("LIVEMAP_IDENTITY_ALLOCATOR_EXHAUSTED")); assert.equal(stale.active, false); assert.equal(m.rev, rev); });
check("structurally equal projected replacement permanently retires the old handle", () => { const m = map({ a: { x: 1 }, b: {} }); set_livemap_projected_quid_candidate_source_for_tests(m, () => Q1); const stale = acquire_projected_identity(m, ["a"]); m.replace(["a"], { x: 1 }); set_livemap_projected_quid_candidate_source_for_tests(m, () => Q2); acquire_projected_identity(m, ["b"]); assert.equal(stale.active, false); });
check("structurally equal document replacement permanently retires the old handle", () => { const m = element(`<main <a/> <b/>/>`); set_livemap_document_quid_candidate_source_for_tests(m.document, () => Q1); const stale = acquire_document_identity(m.document, target(0, 0)); m.document.content.replace(target(0), 0, { $_tag: "a", $_content: [] }); set_livemap_document_quid_candidate_source_for_tests(m.document, () => Q2); acquire_document_identity(m.document, target(0, 1)); assert.equal(stale.active, false); });
check("projected ancestor replacement retires descendant identity permanently", () => { const m = map({ a: { child: {} }, b: {} }); set_livemap_projected_quid_candidate_source_for_tests(m, () => Q1); const stale = acquire_projected_identity(m, ["a", "child"]); m.replace(["a"], { child: {} }); set_livemap_projected_quid_candidate_source_for_tests(m, () => Q2); acquire_projected_identity(m, ["b"]); assert.equal(stale.active, false); });
check("document ancestor removal retires descendant identity permanently", () => { const m = element(`<main <section <a/>/> <b/>/>`); set_livemap_document_quid_candidate_source_for_tests(m.document, () => Q1); const stale = acquire_document_identity(m.document, target(0, 0, 0, 0)); m.document.content.remove(target(0), 0); set_livemap_document_quid_candidate_source_for_tests(m.document, () => Q2); acquire_document_identity(m.document, target(0, 0)); assert.equal(stale.active, false); });
check("multiple handles for one retired projected identity all remain inactive", () => { const m = map({ a: {} }); const one = acquire_projected_identity(m, ["a"]); const two = acquire_projected_identity(m, ["a"]); m.delete(["a"]); assert.equal(one.active, false); assert.equal(two.active, false); });
check("multiple handles for one retired document identity all remain inactive", () => { const m = element(`<main <a/> <b/>/>`); const one = acquire_document_identity(m.document, target(0, 0)); const two = acquire_document_identity(m.document, target(0, 0)); m.document.content.remove(target(0), 0); assert.equal(one.active, false); assert.equal(two.active, false); });
check("disposing one projected handle does not alter another or the ledger", () => { const m = map({ a: {} }); const one = acquire_projected_identity(m, ["a"]); const two = acquire_projected_identity(m, ["a"]); one.dispose(); assert.equal(one.active, false); assert.equal(two.active, true); assert.equal(livemap_identity_epoch_accounting(m).issued, 1); });
check("a projected move preserves one active identity lifetime", () => { const m = map([{ a: 1 }, {}]); const h = acquire_projected_identity(m, [0]); m.at([]).array.move(0, 1); assert.deepEqual(h.path(), [1]); assert.equal(livemap_identity_epoch_accounting(m).issued, 1); });
check("a projected rename preserves one active identity lifetime", () => { const m = map({ a: {}, b: 1 }); const h = acquire_projected_identity(m, ["a"]); m.at([]).object.renameKey("a", "z"); assert.deepEqual(h.path(), ["z"]); assert.equal(livemap_identity_epoch_accounting(m).issued, 1); });
check("document insertion shifts a handle without issuing again", () => { const m = element(`<main <a/> <b/>/>`); const h = acquire_document_identity(m.document, target(0, 1)); m.document.content.insert(target(0), 0, { $_tag: "i", $_content: [] }); assert.deepEqual(h.path(), [0, 2]); assert.equal(livemap_identity_epoch_accounting(m).issued, 1); });
check("document movement preserves raw and opaque lookup continuity", () => { const m = element(`<main <a/> <b/>/>`); set_livemap_document_quid_candidate_source_for_tests(m.document, () => Q1); const h = acquire_document_identity(m.document, target(0, 0)); m.document.content.move(target(0), 0, 1); assert.deepEqual(h.path(), [0, 1]); assert.equal(m.document.byQuid(Q1)?.$_tag, "a"); });
check("a new projected epoch may reuse bytes without reactivating an old handle", () => { const m = map({ a: {} }); set_livemap_projected_quid_candidate_source_for_tests(m, () => Q1); const old = acquire_projected_identity(m, ["a"]); m.replace({ b: {} }); set_livemap_projected_quid_candidate_source_for_tests(m, () => Q1); const fresh = acquire_projected_identity(m, ["b"]); assert.equal(fresh.active, true); assert.equal(old.active, false); });
check("a durable document epoch may admit equal bytes without reviving an old handle", () => { const m = element(`<main/>`); set_livemap_document_quid_candidate_source_for_tests(m.document, () => Q1); const old = acquire_document_identity(m.document, target()); m.restore(m.capture()); assert.equal(m.document.byQuid(Q1)?.$_tag, "main"); assert.equal(old.active, false); });
check("fresh owner epochs remain independent even when QUID bytes are equal", () => { const a = map({ x: {} }); const b = map({ x: {} }); set_livemap_projected_quid_candidate_source_for_tests(a, () => Q1); set_livemap_projected_quid_candidate_source_for_tests(b, () => Q1); const ha = acquire_projected_identity(a, ["x"]); const hb = acquire_projected_identity(b, ["x"]); a.delete(["x"]); assert.equal(ha.active, false); assert.equal(hb.active, true); });

process.stdout.write(`1..${checks}\n`);
emit_hson_live_test_completion("livemap.identity-aba-prevention", checks, checks, 0);
