import assert from "node:assert/strict";
import { discover_schema_validation_sources as discover } from "../src/internal/trusted-schema-diagnostics/discover-validation-sources.ts";
import { emit_hson_live_test_completion } from "./launcher-completion.mjs";
let checks = 0;
const prelude = 'import { Hson } from "hson-live"; import { UserSchema } from "./schema.js";\n';
const template = 'const user = Hson`<age "37">`;\n';
const call = 'Hson.certify(UserSchema, user);';
const run = (source: string) => discover("/project/user.ts", source);
function check(name: string, source: string, count: number): void { assert.equal(run(source).length, count, name); console.log(`ok ${++checks} - ${name}`); }
check("direct later validation", prelude + template + call, 1);
check("renamed official root import", (prelude + template + call).replace('import { Hson }', 'import { Hson as authored }').replaceAll('Hson`', 'authored`').replace('Hson.certify', 'authored.certify'), 1);
check("retired Hson validate is not discovered", prelude + template + 'Hson.validate(UserSchema, user);', 0);
check("official hson subpath", (prelude + template + call).replace('"hson-live"', '"hson-live/hson"'), 1);
check("harmless parentheses", prelude + 'const user = (Hson`<age "37">`); Hson.certify((UserSchema), (user));', 1);
check("finite const canonical chain", prelude + template + 'const a = (user); const b = a; Hson.certify(UserSchema, b);', 1);
check("immutable Schema alias chain", prelude + template + 'const a = UserSchema; const b = (a); Hson.certify(b, user);', 1);
check("local Schema registration binding", 'import { Hson, hson } from "hson-live"; const UserSchema = hson.liveMap.schema.define(s => s.number);' + template + call, 1);
check("two validation statements remain independent", prelude + template + call + call, 2);
check("mutable canonical declaration rejected", prelude + template.replace('const', 'let') + call, 0);
check("var declaration rejected", prelude + template.replace('const', 'var') + call, 0);
check("mutable alias rejected", prelude + template + 'let alias = user; Hson.certify(UserSchema, alias);', 0);
check("forward declaration rejected", prelude + call + template, 0);
check("cyclic aliases rejected", prelude + 'const user = a; const a = user;' + call, 0);
check("function return flow rejected", prelude + 'const user = getUser();' + call, 0);
check("transformation breaks correspondence", prelude + template + 'const changed = transform(user); Hson.certify(UserSchema, changed);', 0);
check("property lookup rejected", prelude + template + 'Hson.certify(UserSchema, box.user);', 0);
check("interpolation relationship discovered for trusted D5 capture", prelude + 'const user = Hson`<age ${age}>`;' + call, 1);
check("wrong package rejected", (prelude + template + call).replace('"hson-live"', '"lookalike"'), 0);
check("namespace lookalike rejected", 'import * as Hson from "hson-live";' + template + 'const UserSchema = {};'+call, 0);
check("shadowed facade rejected", prelude + template + 'function f(Hson: any) {' + call + '}', 0);
check("extracted validator rejected", prelude + template + 'const validate = Hson.certify; validate(UserSchema, user);', 0);
check("same function-body domain supported", prelude + 'function f() {' + template + call + '}', 1);
check("cross-function canonical tracing rejected", prelude + template + 'function f() {' + call + '}', 0);
check("bounded chain rejected after 32 aliases", prelude + template + Array.from({ length: 34 }, (_, i) => `const a${i} = ${i === 0 ? 'user' : `a${i-1}`};`).join('') + 'Hson.certify(UserSchema, a33);', 0);
check("renamed imported Schema retains export identity", prelude.replace('{ UserSchema }', '{ ActualSchema as UserSchema }') + template + call, 1);
const aliases = run(prelude.replace('{ UserSchema }', '{ ActualSchema as UserSchema }') + template + call);
assert.deepEqual(aliases[0]?.binding, { moduleUrl: "file:///project/schema.js", exportName: "ActualSchema" });
const local = run('import { Hson } from "hson-live"; const UserSchema = makeSchema();' + template + call)[0];
assert.equal(local?.binding.localName, "UserSchema");
assert.equal(local?.binding.declarationStart, 40);
assert.equal(run(prelude + template + call + call)[0]?.templateId, run(prelude + template + call + call)[1]?.templateId);
assert.notEqual(run(prelude + template + call + call)[0]?.callId, run(prelude + template + call + call)[1]?.callId);
emit_hson_live_test_completion("schema-d2-discovery", checks, checks, 0);
