import assert from "node:assert/strict";
import { fileURLToPath, pathToFileURL } from "node:url";
import { TrustedSchemaClient, type D2Measurement } from "../editors/vscode-hson/src/trusted-schema-client.ts";
import { present_schema_diagnostic } from "../editors/vscode-hson/src/schema-presentation.ts";
import { discover_schema_validation_sources } from "../src/internal/trusted-schema-diagnostics/discover-validation-sources.ts";
import { cases, caseFile } from "./fixtures/schema-d3-cases.mts";
import { emit_hson_live_test_completion } from "./launcher-completion.mjs";
let checks = 0;
const check = async (name: string, f: () => unknown) => { await f(); console.log(`ok ${++checks} - ${name}`); };
const moduleUrl = new URL('./fixtures/schema-d3-runtime.fixture.mts', import.meta.url).href;
const hsonModuleUrl = new URL('../src/hson.ts', import.meta.url).href;
const runtimeEntry = fileURLToPath(new URL('../src/internal/trusted-schema-diagnostics/node-runtime-entry.ts', import.meta.url));
const makeClient = (workspaceTrusted = true, enabled = true) => new TrustedSchemaClient({ trust:{ workspaceTrusted,enabled },moduleUrl,hsonModuleUrl,runtimeEntry,execArgv:['--loader','ts-node/esm'],startupDeadlineMs:5_000 });
const document = (name: string, text = cases[name]!, version = 1) => ({ fileName:caseFile(name), uri:pathToFileURL(caseFile(name)).href,languageId:'typescript',version,text });
const client = makeClient();
try {
  await check('closed trust gates never start or import the project', async () => { for (const [trusted,enabled] of [[false,false],[false,true],[true,false]]) { const c=makeClient(trusted,enabled); try { assert.equal((await c.validate(document('direct'),()=>true)).status,'off'); assert.equal(c.supervisor.generation,0); assert.equal(c.supervisor.output.stdout,''); } finally { c.dispose(); } } });
  await check('ordinary map flow needs no standalone validate', async () => { assert.doesNotMatch(cases.direct!,/schema\.validate/); const r=await client.validate(document('direct'),()=>true); assert.equal(r.status,'current-invalid',r.message + client.supervisor.output.stderr); assert.equal(r.diagnostics.length,1); assert.equal(cases.direct!.slice(r.diagnostics[0]!.range.start,r.diagnostics[0]!.range.end),'"37"'); });
  await check('related information points to use not an extra primary squiggle', async () => { const r=await client.validate(document('direct'),()=>true); const d=r.diagnostics[0]!; assert.match(d.message,/Expected `age` to be a number/); assert.match(d.related[0]!.message,/map.schema.use/); assert.equal(cases.direct!.slice(d.related[0]!.range.start,d.related[0]!.range.end),'map.schema.use(UserSchema)'); });
  await check('unsaved correction validates current editor candidate', async () => { const r=await client.validate(document('direct',cases.direct!.replace('"37"','37'),2),()=>true); assert.equal(r.status,'current-valid',r.message); assert.deepEqual(r.diagnostics,[]); });
  await check('longer body keeps relationship but remaps fresh diagnostic span', async () => { const text=cases.direct!.replace('"37"','"longer current value"'); const r=await client.validate(document('direct',text,3),()=>true); const d=r.diagnostics[0]!; assert.equal(text.slice(d.range.start,d.range.end),'"longer current value"'); assert.equal(text.slice(d.related[0]!.range.start,d.related[0]!.range.end),'map.schema.use(UserSchema)'); });
  await check('mutation yields unavailable, never source blame', async () => { assert.equal((await client.validate(document('documentMutated'),()=>true)).status,'unavailable'); const r=await client.validate(document('mutated'),()=>true); assert.equal(r.status,'unavailable'); assert.deepEqual(r.diagnostics,[]); });
  await check('mutate/revert remains unavailable', async () => { assert.equal((await client.validate(document('documentReverted'),()=>true)).status,'unavailable'); const r=await client.validate(document('reverted'),()=>true); assert.equal(r.status,'unavailable'); assert.deepEqual(r.diagnostics,[]); });
  await check('one-template/two-map diagnostics retain independent related sites', async () => { const r=await client.validate(document('two'),()=>true); assert.equal(r.diagnostics.length,2); assert.deepEqual(r.diagnostics[0]!.range,r.diagnostics[1]!.range); assert.notDeepEqual(r.diagnostics[0]!.related,r.diagnostics[1]!.related); });
  await check('independent mutation suppresses only one map', async () => { const r=await client.validate(document('independent'),()=>true); assert.equal(r.status,'current-invalid'); assert.equal(r.diagnostics.length,1); assert.match(r.diagnostics[0]!.message,/OtherSchema/); });
  await check('idempotence and rejected replacement add no contradictory authority', async () => { const r=await client.validate(document('attempts',cases.attempts!.replace('age 37','age "37"'),2),()=>true); assert.equal(r.diagnostics.length,1); assert.match(r.diagnostics[0]!.message,/UserSchema/); });
  await check('two failed validating attempts remain independent', async () => { const r=await client.validate(document('retries'),()=>true); assert.equal(r.diagnostics.length,2); });
  await check('C2 document exact and anchor presentation', async () => { const r=await client.validate(document('document'),()=>true); assert.equal(r.status,'current-invalid'); assert.ok(r.diagnostics.some(d=>d.precision==='exact' && cases.document!.slice(d.range.start,d.range.end)==='"bad"')); assert.ok(r.diagnostics.some(d=>d.precision==='anchor' && /Anchored/.test(d.message))); });
  await check('C1 missing structure uses an anchor', async () => { const r=await client.validate(document('direct',cases.direct!.replace('<age "37">','<>'),2),()=>true); assert.ok(r.diagnostics.some(d=>d.precision==='anchor' && /age/.test(d.message))); });
  await check('unresolved presentation remains explicitly template-level', () => { const site=discover_schema_validation_sources(caseFile('direct'),cases.direct!)[0]!; const d=present_schema_diagnostic({code:'TYPE_MISMATCH',path:[],range:{precision:'unresolved'}},site); assert.equal(d.precision,'unresolved'); assert.deepEqual(d.range,site.source.templateRange); assert.match(d.message,/Template-level/); assert.match(d.related[0]!.message,/map.schema.use/); });
  await check('inline and immutable aliases reach the same real client pipeline', async () => { for(const name of ['inline','aliases']) assert.equal((await client.validate(document(name),()=>true)).status,'current-invalid'); });
  await check('text fragment context differs from standalone canonical context', async () => { const r=await client.validate(document('text'),()=>true); assert.equal(r.status,'current-valid',r.message); assert.equal((await client.validate(document('scalar'),()=>true)).status,'current-invalid'); });
  await check('fragment root diagnostics stay in authored source', async () => { const r=await client.validate(document('fragment'),()=>true); assert.equal(r.status,'current-invalid'); assert.ok(r.diagnostics.every(d=>d.range.start>=cases.fragment!.indexOf('HSON`'))); });
  await check('standalone validate and map.use coexist independently', async () => { const r=await client.validate(document('mixed'),()=>true); assert.equal(r.diagnostics.length,2); assert.ok(r.diagnostics.some(d=>/this validate call/.test(d.related[0]!.message))); assert.ok(r.diagnostics.some(d=>/map.schema.use/.test(d.related[0]!.message))); });
  await check('construction edit invalidates old lifecycle even at similar ranges', async () => { const r=await client.validate(document('direct',cases.direct!.replace('hson.liveMap.fromHson(source)','hsonLiveMap.fromHson(source)'),2),()=>true); assert.equal(r.status,'unavailable'); assert.deepEqual(r.diagnostics,[]); });
  await check('use and Schema binding edits invalidate lifecycle', async () => { for(const text of [cases.direct!.replace('map.schema.use(UserSchema)','map.schema.use(OtherSchema)'),cases.direct!.replace('map.schema.use','(map).schema.use')]) { const r=await client.validate(document('direct',text,2),()=>true); assert.equal(r.status,'unavailable'); assert.deepEqual(r.diagnostics,[]); } });
  await check('missing lifecycle is unavailable and repeated runtime applications are ambiguous', async () => { assert.equal((await client.validate(document('repeated'),()=>true)).status,'ambiguous'); const doc=document('direct'); const r=await client.validate({...doc,fileName:caseFile('unregistered'),uri:pathToFileURL(caseFile('unregistered')).href},()=>true); assert.equal(r.status,'unavailable'); assert.deepEqual(r.diagnostics,[]); });
  await check('superseded async request returns no publishable diagnostics', async () => { let current=true; const pending=client.validate(document('direct'),()=>current); current=false; const r=await pending; assert.equal(r.status,'stale'); assert.deepEqual(r.diagnostics,[]); });
  await check('source lifecycle modules participate in provider invalidation', () => assert.ok(client.schemaModuleUrls.includes(pathToFileURL(caseFile('direct')).href)));
  await check('warm discovery lifecycle projected document and two-map timings', async () => {
    const median=(values:number[])=>[...values].sort((a,b)=>a-b)[Math.floor(values.length/2)]!;
    for(const name of ['direct','document','two']) {
      const samples:D2Measurement[]=[];
      for(let i=0;i<9;i++) { const r=await client.validate(document(name,cases[name],10+i),()=>true); assert.equal(r.status,'current-invalid'); samples.push(r.measurement!); }
      console.log('# D3 p50 milliseconds '+JSON.stringify({name,discovery:median(samples.map(s=>s.discoveryMs)),lifecycle:median(samples.map(s=>s.lifecycleMs!)),roundTrip:median(samples.map(s=>s.roundTripMs)),endToEnd:median(samples.map(s=>s.endToEndMs)),max:Math.max(...samples.map(s=>s.endToEndMs))}));
      assert.ok(samples.every(s=>s.endToEndMs<2_000),'ordinary warmed path must not become multi-second');
    }
  });
  await check('generation retirement clears authority and replacement reconstructs it', async () => { const before=client.supervisor.activeGeneration; client.invalidate(); assert.equal(client.supervisor.activeGeneration,undefined); const r=await client.validate(document('direct'),()=>true); assert.equal(r.status,'current-invalid',r.message); assert.notEqual(r.generation,before); });
} finally { client.dispose(); }
emit_hson_live_test_completion('schema-d3-editor',checks,checks,0);
