import assert from "node:assert/strict";
import { hson } from "../src/hson.ts";
import type { LiveMapProjectedSchema } from "../src/api/livemap/livemap.schema.ts";
import { query_schema_completion } from "../src/internal/schema-completion/query.ts";
import { emit_hson_live_test_completion } from "./launcher-completion.mjs";
let checks = 0;
const check = (name: string, f: () => void) => { f(); console.log(`ok ${++checks} - ${name}`); };
const define = hson.liveMap.schema.define;
const items = (schema: object, marked: string) => query_schema_completion(schema, marked.replace("|", ""), marked.indexOf("|")).items;
const labels = (schema: object, marked: string) => items(schema, marked).map(i => i.label);
const S = define(s => s.object.exact({ optional: s.string.optional, required: s.number, single: s.literal("only"), choices: s.pick("red", "blue") }));
check("required member", () => assert.equal(items(S, '< |>').find(i => i.label === 'required')?.required, true));
check("optional member", () => assert.equal(items(S, '< |>').find(i => i.label === 'optional')?.required, false));
check("required sort before optional", () => { const all = items(S, '< |>'); assert.ok(all.find(i => i.label === 'required')!.sortText < all.find(i => i.label === 'optional')!.sortText); });
check("existing member omitted", () => assert.ok(!labels(S, '<required 3 |>').includes('required')));
check("open object declares known keys", () => { const result = items(define(s => s.object({ key: s.string })), '< |>'); assert.equal(result.length, 1); assert.match(result[0]!.detail, /open object/); });
check("string no default", () => assert.deepEqual(labels(define(s => s.string), '|'), []));
check("number no default", () => assert.deepEqual(labels(define(s => s.number), '|'), []));
check("boolean finite domain", () => assert.deepEqual(labels(define(s => s.boolean), '|'), ['true', 'false']));
check("null finite domain", () => assert.deepEqual(labels(define(s => s.null), '|'), ['null']));
check("finite alternatives preserve Schema order", () => assert.deepEqual(labels(S, '<choices |>'), ['"red"', '"blue"']));
check("negative zero preserved", () => assert.deepEqual(labels(define(s => s.literal(-0)), '|'), ['-0']));
check("escaping uses HSON spelling and cannot create JS interpolation", () => { assert.deepEqual(labels(define(s => s.literal('a"\n\\b')), '|'), ['"a\\"\\n\\\\b"']); assert.deepEqual(labels(define(s => s.literal('`${x}')), '|'), ['"\\u0060\\u0024{x}"']); });
check("structured literal uses canonical serializer", () => assert.deepEqual(labels(define(s => s.literal({ a: [true, -0] })), '|'), ['<a «true,-0»>']));
check("member broad value uses empty placeholder", () => assert.equal(items(S, '< |>').find(i => i.label === 'required')?.insertText, 'required ${1}'));
check("singleton literal inserted directly", () => assert.equal(items(S, '< |>').find(i => i.label === 'single')?.insertText, 'single "only"'));
check("quoted member names use authored serializer", () => assert.equal(items(define(s => s.object({ 'odd key': s.number })), '< |>')[0]?.insertText, "'odd key' ${1}"));
check("array item schema", () => assert.deepEqual(labels(define(s => s.array(s.pick(1, 2))), '[1, |]'), ['1', '2']));
const Tuple = define(s => s.tuple(s.literal('first'), s.boolean.optional));
check("tuple optional suffix position", () => assert.deepEqual(labels(Tuple, '["first", |]'), ['true', 'false']));
check("closed tuple stops", () => assert.deepEqual(labels(Tuple, '["first", true, |]'), []));
const Tagged = define(s => s.tagged('kind', { a: s.object({ alpha: s.string }), b: s.object({ beta: s.number }) }));
check("unresolved tagged only common discriminator", () => assert.deepEqual(labels(Tagged, '< |>'), ['kind']));
check("tagged discriminator finite choices", () => assert.deepEqual(labels(Tagged, '<kind |>'), ['"a"', '"b"']));
check("unambiguous discriminator narrows", () => assert.deepEqual(labels(Tagged, '<kind "b" |>'), ['beta']));
check("ambiguous pick never chooses closest branch", () => assert.deepEqual(labels(define(s => s.pick(s.object({ a: s.string }), s.object({ b: s.string }))), '< |>'), []));
check("constraints never execute", () => { let calls = 0; const schema = define(s => s.object({ x: s.string.constrain(() => { calls++; return false; }) }).constrain(() => { calls++; return false; })); assert.deepEqual(labels(schema, '< |>'), ['x']); assert.deepEqual(labels(schema, '<x |>'), []); assert.equal(calls, 0); });
check("recurse follows cursor path with existing memoization only", () => { let calls = 0; let Tree: LiveMapProjectedSchema; Tree = define(s => s.object({ name: s.string, child: s.recurse(() => { calls++; return Tree; }).optional })); assert.deepEqual(labels(Tree, '< |>'), ['name', 'child']); assert.equal(calls, 0); for (let i=0;i<2;i++) assert.deepEqual(labels(Tree, '<child < |>>'), ['name', 'child']); assert.equal(calls, 1); });
check("recursive cycle fails closed within the traversal bound", () => { let Cycle: LiveMapProjectedSchema; Cycle = define(s => s.recurse(() => Cycle)); assert.deepEqual(labels(Cycle,'|'), []); });
emit_hson_live_test_completion('schema-projected-completion', checks, checks, 0);
