import assert from "node:assert/strict";
import { hson } from "../src/hson.ts";
import { query_schema_completion } from "../src/internal/schema-completion/query.ts";
import { emit_hson_live_test_completion } from "./launcher-completion.mjs";
let checks = 0;
const check = (name: string, f: () => void) => { f(); console.log(`ok ${++checks} - ${name}`); };
const define = hson.liveMap.schema.define;
const items = (schema: object, marked: string) => query_schema_completion(schema, marked.replace("|", ""), marked.indexOf("|")).items;
const labels = (schema: object, marked: string) => items(schema, marked).map(i => i.label);
const Button = define(s => s.button(s.attrs.exact({ disabled: s.flag, selected: s.flag.optional, id: s.string, role: s.literal('button', 'switch').optional }), s.empty));
check("fixed root tag", () => assert.deepEqual(labels(Button, '< |/>'), ['button']));
check("runtime custom tag evidence", () => { const tag: string = 'my-widget'; assert.deepEqual(labels(define(s => s.tag[tag]()), '< |/>'), [tag]); });
check("broad tag does not enumerate HTML", () => assert.deepEqual(labels(define(s => s.tag()), '< |/>'), []));
check("required attr declaration", () => assert.equal(items(Button, '<button |/>').find(i => i.label === 'id')?.required, true));
check("optional attr declaration", () => assert.equal(items(Button, '<button |/>').find(i => i.label === 'role')?.required, false));
check("required flag evidence", () => { const flag = items(Button, '<button |/>').find(i => i.label === 'disabled'); assert.equal(flag?.kind, 'flag'); assert.equal(flag?.insertText, 'disabled'); assert.equal(flag?.snippet, false); });
check("optional flag evidence", () => assert.equal(items(Button, '<button |/>').find(i => i.label === 'selected')?.required, false));
check("flag presence filters duplicates", () => assert.ok(!labels(Button, '<button disabled |/>').includes('disabled')));
check("valued attr presence filters duplicates", () => assert.ok(!labels(Button, '<button id="x" |/>').includes('id')));
check("attrs exact declared set", () => assert.deepEqual(labels(Button, '<button |/>'), ['disabled', 'id', 'role', 'selected']));
check("open attrs known set not exhaustive", () => assert.match(items(define(s => s.div(s.attrs({ id: s.string }))), '<div |/>')[0]!.detail, /open attrs/));
check("attribute finite literals", () => assert.deepEqual(labels(Button, '<button role=|/>'), ['"button"', '"switch"']));
check("attribute string/constraint no fabricated value or predicate execution", () => { assert.deepEqual(labels(Button, '<button id=|/>'), []); let calls=0; const schema=define(s=>s.div(s.attrs({ code:s.string.constrain(()=>{calls++;return false;}) }))); assert.deepEqual(labels(schema,'<div code=|/>'),[]); assert.deepEqual(labels(schema,'<div |/>'),['code']); assert.equal(calls,0); });
check("boolean attr is not a flag and lacks typed authored spelling", () => { const schema = define(s => s.div(s.attrs({ bool: s.boolean }))); assert.equal(items(schema, '<div |/>')[0]?.kind, 'attribute'); assert.deepEqual(labels(schema, '<div bool=|/>'), []); });
check("attr insertion leaves value blank", () => assert.equal(items(Button, '<button |/>').find(i => i.label === 'id')?.insertText, 'id=${1}'));
check("attr singleton insertion", () => assert.equal(items(define(s => s.div(s.attrs({ role: s.literal('button') }))), '<div |/>')[0]?.insertText, 'role="button"'));
const Sequence = define(s => s.div(s.span(s.empty), s.button(s.empty)));
check("child tuple initial position", () => assert.deepEqual(labels(Sequence, '<div |/>'), ['span']));
check("child tuple second position after element or text", () => { assert.deepEqual(labels(Sequence, '<div <span/> |/>'), ['button']); assert.deepEqual(labels(define(s => s.div(s.string, s.button())), '<div "text" |/>'), ['button']); });
check("closed sequence stops", () => assert.deepEqual(labels(Sequence, '<div <span/> <button/> |/>'), []));
check("repeat can append", () => assert.deepEqual(labels(define(s => s.div(s.repeat(s.button()))), '<div <button/> |/>'), ['button']));
check("counted repeat stops at count", () => assert.deepEqual(labels(define(s => s.div(s.repeat(1, s.button()))), '<div <button/> |/>'), []));
check("empty and broad content produce no invented children", () => { for (const schema of [define(s => s.div(s.empty)), define(s => s.div())]) assert.deepEqual(labels(schema, '<div |/>'), []); });
check("document item pick offers tags without guessing same-tag contracts", () => { assert.deepEqual(labels(define(s => s.div(s.pick(s.span(), s.button()))), '<div < |/>/>'), ['span', 'button']); const same=define(s=>s.div(s.pick(s.button(s.attrs({a:s.flag})),s.button(s.attrs({b:s.flag}))))); assert.equal(items(same,'<div |/>')[0]?.insertText,'<button ${1}/>'); assert.deepEqual(labels(same,'<div <button |/>/>'),[]); });
check("nested document attributes", () => assert.deepEqual(labels(define(s => s.div(s.button(s.attrs({ disabled: s.flag })))), '<div <button |/>/>'), ['disabled']));
check("skeleton stays shallow, preserves required attrs/flags, and invents no prose", () => { assert.equal(items(Sequence, '<div |/>')[0]?.insertText, '<span/>'); assert.equal(items(define(s => s.div(s.button(s.attrs({ disabled:s.flag, id:s.string }),s.empty))), '<div |/>')[0]?.insertText, '<button disabled id=${1}/>'); assert.deepEqual(labels(define(s => s.div(s.string)), '<div |/>'), []); });
check("fragment tuple logical position", () => assert.deepEqual(labels(define(s => s.tuple(s.div(),s.button())), '<div/> < |/>'), ['button']));
emit_hson_live_test_completion('schema-document-completion', checks, checks, 0);
