import assert from "node:assert/strict";
import { HSON } from "../src/hson-authoring.ts";
import { discover_hson_tagged_templates } from "../src/internal/embedded-hson/discover-hson-tagged-templates.ts";
import { interpolation_site } from "../src/internal/trusted-schema-diagnostics/interpolation-source.ts";
import { capture_interpolation, reset_interpolation_captures, read_interpolation_captures } from "../src/internal/trusted-schema-diagnostics/interpolation-capture.ts";
import { instrument_trusted_schema_map_sources } from "../src/internal/trusted-schema-diagnostics/instrument-map-sources.ts";
import { TrustedSchemaDiagnosticRuntime } from "../src/internal/trusted-schema-diagnostics/runtime.ts";
import { discover_schema_validation_sources } from "../src/internal/trusted-schema-diagnostics/discover-validation-sources.ts";
import { cases,caseFile } from "./fixtures/schema-d5-cases.mts";
import { emit_hson_live_test_completion } from "./launcher-completion.mjs";
let checks=0;
const check=async(name:string,run:()=>unknown)=>{await run();console.log(`ok ${++checks} - ${name}`);};
function execute(body:string,values:unknown[],repeat=1) {
  reset_interpolation_captures();
  const text='import { HSON } from "hson-live/hson"; HSON`'+body+'`;';
  const site=interpolation_site(discover_hson_tagged_templates('/project/test.ts',text).interpolated[0]!,'file:///project/test.ts');
  const tag=(strings:TemplateStringsArray,...values:readonly (string|number|boolean|null)[])=>capture_interpolation(site,HSON,strings,values).canonical;
  const run=Function('HSON','v','return HSON`'+body+'`;');
  const results:unknown[]=[];
  for(let i=0;i<repeat;i++) results.push(run(tag,values));
  return results;
}
await check('runtime string admitted as string',()=>{execute('${v[0]}',['37']);assert.equal(read_interpolation_captures()[0]!.source,'"37"');});
await check('runtime number admitted as number',()=>{execute('${v[0]}',[37]);assert.equal(read_interpolation_captures()[0]!.source,'37');});
await check('once-only expression evaluation',()=>{let calls=0;execute('${v[0]()}',[()=>++calls]);assert.equal(calls,1);});
await check('ordinary left-to-right order',()=>{const order:number[]=[];execute('<a ${v[0]()} b ${v[1]()}>',[()=>{order.push(1);return 1;},()=>{order.push(2);return 2;}]);assert.deepEqual(order,[1,2]);});
await check('thrown expression preserves identity',()=>{const sentinel={};assert.throws(()=>execute('${v[0]()}',[()=>{throw sentinel;}]),e=>e===sentinel);});
await check('thrown expression does not call tag or create a capture',()=>{try{execute('${v[0]()}',[()=>{throw 1;}]);}catch{}assert.equal(read_interpolation_captures().length,0);});
await check('throw prevents subsequent substitution evaluation',()=>{let calls=0;try{execute('<a ${v[0]()} b ${v[1]()}>',[()=>{throw 1;},()=>++calls]);}catch{}assert.equal(calls,0);});
await check('unsupported object does not coerce or inspect getters',()=>{let calls=0;const value={toString(){calls++;throw 1;}};assert.throws(()=>execute('${v[0]}',[value]));assert.equal(calls,0);assert.equal(read_interpolation_captures()[0]!.failure?.substitution,0);});
await check('nonfinite error preserves shared admission code',()=>{assert.throws(()=>execute('${v[0]}',[Infinity]));assert.ok(read_interpolation_captures()[0]!.failure?.details?.code);});
await check('admission errors still throw after evidence capture',()=>{assert.throws(()=>execute('${v[0]}',[Symbol('x')]));assert.equal(read_interpolation_captures()[0]!.canonical,undefined);});
await check('second offending substitution identified',()=>{assert.throws(()=>execute('<a ${v[0]} b ${v[1]}>',[1,{}]));assert.equal(read_interpolation_captures()[0]!.failure?.substitution,1);});
await check('grammar failure retains completed source',()=>{assert.throws(()=>execute('<${v[0]}/>',[37]));assert.equal(read_interpolation_captures()[0]!.source,'<37/>');});
await check('public result remains primitive canonical string',()=>{assert.equal(typeof execute('${v[0]}',[37])[0],'string');});
await check('successful canonical is actual tag result',()=>{const r=execute('<a ${v[0]}>',[37])[0];assert.equal(r,read_interpolation_captures()[0]!.canonical);});
await check('repeated execution creates distinct evaluation IDs',()=>{execute('${v[0]}',[37],2);assert.notEqual(read_interpolation_captures()[0]!.evaluationId,read_interpolation_captures()[1]!.evaluationId);});
await check('bounded overflow fails closed rather than selecting last',()=>{execute('${v[0]}',[37],257);assert.deepEqual(read_interpolation_captures(),[]);});
await check('source instrumentation leaves original substitution expression intact once',()=>{const source=cases.direct!;const code=instrument_trusted_schema_map_sources(caseFile('direct'),source,'file:///helper.js');assert.equal(code.split('${age}').length-1,1);assert.ok(source.includes('HSON`'));});
await check('shadow tags are not instrumented',()=>{const source='const HSON=x=>x; HSON`${value}`;';assert.equal(instrument_trusted_schema_map_sources('/x.ts',source,'file:///helper.js'),source);});
const runtime=new TrustedSchemaDiagnosticRuntime(7);
const env={protocolVersion:1,runtimeGeneration:7,requestId:'d5'};
const loaded=await runtime.handle({...env,type:'load',moduleUrl:new URL('./fixtures/schema-d5-runtime.fixture.mts',import.meta.url).href,hsonModuleUrl:new URL('../src/hson.ts',import.meta.url).href});
assert.equal(loaded.type,'loaded',loaded.message);
const site=discover_schema_validation_sources(caseFile('direct'),cases.direct!)[0]!;
const capture=loaded.captures!.find(c=>c.site.templateId===site.interpolation!.templateId)!;
const directSource={templateId:site.templateId,callId:site.callId,binding:site.binding,documentRevision:1,templateRevision:1,associationRevision:1,
  interpolation:{templateId:capture.site.templateId,sourceRevision:capture.site.sourceRevision,evaluationId:capture.evaluationId}};
const request={...env,type:'associate-source' as const,associationId:'d5',schemaId:'user',directSource};
await check('runtime generation envelopes capture evidence',()=>assert.equal(loaded.runtimeGeneration,7));
await check('one current evaluation associates without successful application validation',async()=>assert.equal((await runtime.handle(request)).type,'associated'));
await check('stale source revision is unavailable',async()=>assert.equal((await runtime.handle({...request,directSource:{...directSource,interpolation:{...directSource.interpolation,sourceRevision:'stale'}}})).error,'ASSOCIATION_UNAVAILABLE'));
await check('stale generation is unavailable',async()=>assert.equal((await runtime.handle({...request,runtimeGeneration:8})).error,'ASSOCIATION_UNAVAILABLE'));
await check('unknown evaluation ID is unavailable',async()=>assert.equal((await runtime.handle({...request,directSource:{...directSource,interpolation:{...directSource.interpolation,evaluationId:'other'}}})).error,'ASSOCIATION_UNAVAILABLE'));
await check('equal repeated executions remain ambiguous',async()=>{const s=discover_schema_validation_sources(caseFile('repeated'),cases.repeated!)[0]!;const c=loaded.captures!.find(c=>c.site.templateId===s.interpolation!.templateId)!;assert.equal((await runtime.handle({...request,directSource:{...directSource,templateId:s.templateId,callId:s.callId,interpolation:{templateId:c.site.templateId,sourceRevision:c.site.sourceRevision,evaluationId:c.evaluationId}}})).error,'AMBIGUOUS_REGISTRATION');});
await check('admission failure evidence exists without any Schema call',()=>assert.ok(loaded.captures!.some(c=>c.site.moduleUrl.endsWith('d5-unsupported.ts')&&c.failure?.substitution===0)));
await check('current capture request is request-bound and source-filtered',async()=>{const r=await runtime.handle({...env,type:'captures',requestId:'fresh-capture',moduleUrl:capture.site.moduleUrl});assert.equal(r.requestId,'fresh-capture');assert.equal(r.type,'captured');assert.equal(r.captures?.length,1);});
await check('evaluation repeated after association invalidates authority',async()=>{
  assert.equal((await runtime.handle(request)).type,'associated');
  const tag=(strings:TemplateStringsArray,...values:readonly (string|number|boolean|null)[])=>capture_interpolation(capture.site,HSON,strings,values).canonical;
  tag`<user <age ${'37'}>>`;
  const r=await runtime.handle({...env,type:'validate',associationId:'d5',schemaId:'user',directSource,templateRevision:1,candidateRevision:1,source:capture.source});
  assert.equal(r.error,'AMBIGUOUS_REGISTRATION');
});
await check('uncaught provider admission failure retains trace and failure status',async()=>{
  const r=await new TrustedSchemaDiagnosticRuntime(8).handle({...env,runtimeGeneration:8,type:'load',moduleUrl:new URL('./fixtures/schema-d5-uncaught.fixture.mts',import.meta.url).href,hsonModuleUrl:new URL('../src/hson.ts',import.meta.url).href});
  assert.equal(r.type,'loaded',r.message);assert.ok(r.loadFailure);assert.doesNotMatch(r.loadFailure!,/Unreachable/);assert.equal(r.captures?.[0]?.failure?.substitution,0);
});
emit_hson_live_test_completion('trusted-d5-capture',checks,checks,0);
