import type ts from "typescript";
import { compile_hson_schema, HSON_SCHEMA_MVP_COMPATIBILITY_VERSION, type CompiledHsonSchema } from "../../../src/internal/hson-schema/compiler.js";
import { generate_hson_schema_types } from "../../../src/internal/hson-schema/generate-types.js";
import { evaluate_canonical_document_schema, evaluate_canonical_projected_schema } from "../../../src/internal/canonical-schema/evaluate.js";
import { parse_hson_with_provenance } from "../../../src/internal/hson-source-provenance/parse-hson-with-provenance.js";
import { projected_value_from_hson_node } from "../../../src/core/projected-value-graph.js";

export type VerifiedSchemaAssignmentRange = Readonly<{ start: number; end: number }>;
type SchemaAssociation = Readonly<{ declaration: ts.VariableDeclaration; compiled: CompiledHsonSchema }>;

/** Facts safe for editor diagnostic filtering; this never changes TypeScript types. */
export function verified_schema_assignment_ranges(
  typescript: typeof ts,
  program: ts.Program,
  fileName: string,
): readonly VerifiedSchemaAssignmentRange[] {
  const sourceFile = program.getSourceFile(fileName);
  if (sourceFile === undefined || sourceFile.isDeclarationFile) return Object.freeze([]);
  const checker = program.getTypeChecker();
  const output: VerifiedSchemaAssignmentRange[] = [];
  for (const statement of sourceFile.statements) {
    if (!typescript.isVariableStatement(statement) || (statement.declarationList.flags & typescript.NodeFlags.Const) === 0 || statement.declarationList.declarations.length !== 1) continue;
    const declaration = statement.declarationList.declarations[0];
    if (declaration === undefined || declaration.type === undefined || declaration.initializer === undefined || !typescript.isTypeReferenceNode(declaration.type) || !typescript.isIdentifier(declaration.type.typeName)) continue;
    const association = resolve_schema_association(typescript, program, checker, declaration.type.typeName);
    if (association === undefined || !verified_initializer(typescript, checker, sourceFile, declaration.initializer, association)) continue;
    output.push(Object.freeze({ start: declaration.name.getStart(sourceFile), end: declaration.name.getEnd() }));
  }
  return Object.freeze(output);
}

export function filter_verified_schema_assignment_diagnostics(
  diagnostics: readonly ts.Diagnostic[],
  ranges: readonly VerifiedSchemaAssignmentRange[],
): readonly ts.Diagnostic[] {
  return diagnostics.filter((diagnostic) => {
    const start = diagnostic.start;
    return diagnostic.code !== 2322 || start === undefined || !ranges.some((range) => start >= range.start && start < range.end);
  });
}

function resolve_schema_association(
  typescript: typeof ts,
  program: ts.Program,
  checker: ts.TypeChecker,
  identifier: ts.Identifier,
): SchemaAssociation | undefined {
  let symbol = checker.getSymbolAtLocation(identifier);
  if (symbol !== undefined && (symbol.flags & typescript.SymbolFlags.Alias) !== 0) symbol = checker.getAliasedSymbol(symbol);
  const aliases = (symbol?.declarations ?? []).filter(typescript.isTypeAliasDeclaration);
  if (aliases.length !== 1) return undefined;
  const alias = aliases[0];
  if (alias === undefined || !alias.name.text.endsWith("Hson")) return undefined;
  const generatedFile = alias.getSourceFile();
  const generatedMatch = /^(.*)\.([^.]+)\.hson-schema\.generated\.ts$/.exec(generatedFile.fileName);
  if (generatedMatch === null) return undefined;
  const producerStem = generatedMatch[1], schemaName = generatedMatch[2];
  if (producerStem === undefined || schemaName === undefined) return undefined;
  const producer = [".ts", ".mts", ".cts"].map((extension) => program.getSourceFile(`${producerStem}${extension}`)).find((candidate) => candidate !== undefined);
  if (producer === undefined) return undefined;
  const schema = find_schema_declaration(typescript, checker, producer, schemaName);
  if (schema === undefined) return undefined;
  const compiled = compile_hson_schema(raw_template(schema.template, producer));
  if (!compiled.ok) return undefined;
  const generated = generate_hson_schema_types(schemaName, compiled.value.semantic);
  const numberImport = generated.declarations.includes("HsonNumber") ? 'import type { HsonNumber } from "hson-live";\n' : "";
  const expected = `/* Generated by Hson Schema ${HSON_SCHEMA_MVP_COMPATIBILITY_VERSION}. Do not edit. */\n${numberImport}import type { HsonCanonical } from "hson-live/hson";\n${generated.declarations}\n`;
  if (generatedFile.text !== expected) return undefined;
  return Object.freeze({ declaration: schema.declaration, compiled: compiled.value });
}

function find_schema_declaration(
  typescript: typeof ts,
  checker: ts.TypeChecker,
  sourceFile: ts.SourceFile,
  schemaName: string,
): Readonly<{ declaration: ts.VariableDeclaration; template: ts.NoSubstitutionTemplateLiteral }> | undefined {
  for (const statement of sourceFile.statements) {
    if (!typescript.isVariableStatement(statement) || (statement.declarationList.flags & typescript.NodeFlags.Const) === 0 || statement.declarationList.declarations.length !== 1) continue;
    const declaration = statement.declarationList.declarations[0];
    if (declaration === undefined || !typescript.isIdentifier(declaration.name) || declaration.name.text !== schemaName || declaration.type === undefined || !typescript.isTypeReferenceNode(declaration.type) || !typescript.isIdentifier(declaration.type.typeName)) continue;
    if (!official_binding(typescript, checker, declaration.type.typeName, "HsonSchema") || declaration.initializer === undefined || !typescript.isTaggedTemplateExpression(declaration.initializer) || !typescript.isIdentifier(declaration.initializer.tag) || !official_binding(typescript, checker, declaration.initializer.tag, "Hson") || !typescript.isNoSubstitutionTemplateLiteral(declaration.initializer.template)) return undefined;
    return Object.freeze({ declaration, template: declaration.initializer.template });
  }
  return undefined;
}

function verified_initializer(
  typescript: typeof ts,
  checker: ts.TypeChecker,
  sourceFile: ts.SourceFile,
  initializer: ts.Expression,
  association: SchemaAssociation,
): boolean {
  if (typescript.isTaggedTemplateExpression(initializer)) {
    if (!typescript.isIdentifier(initializer.tag) || !official_binding(typescript, checker, initializer.tag, "Hson") || !typescript.isNoSubstitutionTemplateLiteral(initializer.template)) return false;
    try {
      const parsed = parse_hson_with_provenance(raw_template(initializer.template, sourceFile));
      const result = association.compiled.semantic.kind === "document-element"
        ? evaluate_canonical_document_schema(association.compiled.graph, parsed.value, "element")
        : evaluate_canonical_projected_schema(association.compiled.graph, projected_value_from_hson_node(parsed.value));
      return result.ok;
    } catch {
      return false;
    }
  }
  if (!typescript.isCallExpression(initializer) || !typescript.isPropertyAccessExpression(initializer.expression) || initializer.expression.name.text !== "certify" || !typescript.isIdentifier(initializer.expression.expression) || !official_binding(typescript, checker, initializer.expression.expression, "Hson")) return false;
  const schemaArgument = initializer.arguments[0];
  return schemaArgument !== undefined && typescript.isIdentifier(schemaArgument) && identifier_resolves_to(typescript, checker, schemaArgument, association.declaration);
}

function official_binding(typescript: typeof ts, checker: ts.TypeChecker, identifier: ts.Identifier, expected: "Hson" | "HsonSchema"): boolean {
  const symbol = checker.getSymbolAtLocation(identifier);
  if (symbol !== undefined) {
    const target = (symbol.flags & typescript.SymbolFlags.Alias) !== 0 ? checker.getAliasedSymbol(symbol) : symbol;
    if ((target.getName() === expected || expected === "Hson" && target.getName() === "admit_hson") && target.declarations?.some((declaration) => /(?:^|[/\\])(?:hson-authoring|index|hson-admission|transform\.types)\.(?:d\.)?[cm]?ts$/.test(declaration.getSourceFile().fileName)) === true) return true;
  }
  if (!identifier.parent || !typescript.isImportSpecifier(identifier.parent)) return false;
  const importDeclaration = identifier.parent.parent.parent.parent;
  const importedName = identifier.parent.propertyName?.text ?? identifier.parent.name.text;
  return typescript.isImportDeclaration(importDeclaration) && typescript.isStringLiteral(importDeclaration.moduleSpecifier)
    && ["hson-live", "hson-live/hson"].includes(importDeclaration.moduleSpecifier.text) && importedName === expected;
}

function identifier_resolves_to(typescript: typeof ts, checker: ts.TypeChecker, identifier: ts.Identifier, expected: ts.Declaration): boolean {
  let symbol = checker.getSymbolAtLocation(identifier);
  if (symbol !== undefined && (symbol.flags & typescript.SymbolFlags.Alias) !== 0) symbol = checker.getAliasedSymbol(symbol);
  return symbol?.declarations?.includes(expected) === true;
}

function raw_template(node: ts.NoSubstitutionTemplateLiteral, sourceFile: ts.SourceFile): string {
  const text = node.getText(sourceFile);
  return text.slice(1, -1);
}
