/* Generated by Hson Schema hson-schema-mvp-10. Do not edit. */
import type { HsonSchemaMutationCandidate } from "hson-live";
import type { JsonValue } from "hson-live/hson";
import type { HsonCanonical } from "hson-live/hson";
abstract class __InteractionFieldsSchemaRootObjectProof0 { declare private readonly __hsonSchemaProof0: void; }
abstract class __InteractionFieldsSchemaHsonProof1 { declare private readonly __hsonSchemaProof1: void; }
export type InteractionFieldsSchemaType = Readonly<{ readonly args: JsonValue; readonly payload: JsonValue; }> & __InteractionFieldsSchemaRootObjectProof0 & HsonSchemaMutationCandidate<{ args: JsonValue; payload: JsonValue; }>;
export type InteractionFieldsSchemaHson = HsonCanonical & __InteractionFieldsSchemaHsonProof1;
