/* Generated by Hson Schema hson-schema-mvp-10. Do not edit. */
import type { HsonSchemaMutationCandidate } from "hson-live";
import type { HsonCanonical } from "hson-live/hson";
abstract class __RelationalUniqueSchemaRootM0ItemObjectProof0 { declare private readonly __hsonSchemaProof0: void; }
abstract class __RelationalUniqueSchemaRootM0ArrayProof1 { declare private readonly __hsonSchemaProof1: void; }
abstract class __RelationalUniqueSchemaRootM0UniqueR0Proof2 { declare private readonly __hsonSchemaProof2: void; }
abstract class __RelationalUniqueSchemaRootObjectProof3 { declare private readonly __hsonSchemaProof3: void; }
abstract class __RelationalUniqueSchemaHsonProof4 { declare private readonly __hsonSchemaProof4: void; }
export type RelationalUniqueSchemaType = Readonly<{ readonly cells: ReadonlyArray<Readonly<{ readonly position: string; readonly body: string; }> & __RelationalUniqueSchemaRootM0ItemObjectProof0 & HsonSchemaMutationCandidate<{ position: string; body: string; }>> & __RelationalUniqueSchemaRootM0ArrayProof1 & HsonSchemaMutationCandidate<Array<{ position: string; body: string; }>> & __RelationalUniqueSchemaRootM0UniqueR0Proof2 & HsonSchemaMutationCandidate<Array<{ position: string; body: string; }>>; }> & __RelationalUniqueSchemaRootObjectProof3 & HsonSchemaMutationCandidate<{ cells: Array<{ position: string; body: string; }>; }>;
export type RelationalUniqueSchemaHson = HsonCanonical & __RelationalUniqueSchemaHsonProof4;
