/* Generated by Hson Schema hson-schema-mvp-10. Do not edit. */
import type { HsonSchemaMutationCandidate } from "hson-live";
import type { JsonValue } from "hson-live/hson";
abstract class __InteractionFieldsSchemaRootObjectProof0 { declare private readonly __hsonSchemaProof0: void; }
type __Value = Readonly<{ readonly args: JsonValue; readonly payload: JsonValue; }> & __InteractionFieldsSchemaRootObjectProof0 & HsonSchemaMutationCandidate<{ args: JsonValue; payload: JsonValue; }>;
declare const __Identity: unique symbol;
export type Evidence = Readonly<{ value: __Value; mode: "data"; identity: typeof __Identity }>;
