/* Generated by Hson Schema hson-schema-mvp-4. Do not edit. */
import type { HsonNumber } from "hson-live";
import type { HsonCanonical } from "hson-live/hson";
abstract class __UserSchemaRootM3IntR0Proof0 { declare private readonly __hsonSchemaProof0: void; }
abstract class __UserSchemaRootM3MinR1Proof1 { declare private readonly __hsonSchemaProof1: void; }
abstract class __UserSchemaRootM3UnderR2Proof2 { declare private readonly __hsonSchemaProof2: void; }
abstract class __UserSchemaRootM4MinR0Proof3 { declare private readonly __hsonSchemaProof3: void; }
abstract class __UserSchemaRootM4MaxR1Proof4 { declare private readonly __hsonSchemaProof4: void; }
abstract class __UserSchemaRootM5PrefixR0Proof5 { declare private readonly __hsonSchemaProof5: void; }
abstract class __UserSchemaRootM5ContainsR1Proof6 { declare private readonly __hsonSchemaProof6: void; }
abstract class __UserSchemaRootM5SuffixR2Proof7 { declare private readonly __hsonSchemaProof7: void; }
abstract class __UserSchemaRootM5LenR3Proof8 { declare private readonly __hsonSchemaProof8: void; }
abstract class __UserSchemaRootM7ZeroProof9 { declare private readonly __hsonSchemaProof9: void; }
abstract class __UserSchemaRootM8ZeroProof10 { declare private readonly __hsonSchemaProof10: void; }
abstract class __UserSchemaRootM9ArrayProof11 { declare private readonly __hsonSchemaProof11: void; }
abstract class __UserSchemaRootM9UniqueR0Proof12 { declare private readonly __hsonSchemaProof12: void; }
abstract class __UserSchemaRootM9MinlenR1Proof13 { declare private readonly __hsonSchemaProof13: void; }
abstract class __UserSchemaRootM10TupleProof14 { declare private readonly __hsonSchemaProof14: void; }
abstract class __UserSchemaRootM11U0ObjectProof15 { declare private readonly __hsonSchemaProof15: void; }
abstract class __UserSchemaRootM11U1ObjectProof16 { declare private readonly __hsonSchemaProof16: void; }
abstract class __UserSchemaRootObjectProof17 { declare private readonly __hsonSchemaProof17: void; }
abstract class __UserSchemaHsonProof18 { declare private readonly __hsonSchemaProof18: void; }
export type UserSchemaType = Readonly<{ readonly name: string; readonly nickname?: string; readonly score: HsonNumber; readonly age: HsonNumber & __UserSchemaRootM3IntR0Proof0 & __UserSchemaRootM3MinR1Proof1 & __UserSchemaRootM3UnderR2Proof2; readonly percent: HsonNumber & __UserSchemaRootM4MinR0Proof3 & __UserSchemaRootM4MaxR1Proof4; readonly code: string & __UserSchemaRootM5PrefixR0Proof5 & __UserSchemaRootM5ContainsR1Proof6 & __UserSchemaRootM5SuffixR2Proof7 & __UserSchemaRootM5LenR3Proof8; readonly status: "ready"; readonly zero: 0 & HsonNumber & __UserSchemaRootM7ZeroProof9; readonly negativeZero: 0 & HsonNumber & __UserSchemaRootM8ZeroProof10; readonly flags: ReadonlyArray<boolean> & __UserSchemaRootM9ArrayProof11 & __UserSchemaRootM9UniqueR0Proof12 & __UserSchemaRootM9MinlenR1Proof13; readonly pair: readonly [string, HsonNumber] & __UserSchemaRootM10TupleProof14; readonly account: (Readonly<{ readonly kind: "user"; readonly handle: string; }> & __UserSchemaRootM11U0ObjectProof15) | (Readonly<{ readonly kind: "admin"; readonly level: HsonNumber; }> & __UserSchemaRootM11U1ObjectProof16); }> & __UserSchemaRootObjectProof17;
export type UserSchemaHson = HsonCanonical & __UserSchemaHsonProof18;
