/* Generated by Hson Schema hson-schema-mvp-3. Do not edit. */
import type { HsonNumber } from "hson-live";
import type { HsonCanonical } from "hson-live/hson";
abstract class __UserSchemaRootM4ZeroProof0 { declare private readonly __hsonSchemaProof: void; }
abstract class __UserSchemaRootM5ZeroProof1 { declare private readonly __hsonSchemaProof: void; }
abstract class __UserSchemaRootM6ArrayProof2 { declare private readonly __hsonSchemaProof: void; }
abstract class __UserSchemaRootM7TupleProof3 { declare private readonly __hsonSchemaProof: void; }
abstract class __UserSchemaRootM8U0ObjectProof4 { declare private readonly __hsonSchemaProof: void; }
abstract class __UserSchemaRootM8U1ObjectProof5 { declare private readonly __hsonSchemaProof: void; }
abstract class __UserSchemaRootObjectProof6 { declare private readonly __hsonSchemaProof: void; }
abstract class __UserSchemaHsonProof7 { declare private readonly __hsonSchemaProof: void; }
export type UserSchemaType = Readonly<{ readonly name: string; readonly nickname?: string; readonly score: HsonNumber; readonly status: "ready"; readonly zero: 0 & HsonNumber & __UserSchemaRootM4ZeroProof0; readonly negativeZero: 0 & HsonNumber & __UserSchemaRootM5ZeroProof1; readonly flags: ReadonlyArray<boolean> & __UserSchemaRootM6ArrayProof2; readonly pair: readonly [string, HsonNumber] & __UserSchemaRootM7TupleProof3; readonly account: (Readonly<{ readonly kind: "user"; readonly handle: string; }> & __UserSchemaRootM8U0ObjectProof4) | (Readonly<{ readonly kind: "admin"; readonly level: HsonNumber; }> & __UserSchemaRootM8U1ObjectProof5); }> & __UserSchemaRootObjectProof6;
export type UserSchemaHson = HsonCanonical & __UserSchemaHsonProof7;
