/* Generated by Hson Schema hson-schema-mvp-10. Do not edit. */
import type { JsonValue } from "hson-live/hson";

type __Value = JsonValue;
declare const __Identity: unique symbol;
export type Evidence = Readonly<{ value: __Value; mode: "data"; identity: typeof __Identity }>;
