/* Generated by Hson Schema hson-schema-mvp-10. Do not edit. */
import type { HsonSchemaMutationCandidate } from "hson-live";
abstract class __RelationalUniqueSchemaRootM0ItemObjectProof0 { declare private readonly __hsonSchemaProof0: void; }
abstract class __RelationalUniqueSchemaRootM0ArrayProof1 { declare private readonly __hsonSchemaProof1: void; }
abstract class __RelationalUniqueSchemaRootM0UniqueR0Proof2 { declare private readonly __hsonSchemaProof2: void; }
abstract class __RelationalUniqueSchemaRootObjectProof3 { declare private readonly __hsonSchemaProof3: void; }
type __Value = Readonly<{ readonly cells: ReadonlyArray<Readonly<{ readonly position: string; readonly body: string; }> & __RelationalUniqueSchemaRootM0ItemObjectProof0 & HsonSchemaMutationCandidate<{ position: string; body: string; }>> & __RelationalUniqueSchemaRootM0ArrayProof1 & HsonSchemaMutationCandidate<Array<{ position: string; body: string; }>> & __RelationalUniqueSchemaRootM0UniqueR0Proof2 & HsonSchemaMutationCandidate<Array<{ position: string; body: string; }>>; }> & __RelationalUniqueSchemaRootObjectProof3 & HsonSchemaMutationCandidate<{ cells: Array<{ position: string; body: string; }>; }>;
declare const __Identity: unique symbol;
export type Evidence = Readonly<{ value: __Value; mode: "data"; identity: typeof __Identity }>;
