/* Generated by Hson Schema hson-schema-mvp-10. Do not edit. */
import type { HsonNumber, HsonSchemaMutationCandidate } from "hson-live";
abstract class __TreeSchemaD0M2ArrayProof0 { declare private readonly __hsonSchemaProof0: void; }
abstract class __TreeSchemaD0ObjectProof1 { declare private readonly __hsonSchemaProof1: void; }
abstract class __TreeSchemaD0DefinitionProof2 { declare private readonly __hsonSchemaProof2: void; }
abstract class __TreeSchemaD1IntR0Proof3 { declare private readonly __hsonSchemaProof3: void; }
abstract class __TreeSchemaD1MinR1Proof4 { declare private readonly __hsonSchemaProof4: void; }
abstract class __TreeSchemaD1DefinitionProof5 { declare private readonly __hsonSchemaProof5: void; }
type __TreeSchemaDefinition0MutationCandidate = { value: string; age: __TreeSchemaDefinition1MutationCandidate; children: Array<__TreeSchemaDefinition0MutationCandidate>; };
type __TreeSchemaDefinition1MutationCandidate = number;
type __TreeSchemaDefinition0 = (Readonly<{ readonly value: string; readonly age: __TreeSchemaDefinition1; readonly children: ReadonlyArray<__TreeSchemaDefinition0> & __TreeSchemaD0M2ArrayProof0 & HsonSchemaMutationCandidate<Array<__TreeSchemaDefinition0MutationCandidate>>; }> & __TreeSchemaD0ObjectProof1 & HsonSchemaMutationCandidate<{ value: string; age: __TreeSchemaDefinition1MutationCandidate; children: Array<__TreeSchemaDefinition0MutationCandidate>; }>) & __TreeSchemaD0DefinitionProof2 & HsonSchemaMutationCandidate<__TreeSchemaDefinition0MutationCandidate>;
type __TreeSchemaDefinition1 = (HsonNumber & HsonSchemaMutationCandidate<number> & __TreeSchemaD1IntR0Proof3 & HsonSchemaMutationCandidate<number> & __TreeSchemaD1MinR1Proof4 & HsonSchemaMutationCandidate<number>) & __TreeSchemaD1DefinitionProof5 & HsonSchemaMutationCandidate<__TreeSchemaDefinition1MutationCandidate>;
type __Value = __TreeSchemaDefinition0;
declare const __Identity: unique symbol;
export type Evidence = Readonly<{ value: __Value; mode: "data"; identity: typeof __Identity }>;
