/* Generated by Hson Schema hson-schema-mvp-10. Do not edit. */
import type { HsonSchemaMutationCandidate } from "hson-live";
abstract class __SameShapeOneSchemaRootObjectProof0 { declare private readonly __hsonSchemaProof0: void; }
type __Value = Readonly<{ readonly name: string; }> & __SameShapeOneSchemaRootObjectProof0 & HsonSchemaMutationCandidate<{ name: string; }>;
declare const __Identity: unique symbol;
export type Evidence = Readonly<{ value: __Value; mode: "data"; identity: typeof __Identity }>;
