/* Generated by Hson Schema hson-schema-mvp-5. Do not edit. */
import type { HsonNumber } from "hson-live";
import type { HsonCanonical } from "hson-live/hson";
abstract class __TreeSchemaD0M2ArrayProof0 { declare private readonly __hsonSchemaProof0: void; }
abstract class __TreeSchemaD0ObjectProof1 { declare private readonly __hsonSchemaProof1: void; }
abstract class __TreeSchemaD0DefinitionProof2 { declare private readonly __hsonSchemaProof2: void; }
abstract class __TreeSchemaD1IntR0Proof3 { declare private readonly __hsonSchemaProof3: void; }
abstract class __TreeSchemaD1MinR1Proof4 { declare private readonly __hsonSchemaProof4: void; }
abstract class __TreeSchemaD1DefinitionProof5 { declare private readonly __hsonSchemaProof5: void; }
abstract class __TreeSchemaHsonProof6 { declare private readonly __hsonSchemaProof6: void; }
type __TreeSchemaDefinition0 = (Readonly<{ readonly value: string; readonly age: __TreeSchemaDefinition1; readonly children: ReadonlyArray<__TreeSchemaDefinition0> & __TreeSchemaD0M2ArrayProof0; }> & __TreeSchemaD0ObjectProof1) & __TreeSchemaD0DefinitionProof2;
type __TreeSchemaDefinition1 = (HsonNumber & __TreeSchemaD1IntR0Proof3 & __TreeSchemaD1MinR1Proof4) & __TreeSchemaD1DefinitionProof5;
export type TreeSchemaType = __TreeSchemaDefinition0;
export type TreeSchemaHson = HsonCanonical & __TreeSchemaHsonProof6;
