/* Generated by Hson Schema hson-schema-mvp-5. Do not edit. */
import type { HsonCanonical } from "hson-live/hson";
abstract class __ReuseSchemaD0ObjectProof0 { declare private readonly __hsonSchemaProof0: void; }
abstract class __ReuseSchemaD0DefinitionProof1 { declare private readonly __hsonSchemaProof1: void; }
abstract class __ReuseSchemaD1ObjectProof2 { declare private readonly __hsonSchemaProof2: void; }
abstract class __ReuseSchemaD1DefinitionProof3 { declare private readonly __hsonSchemaProof3: void; }
abstract class __ReuseSchemaRootObjectProof4 { declare private readonly __hsonSchemaProof4: void; }
abstract class __ReuseSchemaHsonProof5 { declare private readonly __hsonSchemaProof5: void; }
type __ReuseSchemaDefinition0 = (Readonly<{ readonly value: string; }> & __ReuseSchemaD0ObjectProof0) & __ReuseSchemaD0DefinitionProof1;
type __ReuseSchemaDefinition1 = (Readonly<{ readonly value: string; }> & __ReuseSchemaD1ObjectProof2) & __ReuseSchemaD1DefinitionProof3;
export type ReuseSchemaType = Readonly<{ readonly left: __ReuseSchemaDefinition0; readonly right: __ReuseSchemaDefinition1; readonly again: __ReuseSchemaDefinition0; }> & __ReuseSchemaRootObjectProof4;
export type ReuseSchemaHson = HsonCanonical & __ReuseSchemaHsonProof5;
