/* Generated by Hson Schema hson-schema-mvp-6. Do not edit. */
import type { HsonCanonical } from "hson-live/hson";
abstract class __FragmentSchemaD0AttrsProof0 { declare private readonly __hsonSchemaProof0: void; }
abstract class __FragmentSchemaD0ElementProof1 { declare private readonly __hsonSchemaProof1: void; }
abstract class __FragmentSchemaD0DefinitionProof2 { declare private readonly __hsonSchemaProof2: void; }
abstract class __FragmentSchemaRootContentRepeatProof3 { declare private readonly __hsonSchemaProof3: void; }
abstract class __FragmentSchemaRootContentClusterProof4 { declare private readonly __hsonSchemaProof4: void; }
abstract class __FragmentSchemaRootFragmentProof5 { declare private readonly __hsonSchemaProof5: void; }
abstract class __FragmentSchemaHsonProof6 { declare private readonly __hsonSchemaProof6: void; }
type __FragmentSchemaDefinition0 = (Readonly<{ readonly $_tag: "item"; readonly $_attrs?: Readonly<{  }> & Readonly<Record<string, unknown>> & __FragmentSchemaD0AttrsProof0; readonly $_content: readonly []; }> & __FragmentSchemaD0ElementProof1) & __FragmentSchemaD0DefinitionProof2;
export type FragmentSchemaType = Readonly<{ readonly $_tag: "_hson_root"; readonly $_content: readonly [Readonly<{ readonly $_tag: "_hson_elem"; readonly $_content: readonly [__FragmentSchemaDefinition0, __FragmentSchemaDefinition0] & __FragmentSchemaRootContentRepeatProof3; }> & __FragmentSchemaRootContentClusterProof4]; }> & __FragmentSchemaRootFragmentProof5;
export type FragmentSchemaHson = HsonCanonical & __FragmentSchemaHsonProof6;
