/* Generated by Hson Schema hson-schema-mvp-10. Do not edit. */
abstract class __DocumentSequenceSchemaD0AttrsProof0 { declare private readonly __hsonSchemaProof0: void; }
abstract class __DocumentSequenceSchemaD0ElementProof1 { declare private readonly __hsonSchemaProof1: void; }
abstract class __DocumentSequenceSchemaD0DefinitionProof2 { declare private readonly __hsonSchemaProof2: void; }
abstract class __DocumentSequenceSchemaRootContentRepeatProof3 { declare private readonly __hsonSchemaProof3: void; }
abstract class __DocumentSequenceSchemaRootDocumentProof4 { declare private readonly __hsonSchemaProof4: void; }
type __DocumentSequenceSchemaDefinition0 = (Readonly<{ readonly $_tag: "item"; readonly $_attrs?: Readonly<{  }> & Readonly<Record<string, unknown>> & __DocumentSequenceSchemaD0AttrsProof0; readonly $_content: readonly []; }> & __DocumentSequenceSchemaD0ElementProof1) & __DocumentSequenceSchemaD0DefinitionProof2;
type __Value = Readonly<{ readonly $_tag: "_hson_root"; readonly $_content: readonly [__DocumentSequenceSchemaDefinition0, __DocumentSequenceSchemaDefinition0] & __DocumentSequenceSchemaRootContentRepeatProof3; }> & __DocumentSequenceSchemaRootDocumentProof4;
declare const __Identity: unique symbol;
export type Evidence = Readonly<{ value: __Value; mode: "document"; identity: typeof __Identity }>;
