/* Generated by Hson Schema hson-schema-mvp-10. Do not edit. */
import type { HsonNode } from "hson-live/hson";
abstract class __MainDocumentSchemaRootContentS0AttrsProof0 { declare private readonly __hsonSchemaProof0: void; }
abstract class __MainDocumentSchemaRootContentS0ElementProof1 { declare private readonly __hsonSchemaProof1: void; }
abstract class __MainDocumentSchemaRootDocumentProof2 { declare private readonly __hsonSchemaProof2: void; }
type __Value = Readonly<{ readonly $_tag: "_hson_root"; readonly $_content: readonly [Readonly<{ readonly $_tag: "main"; readonly $_attrs?: Readonly<{  }> & Readonly<Record<string, unknown>> & __MainDocumentSchemaRootContentS0AttrsProof0; readonly $_content: readonly HsonNode[]; }> & __MainDocumentSchemaRootContentS0ElementProof1]; }> & __MainDocumentSchemaRootDocumentProof2;
declare const __Identity: unique symbol;
export type Evidence = Readonly<{ value: __Value; mode: "document"; identity: typeof __Identity }>;
