/* Generated by Hson Schema hson-schema-mvp-10. Do not edit. */
import type { HsonNode } from "hson-live/hson";
abstract class __AnyDocumentSchemaRootDocumentProof0 { declare private readonly __hsonSchemaProof0: void; }
type __Value = Readonly<{ readonly $_tag: "_hson_root"; readonly $_content: readonly HsonNode[]; }> & __AnyDocumentSchemaRootDocumentProof0;
declare const __Identity: unique symbol;
export type Evidence = Readonly<{ value: __Value; mode: "document"; identity: typeof __Identity }>;
