/* Generated by Hson Schema hson-schema-mvp-10. Do not edit. */
import type { HsonSchemaMutationCandidate } from "hson-live";
abstract class __ListSchemaD0A0Proof0 { declare private readonly __hsonSchemaProof0: void; }
abstract class __ListSchemaD0AttrsProof1 { declare private readonly __hsonSchemaProof1: void; }
abstract class __ListSchemaD0ElementProof2 { declare private readonly __hsonSchemaProof2: void; }
abstract class __ListSchemaD0DefinitionProof3 { declare private readonly __hsonSchemaProof3: void; }
abstract class __ListSchemaD1PrefixR0Proof4 { declare private readonly __hsonSchemaProof4: void; }
abstract class __ListSchemaD1DefinitionProof5 { declare private readonly __hsonSchemaProof5: void; }
abstract class __ListSchemaRootContentS0AttrsProof6 { declare private readonly __hsonSchemaProof6: void; }
abstract class __ListSchemaRootContentS0ContentRepeatProof7 { declare private readonly __hsonSchemaProof7: void; }
abstract class __ListSchemaRootContentS0ContentClusterProof8 { declare private readonly __hsonSchemaProof8: void; }
abstract class __ListSchemaRootContentS0ElementProof9 { declare private readonly __hsonSchemaProof9: void; }
abstract class __ListSchemaRootDocumentProof10 { declare private readonly __hsonSchemaProof10: void; }
type __ListSchemaDefinition1MutationCandidate = string;
type __ListSchemaDefinition0 = (Readonly<{ readonly $_tag: "item"; readonly $_attrs: Readonly<{ readonly code: string & __ListSchemaD0A0Proof0; }> & Readonly<Record<string, unknown>> & __ListSchemaD0AttrsProof1; readonly $_content: readonly []; }> & __ListSchemaD0ElementProof2) & __ListSchemaD0DefinitionProof3;
type __ListSchemaDefinition1 = (string & __ListSchemaD1PrefixR0Proof4 & HsonSchemaMutationCandidate<string>) & __ListSchemaD1DefinitionProof5 & HsonSchemaMutationCandidate<__ListSchemaDefinition1MutationCandidate>;
type __Value = Readonly<{ readonly $_tag: "_hson_root"; readonly $_content: readonly [Readonly<{ readonly $_tag: "list"; readonly $_attrs?: Readonly<{  }> & Readonly<Record<string, unknown>> & __ListSchemaRootContentS0AttrsProof6; readonly $_content: readonly [Readonly<{ readonly $_tag: "_hson_elem"; readonly $_content: readonly [__ListSchemaDefinition0, __ListSchemaDefinition0] & __ListSchemaRootContentS0ContentRepeatProof7; }> & __ListSchemaRootContentS0ContentClusterProof8]; }> & __ListSchemaRootContentS0ElementProof9]; }> & __ListSchemaRootDocumentProof10;
declare const __Identity: unique symbol;
export type Evidence = Readonly<{ value: __Value; mode: "document"; identity: typeof __Identity }>;
