/* Generated by Hson Schema hson-schema-mvp-6. Do not edit. */
import type { HsonCanonical } from "hson-live/hson";
abstract class __PageSchemaRootA0Proof0 { declare private readonly __hsonSchemaProof0: void; }
abstract class __PageSchemaRootAttrsProof1 { declare private readonly __hsonSchemaProof1: void; }
abstract class __PageSchemaRootContentS0AttrsProof2 { declare private readonly __hsonSchemaProof2: void; }
abstract class __PageSchemaRootContentS0ContentS0TextProof3 { declare private readonly __hsonSchemaProof3: void; }
abstract class __PageSchemaRootContentS0ContentClusterProof4 { declare private readonly __hsonSchemaProof4: void; }
abstract class __PageSchemaRootContentS0ElementProof5 { declare private readonly __hsonSchemaProof5: void; }
abstract class __PageSchemaRootContentClusterProof6 { declare private readonly __hsonSchemaProof6: void; }
abstract class __PageSchemaRootElementProof7 { declare private readonly __hsonSchemaProof7: void; }
abstract class __PageSchemaHsonProof8 { declare private readonly __hsonSchemaProof8: void; }
export type PageSchemaType = Readonly<{ readonly $_tag: "main"; readonly $_attrs: Readonly<{ readonly id: string & __PageSchemaRootA0Proof0; readonly hidden?: "hidden"; }> & Readonly<Record<string, unknown>> & __PageSchemaRootAttrsProof1; readonly $_content: readonly [Readonly<{ readonly $_tag: "_hson_elem"; readonly $_content: readonly [Readonly<{ readonly $_tag: "section"; readonly $_attrs?: Readonly<{  }> & Readonly<Record<string, unknown>> & __PageSchemaRootContentS0AttrsProof2; readonly $_content: readonly [Readonly<{ readonly $_tag: "_hson_elem"; readonly $_content: readonly [Readonly<{ readonly $_tag: "_hson_str"; readonly $_content: readonly [string]; }> & __PageSchemaRootContentS0ContentS0TextProof3]; }> & __PageSchemaRootContentS0ContentClusterProof4]; }> & __PageSchemaRootContentS0ElementProof5]; }> & __PageSchemaRootContentClusterProof6]; }> & __PageSchemaRootElementProof7;
export type PageSchemaHson = HsonCanonical & __PageSchemaHsonProof8;
