/* Generated by Hson Schema hson-schema-mvp-10. Do not edit. */
abstract class __PageSchemaRootContentS0A0Proof0 { declare private readonly __hsonSchemaProof0: void; }
abstract class __PageSchemaRootContentS0AttrsProof1 { declare private readonly __hsonSchemaProof1: void; }
abstract class __PageSchemaRootContentS0ContentS0AttrsProof2 { declare private readonly __hsonSchemaProof2: void; }
abstract class __PageSchemaRootContentS0ContentS0ContentS0TextProof3 { declare private readonly __hsonSchemaProof3: void; }
abstract class __PageSchemaRootContentS0ContentS0ContentClusterProof4 { declare private readonly __hsonSchemaProof4: void; }
abstract class __PageSchemaRootContentS0ContentS0ElementProof5 { declare private readonly __hsonSchemaProof5: void; }
abstract class __PageSchemaRootContentS0ContentClusterProof6 { declare private readonly __hsonSchemaProof6: void; }
abstract class __PageSchemaRootContentS0ElementProof7 { declare private readonly __hsonSchemaProof7: void; }
abstract class __PageSchemaRootDocumentProof8 { declare private readonly __hsonSchemaProof8: void; }
type __Value = Readonly<{ readonly $_tag: "_hson_root"; readonly $_content: readonly [Readonly<{ readonly $_tag: "main"; readonly $_attrs: Readonly<{ readonly id: string & __PageSchemaRootContentS0A0Proof0; readonly hidden?: "hidden"; }> & Readonly<Record<string, unknown>> & __PageSchemaRootContentS0AttrsProof1; readonly $_content: readonly [Readonly<{ readonly $_tag: "_hson_elem"; readonly $_content: readonly [Readonly<{ readonly $_tag: "section"; readonly $_attrs?: Readonly<{  }> & Readonly<Record<string, unknown>> & __PageSchemaRootContentS0ContentS0AttrsProof2; readonly $_content: readonly [Readonly<{ readonly $_tag: "_hson_elem"; readonly $_content: readonly [Readonly<{ readonly $_tag: "_hson_str"; readonly $_content: readonly [string]; }> & __PageSchemaRootContentS0ContentS0ContentS0TextProof3]; }> & __PageSchemaRootContentS0ContentS0ContentClusterProof4]; }> & __PageSchemaRootContentS0ContentS0ElementProof5]; }> & __PageSchemaRootContentS0ContentClusterProof6]; }> & __PageSchemaRootContentS0ElementProof7]; }> & __PageSchemaRootDocumentProof8;
declare const __Identity: unique symbol;
export type Evidence = Readonly<{ value: __Value; mode: "document"; identity: typeof __Identity }>;
