import assert from "node:assert/strict";
import { hson } from "../../src/hson.ts";
import type { JsonValue, LiveMapCore } from "../../src/types/index.ts";
import { mutation_operator, own_record, type DeterministicLiveMapOperator } from "./operator-catalog.mts";

type Map = LiveMapCore<JsonValue | undefined>;

function exact_is(expected: string | JsonValue): (map: Map) => void {
  return (map) => assert.equal(map.capture().payload, hson.liveMap.fromJson(expected).capture().payload);
}

export const mutation_operators: readonly DeterministicLiveMapOperator[] = Object.freeze([
  mutation_operator("mutation/primitive-string-change", "replace a primitive string", "A different primitive replaces the selected scalar.", "Path value exists and is a string.", "change", { value: "before" }, '"after"', (map) => map.set(["value"], "after"), exact_is({ value: "after" })),
  mutation_operator("mutation/primitive-same-noop", "replace a primitive with itself", "SameValue replacement publishes no commit.", "Candidate is SameValue-equal to the selected primitive.", "no-op", { value: true }, "true", (map) => map.set(["value"], true), exact_is({ value: true })),
  mutation_operator("mutation/positive-to-negative-zero", "replace positive zero with negative zero", "Object.is distinguishes the two zero signs.", "Selected value is +0.", "change", { value: 0 }, "-0", (map) => map.set(["value"], -0), (map) => assert.equal(Object.is(map.snap(["value"]), -0), true)),
  mutation_operator("mutation/negative-zero-noop", "replace negative zero with negative zero", "SameValue negative zero is a no-op.", "Selected value and candidate are -0.", "no-op", { value: -0 }, "-0", (map) => map.set(["value"], -0), (map) => assert.equal(Object.is(map.snap(["value"]), -0), true)),
  mutation_operator("mutation/object-add-append", "append a new object property", "A missing property appends after existing entries.", "Parent is an object and key d is absent.", "change", '{"a":1,"b":2,"c":3}', 'path=["d"] value=4', (map) => map.at([]).object.setKey("d", 4), exact_is('{"a":1,"b":2,"c":3,"d":4}')),
  mutation_operator("mutation/object-replace-retain", "replace an existing object property", "Existing-property replacement retains semantic position.", "Parent is an object and key b exists.", "change", '{"a":1,"b":2,"c":3}', 'path=["b"] value=20', (map) => map.set(["b"], 20), exact_is('{"a":1,"b":20,"c":3}')),
  mutation_operator("mutation/object-delete", "delete an existing object property", "Deletion removes exactly one selected entry.", "Own key b exists.", "change", '{"a":1,"b":2,"c":3}', 'path=["b"]', (map) => map.delete(["b"]), exact_is('{"a":1,"c":3}')),
  mutation_operator("mutation/object-delete-missing", "delete a missing object property", "Deleting an absent property is a no-op.", "Parent is an object and key missing is absent.", "no-op", '{"a":1,"b":2}', 'path=["missing"]', (map) => map.at([]).object.deleteKey("missing"), exact_is('{"a":1,"b":2}')),
  mutation_operator("mutation/object-rename-position", "rename an object property in place", "Rename retains the source entry position.", "Source b exists and destination renamed is absent.", "change", '{"a":1,"b":2,"c":3}', 'from="b" to="renamed"', (map) => map.at([]).object.renameKey("b", "renamed"), exact_is('{"a":1,"renamed":2,"c":3}')),
  mutation_operator("mutation/object-order-only-replace", "replace with reordered object entries", "Object-property order alone is semantic.", "Replacement has equal pairs in different order.", "change", '{"a":1,"b":2}', 'ordered entries=[["b",2],["a",1]]', (map) => map.replace(own_record([["b", 2], ["a", 1]])), exact_is('{"b":2,"a":1}')),
  mutation_operator("mutation/integer-key-retain", "replace an integer-like property", "Replacing an integer-like key retains canonical graph order.", "Exact root order is 10,2,1 and key 2 exists.", "change", '{"10":10,"2":2,"1":1}', 'path=["2"] value=20', (map) => map.set(["2"], 20), exact_is('{"10":10,"2":20,"1":1}')),
  mutation_operator("mutation/dangerous-proto-add", "add __proto__ as own data", "The dangerous spelling is an ordinary property key.", "Root object lacks an own __proto__ entry.", "change", {}, 'own key="__proto__" value="data"', (map) => map.at([]).object.setKey("__proto__", "data"), (map) => { const value = map.snap() as object; assert.equal(Object.hasOwn(value, "__proto__"), true); assert.equal(Object.getPrototypeOf(value), Object.prototype); }),
  mutation_operator("mutation/dangerous-constructor-add", "add constructor as own data", "Inherited Object.prototype members do not define canonical membership.", "Root lacks an own constructor entry.", "change", {}, 'own key="constructor" value=-0', (map) => map.at([]).object.setKey("constructor", -0), (map) => assert.equal(Object.is((map.snap() as Record<string, JsonValue>).constructor, -0), true)),
  mutation_operator("mutation/dangerous-prototype-add", "add prototype as own data", "The dangerous spelling is preserved verbatim.", "Root lacks an own prototype entry.", "change", {}, 'own key="prototype" value=null', (map) => map.at([]).object.setKey("prototype", null), (map) => assert.equal(Object.hasOwn(map.snap() as object, "prototype"), true)),
  mutation_operator("mutation/set-many-admitted-order", "merge several object properties", "Existing entries retain position and new entries append in admitted order.", "Root is an object; b exists; d and c are absent.", "change", '{"a":1,"b":2}', 'entries=[["b",20],["d",4],["c",3]]', (map) => map.setMany([], own_record([["b", 20], ["d", 4], ["c", 3]])), exact_is('{"a":1,"b":20,"d":4,"c":3}')),
  mutation_operator("mutation/array-insert", "insert one dense array item", "Insertion shifts later items and preserves density.", "Index 1 is a valid insertion point.", "change", { items: [1, 3] }, 'path=["items"] index=1 value=2', (map) => map.at(["items"]).array.insert(1, 2), exact_is({ items: [1, 2, 3] })),
  mutation_operator("mutation/array-replace", "replace one dense array item", "Replacement changes one position without changing length.", "Index 1 exists.", "change", { items: [1, 2, 3] }, 'path=["items"] index=1 value=-0', (map) => map.at(["items"]).array.replace(1, -0), (map) => { const items = map.snap(["items"]) as number[]; assert.equal(items.length, 3); assert.equal(Object.is(items[1], -0), true); }),
  mutation_operator("mutation/array-remove", "remove one dense array item", "Removal closes the index gap.", "Index 1 exists.", "change", { items: [1, 2, 3] }, 'path=["items"] index=1', (map) => map.at(["items"]).array.remove(1), exact_is({ items: [1, 3] })),
  mutation_operator("mutation/array-move", "move one dense array item", "Movement removes and inserts one existing item deterministically.", "Indexes 0 and 2 exist in the same array.", "change", { items: ["a", "b", "c"] }, 'path=["items"] from=0 to=2', (map) => map.at(["items"]).array.move(0, 2), exact_is({ items: ["b", "c", "a"] })),
  mutation_operator("mutation/nested-object-array", "replace a nested array object", "Nested replacement preserves surrounding order, density, dangerous keys, and -0.", "Path outer.items.0 resolves to an object.", "change", { outer: { items: [{ a: 1 }] } }, 'path=["outer","items",0] entries=[["10",-0],["__proto__","data"]]', (map) => map.replace(["outer", "items", 0], own_record([["10", -0], ["__proto__", "data"]])), (map) => { const value = map.snap(["outer", "items", 0]) as Record<string, JsonValue>; assert.equal(Object.is(value["10"], -0), true); assert.equal(value.__proto__, "data"); }),
]);
