export const DOCUMENT_MIRROR_REVISION_GAP_ERROR_CODE = "DOCUMENT_MIRROR_REVISION_GAP" as const;
export const DOCUMENT_MIRROR_UNSUPPORTED_OPERATION_ERROR_CODE = "DOCUMENT_MIRROR_UNSUPPORTED_OPERATION" as const;
export const DOCUMENT_MIRROR_TARGET_MISSING_ERROR_CODE = "DOCUMENT_MIRROR_TARGET_MISSING" as const;
export const DOCUMENT_MIRROR_QUID_MISMATCH_ERROR_CODE = "DOCUMENT_MIRROR_QUID_MISMATCH" as const;
export const DOCUMENT_MIRROR_NODE_KIND_MISMATCH_ERROR_CODE = "DOCUMENT_MIRROR_NODE_KIND_MISMATCH" as const;
export const DOCUMENT_MIRROR_DOM_MAPPING_MISMATCH_ERROR_CODE = "DOCUMENT_MIRROR_DOM_MAPPING_MISMATCH" as const;
export const DOCUMENT_MIRROR_UPDATE_FAILED_ERROR_CODE = "DOCUMENT_MIRROR_UPDATE_FAILED" as const;
export const DOCUMENT_MIRROR_ALREADY_BOUND_ERROR_CODE = "DOCUMENT_MIRROR_ALREADY_BOUND" as const;
export const DOCUMENT_MIRROR_DISPOSED_ERROR_CODE = "DOCUMENT_MIRROR_DISPOSED" as const;
export const DOCUMENT_MIRROR_CONTENT_PATH_INVALID_ERROR_CODE = "DOCUMENT_MIRROR_CONTENT_PATH_INVALID" as const;
export const DOCUMENT_MIRROR_CONTENT_INDEX_INVALID_ERROR_CODE = "DOCUMENT_MIRROR_CONTENT_INDEX_INVALID" as const;
export const DOCUMENT_MIRROR_CONTENT_MISMATCH_ERROR_CODE = "DOCUMENT_MIRROR_CONTENT_MISMATCH" as const;
export const DOCUMENT_MIRROR_QUID_COLLISION_ERROR_CODE = "DOCUMENT_MIRROR_QUID_COLLISION" as const;
export const DOCUMENT_MIRROR_REUSE_INCOMPATIBLE_ERROR_CODE = "DOCUMENT_MIRROR_REUSE_INCOMPATIBLE" as const;
export const DOCUMENT_MIRROR_STRUCTURAL_UPDATE_FAILED_ERROR_CODE = "DOCUMENT_MIRROR_STRUCTURAL_UPDATE_FAILED" as const;
export const DOCUMENT_MIRROR_DELEGATION_UNSUPPORTED_ERROR_CODE = "DOCUMENT_MIRROR_DELEGATION_UNSUPPORTED" as const;
export const DOCUMENT_MIRROR_DELEGATION_TARGET_INVALID_ERROR_CODE = "DOCUMENT_MIRROR_DELEGATION_TARGET_INVALID" as const;
export const DOCUMENT_MIRROR_DELEGATION_ROOT_FORBIDDEN_ERROR_CODE = "DOCUMENT_MIRROR_DELEGATION_ROOT_FORBIDDEN" as const;
export const DOCUMENT_MIRROR_ROOT_MATERIAL_MISSING_ERROR_CODE = "DOCUMENT_MIRROR_ROOT_MATERIAL_MISSING" as const;
export const DOCUMENT_MIRROR_ROOT_KIND_MISMATCH_ERROR_CODE = "DOCUMENT_MIRROR_ROOT_KIND_MISMATCH" as const;
export const DOCUMENT_MIRROR_ROOT_QUID_CONFLICT_ERROR_CODE = "DOCUMENT_MIRROR_ROOT_QUID_CONFLICT" as const;
export const DOCUMENT_MIRROR_ROOT_VALIDATION_FAILED_ERROR_CODE = "DOCUMENT_MIRROR_ROOT_VALIDATION_FAILED" as const;
export const DOCUMENT_MIRROR_ROOT_REPLACEMENT_FAILED_ERROR_CODE = "DOCUMENT_MIRROR_ROOT_REPLACEMENT_FAILED" as const;
export const DOCUMENT_MIRROR_SNAPSHOT_REVISION_MISMATCH_ERROR_CODE = "DOCUMENT_MIRROR_SNAPSHOT_REVISION_MISMATCH" as const;
export const DOCUMENT_MIRROR_SNAPSHOT_CAPTURE_FAILED_ERROR_CODE = "DOCUMENT_MIRROR_SNAPSHOT_CAPTURE_FAILED" as const;

export type DocumentMirrorErrorCode =
  | typeof DOCUMENT_MIRROR_REVISION_GAP_ERROR_CODE
  | typeof DOCUMENT_MIRROR_UNSUPPORTED_OPERATION_ERROR_CODE
  | typeof DOCUMENT_MIRROR_TARGET_MISSING_ERROR_CODE
  | typeof DOCUMENT_MIRROR_QUID_MISMATCH_ERROR_CODE
  | typeof DOCUMENT_MIRROR_NODE_KIND_MISMATCH_ERROR_CODE
  | typeof DOCUMENT_MIRROR_DOM_MAPPING_MISMATCH_ERROR_CODE
  | typeof DOCUMENT_MIRROR_UPDATE_FAILED_ERROR_CODE
  | typeof DOCUMENT_MIRROR_ALREADY_BOUND_ERROR_CODE
  | typeof DOCUMENT_MIRROR_DISPOSED_ERROR_CODE
  | typeof DOCUMENT_MIRROR_CONTENT_PATH_INVALID_ERROR_CODE
  | typeof DOCUMENT_MIRROR_CONTENT_INDEX_INVALID_ERROR_CODE
  | typeof DOCUMENT_MIRROR_CONTENT_MISMATCH_ERROR_CODE
  | typeof DOCUMENT_MIRROR_QUID_COLLISION_ERROR_CODE
  | typeof DOCUMENT_MIRROR_REUSE_INCOMPATIBLE_ERROR_CODE
  | typeof DOCUMENT_MIRROR_STRUCTURAL_UPDATE_FAILED_ERROR_CODE
  | typeof DOCUMENT_MIRROR_DELEGATION_UNSUPPORTED_ERROR_CODE
  | typeof DOCUMENT_MIRROR_DELEGATION_TARGET_INVALID_ERROR_CODE
  | typeof DOCUMENT_MIRROR_DELEGATION_ROOT_FORBIDDEN_ERROR_CODE
  | typeof DOCUMENT_MIRROR_ROOT_MATERIAL_MISSING_ERROR_CODE
  | typeof DOCUMENT_MIRROR_ROOT_KIND_MISMATCH_ERROR_CODE
  | typeof DOCUMENT_MIRROR_ROOT_QUID_CONFLICT_ERROR_CODE
  | typeof DOCUMENT_MIRROR_ROOT_VALIDATION_FAILED_ERROR_CODE
  | typeof DOCUMENT_MIRROR_ROOT_REPLACEMENT_FAILED_ERROR_CODE
  | typeof DOCUMENT_MIRROR_SNAPSHOT_REVISION_MISMATCH_ERROR_CODE
  | typeof DOCUMENT_MIRROR_SNAPSHOT_CAPTURE_FAILED_ERROR_CODE;

/** Internal classified failure for the experimental document projection proof. */
export class DocumentMirrorError extends Error {
  public constructor(
    public readonly code: DocumentMirrorErrorCode,
    message: string,
    public override readonly cause?: unknown,
  ) {
    super(message, cause === undefined ? undefined : { cause });
    this.name = "DocumentMirrorError";
  }
}
