export const COLLECTION_MIRROR_INVALID_SOURCE_ERROR_CODE = "COLLECTION_MIRROR_INVALID_SOURCE" as const;
export const COLLECTION_MIRROR_DUPLICATE_KEY_ERROR_CODE = "COLLECTION_MIRROR_DUPLICATE_KEY" as const;
export const COLLECTION_MIRROR_MISSING_IDENTITY_ERROR_CODE = "COLLECTION_MIRROR_MISSING_IDENTITY" as const;
export const COLLECTION_MIRROR_INVALID_BRANCH_ERROR_CODE = "COLLECTION_MIRROR_INVALID_BRANCH" as const;
export const COLLECTION_MIRROR_BRANCH_ATTACHED_ERROR_CODE = "COLLECTION_MIRROR_BRANCH_ATTACHED" as const;
export const COLLECTION_MIRROR_MAPPING_CONFLICT_ERROR_CODE = "COLLECTION_MIRROR_MAPPING_CONFLICT" as const;
export const COLLECTION_MIRROR_DISPOSED_ERROR_CODE = "COLLECTION_MIRROR_DISPOSED" as const;
export const COLLECTION_MIRROR_SOURCE_REPLACEMENT_ERROR_CODE = "COLLECTION_MIRROR_SOURCE_REPLACEMENT_FAILED" as const;
export const COLLECTION_MIRROR_UNSUPPORTED_OPERATION_ERROR_CODE = "COLLECTION_MIRROR_UNSUPPORTED_OPERATION" as const;
export const COLLECTION_MIRROR_RENDERER_CREATE_ERROR_CODE = "COLLECTION_MIRROR_RENDERER_CREATE_FAILED" as const;
export const COLLECTION_MIRROR_RENDERER_UPDATE_ERROR_CODE = "COLLECTION_MIRROR_RENDERER_UPDATE_FAILED" as const;
export const COLLECTION_MIRROR_HOST_NOT_EMPTY_ERROR_CODE = "COLLECTION_MIRROR_HOST_NOT_EMPTY" as const;

export type CollectionMirrorErrorCode =
  | typeof COLLECTION_MIRROR_INVALID_SOURCE_ERROR_CODE
  | typeof COLLECTION_MIRROR_DUPLICATE_KEY_ERROR_CODE
  | typeof COLLECTION_MIRROR_MISSING_IDENTITY_ERROR_CODE
  | typeof COLLECTION_MIRROR_INVALID_BRANCH_ERROR_CODE
  | typeof COLLECTION_MIRROR_BRANCH_ATTACHED_ERROR_CODE
  | typeof COLLECTION_MIRROR_MAPPING_CONFLICT_ERROR_CODE
  | typeof COLLECTION_MIRROR_DISPOSED_ERROR_CODE
  | typeof COLLECTION_MIRROR_SOURCE_REPLACEMENT_ERROR_CODE
  | typeof COLLECTION_MIRROR_UNSUPPORTED_OPERATION_ERROR_CODE
  | typeof COLLECTION_MIRROR_RENDERER_CREATE_ERROR_CODE
  | typeof COLLECTION_MIRROR_RENDERER_UPDATE_ERROR_CODE
  | typeof COLLECTION_MIRROR_HOST_NOT_EMPTY_ERROR_CODE;

/** Stable classified failure raised by the experimental projection engine. */
export class CollectionMirrorError extends Error {
  public readonly code: CollectionMirrorErrorCode;
  public readonly cause: unknown;

  public constructor(code: CollectionMirrorErrorCode, message: string, cause?: unknown) {
    super(message);
    this.name = "CollectionMirrorError";
    this.code = code;
    this.cause = cause;
  }
}
