export type HsonLiveTestSubject =
  | "Locus"
  | "LiveHost"
  | "LiveMap"
  | "Reflect"
  | "LiveTree"
  | "Transform"
  | "Core";

export type HsonLiveTestRuntime =
  | "node"
  | "node-synthetic-dom"
  | "node-real-websocket"
  | "node-real-websocket-process";

/** Every registered launcher must emit exactly one valid terminal completion record. */
export const HSON_LIVE_TEST_COMPLETION_REQUIREMENT = "valid-terminal-completion" as const;

export type HsonLiveTestLauncher = Readonly<{
  id: string;
  subject: HsonLiveTestSubject;
  displayName: string;
  packageScript: `test:${string}`;
  repositoryModule: `tests/${string}`;
  runtime: HsonLiveTestRuntime;
  collections: readonly string[];
}>;

export type HsonLiveNonLauncherTestScript = Readonly<{
  packageScript: `test:${string}`;
  reason: string;
}>;

function launcher(
  value: Omit<HsonLiveTestLauncher, "collections"> & {
    collections: readonly string[];
  },
): HsonLiveTestLauncher {
  return Object.freeze({
    ...value,
    collections: Object.freeze([...value.collections]),
  });
}

export const hson_live_test_launchers: readonly HsonLiveTestLauncher[] =
  Object.freeze([
    launcher({
      id: "core.hson-number",
      subject: "Core",
      displayName: "Hson numeric admission",
      packageScript: "test:hson-number",
      repositoryModule: "tests/hson-number.acceptance.mts",
      runtime: "node",
      collections: ["hson", "number", "admission", "public-api", "externally-discoverable"],
    }),
    launcher({
      id: "transform.hson-tokenizer",
      subject: "Transform",
      displayName: "Hson tokenizer",
      packageScript: "test:hson-tokenizer",
      repositoryModule: "tests/hson-tokenizer.acceptance.mts",
      runtime: "node",
      collections: ["hson", "tokenization", "parsing"],
    }),
    launcher({
      id: "transform.hson-tagged-template",
      subject: "Transform",
      displayName: "Hson tagged-template admission",
      packageScript: "test:hson-tagged-template",
      repositoryModule: "tests/hson-tagged-template.acceptance.mts",
      runtime: "node",
      collections: ["hson", "admission", "tagged-template", "public-api", "diagnostics", "externally-discoverable"],
    }),
    launcher({
      id: "transform.embedded-hson-diagnostic-mapping",
      subject: "Transform",
      displayName: "Embedded Hson diagnostic mapping",
      packageScript: "test:embedded-hson-diagnostic-mapping",
      repositoryModule: "tests/embedded-hson-diagnostic-mapping.acceptance.mts",
      runtime: "node",
      collections: ["hson", "diagnostics", "embedded-source", "tooling", "externally-discoverable"],
    }),
    launcher({
      id: "transform.hson-tagged-template-discovery",
      subject: "Transform",
      displayName: "Hson tagged-template discovery",
      packageScript: "test:hson-tagged-template-discovery",
      repositoryModule: "tests/hson-tagged-template-discovery.acceptance.mts",
      runtime: "node",
      collections: ["hson", "discovery", "tagged-template", "tooling", "externally-discoverable"],
    }),
    launcher({
      id: "transform.hson-quoted-name-acceptance",
      subject: "Transform",
      displayName: "Hson single-quoted name acceptance and canonicalization",
      packageScript: "test:hson-quoted-name-acceptance",
      repositoryModule: "tests/hson-quoted-name-acceptance.acceptance.mts",
      runtime: "node",
      collections: ["hson", "quoted-name", "parsing", "serialization", "round-trip", "externally-discoverable"],
    }),
    launcher({
      id: "transform.hson-quoted-name-rejection",
      subject: "Transform",
      displayName: "Hson quoted-name rejection and legacy syntax",
      packageScript: "test:hson-quoted-name-rejection",
      repositoryModule: "tests/hson-quoted-name-rejection.acceptance.mts",
      runtime: "node",
      collections: ["hson", "quoted-name", "rejection", "diagnostics", "externally-discoverable"],
    }),
    launcher({
      id: "transform.hson-root-boundary",
      subject: "Transform",
      displayName: "Hson root detachment and source shaping",
      packageScript: "test:hson-root-boundary",
      repositoryModule: "tests/hson-root-boundary.acceptance.mts",
      runtime: "node",
      collections: ["hson", "parsing", "root-boundary", "source-shaping"],
    }),
    launcher({
      id: "transform.hson-source-provenance-core",
      subject: "Transform",
      displayName: "Hson source provenance core",
      packageScript: "test:hson-source-provenance-core",
      repositoryModule: "tests/hson-source-provenance-core.acceptance.mts",
      runtime: "node",
      collections: ["hson", "parsing", "source-provenance", "internal"],
    }),
    launcher({
      id: "transform.hson-source-provenance-parser",
      subject: "Transform",
      displayName: "Hson source provenance parser",
      packageScript: "test:hson-source-provenance-parser",
      repositoryModule: "tests/hson-source-provenance-parser.acceptance.mts",
      runtime: "node",
      collections: ["hson", "parsing", "source-provenance", "canonical-graph", "internal"],
    }),
    launcher({
      id: "transform.hson-source-provenance-boundary",
      subject: "Transform",
      displayName: "Hson source provenance boundary and canonicalization",
      packageScript: "test:hson-source-provenance-boundary",
      repositoryModule: "tests/hson-source-provenance-boundary.acceptance.mts",
      runtime: "node",
      collections: ["hson", "parsing", "source-provenance", "root-boundary", "internal"],
    }),
    launcher({
      id: "schema-hson-public", subject: "LiveMap", displayName: "Hson Schema public facade boundaries",
      packageScript: "test:schema-hson-public", repositoryModule: "tests/schema-hson-public.acceptance.mts", runtime: "node", collections: ["schema", "public-boundary"],
    }),
    launcher({
      id: "echo.reflect-authoring", subject: "Reflect", displayName: "Echo reflected document authoring",
      packageScript: "test:echo-reflect-authoring", repositoryModule: "tests/echo-reflect-authoring.acceptance.mts", runtime: "node", collections: ["echo", "reflect", "document", "authoring"],
    }),
    launcher({
      id: "livemap.library-ownership", subject: "LiveMap", displayName: "LiveMap library ownership",
      packageScript: "test:livemap-library-ownership", repositoryModule: "tests/livemap-library-ownership.acceptance.mts", runtime: "node", collections: ["livemap", "libraries", "ownership"],
    }),
    launcher({
      id: "livemap.aggregate-library-transitions", subject: "LiveMap", displayName: "LiveMap aggregate library transitions",
      packageScript: "test:livemap-aggregate-library-transitions", repositoryModule: "tests/livemap-aggregate-library-transitions.acceptance.mts", runtime: "node", collections: ["livemap", "libraries", "aggregate", "transitions"],
    }),
    launcher({
      id: "livemap.n-library-engine", subject: "LiveMap", displayName: "LiveMap N-library engine",
      packageScript: "test:livemap-n-library-engine", repositoryModule: "tests/livemap-n-library-engine.acceptance.mts", runtime: "node", collections: ["livemap", "libraries", "aggregate", "engine"],
    }),
    launcher({
      id: "livemap.public-libraries", subject: "LiveMap", displayName: "LiveMap public libraries",
      packageScript: "test:livemap-public-libraries", repositoryModule: "tests/livemap-public-libraries.acceptance.mts", runtime: "node", collections: ["livemap", "libraries", "public-api"],
    }),
    launcher({
      id: "livemap.hosted-multi-library-h1", subject: "LiveMap", displayName: "Hosted multi-library H1",
      packageScript: "test:livemap-hosted-multi-library-h1", repositoryModule: "tests/livemap-hosted-multi-library-h1.acceptance.mts", runtime: "node", collections: ["livemap", "libraries", "hosted", "h1"],
    }),
    launcher({
      id: "locus.hosted-multi-library-h2", subject: "Locus", displayName: "Hosted multi-library H2",
      packageScript: "test:locus-hosted-multi-library-h2", repositoryModule: "tests/locus-hosted-multi-library-h2.acceptance.mts", runtime: "node", collections: ["locus", "livemap", "libraries", "hosted", "h2"],
    }),
    launcher({
      id: "locus.hosted-multi-library-h3", subject: "Locus", displayName: "Hosted multi-library H3",
      packageScript: "test:locus-hosted-multi-library-h3", repositoryModule: "tests/locus-hosted-multi-library-h3.acceptance.mts", runtime: "node", collections: ["locus", "livemap", "libraries", "hosted", "h3"],
    }),
    launcher({
      id: "locus.hosted-multi-library-h4", subject: "Locus", displayName: "Hosted multi-library H4",
      packageScript: "test:locus-hosted-multi-library-h4", repositoryModule: "tests/locus-hosted-multi-library-h4.acceptance.mts", runtime: "node", collections: ["locus", "livemap", "libraries", "hosted", "h4"],
    }),
    launcher({
      id: "locus.hosted-multi-library-h5", subject: "Locus", displayName: "Hosted multi-library H5",
      packageScript: "test:locus-hosted-multi-library-h5", repositoryModule: "tests/locus-hosted-multi-library-h5.acceptance.mts", runtime: "node", collections: ["locus", "echo", "livemap", "libraries", "hosted", "h5"],
    }),
    launcher({
      id: "locus.hosted-multi-library-action-pipeline", subject: "Locus", displayName: "Hosted multi-library action pipeline",
      packageScript: "test:locus-hosted-multi-library-action-pipeline", repositoryModule: "tests/locus-hosted-multi-library-action-pipeline.acceptance.mts", runtime: "node", collections: ["locus", "echo", "livemap", "libraries", "actions"],
    }),
    launcher({
      id: "livemap-hson-schema-mutation-proof", subject: "LiveMap", displayName: "LiveMap Hson Schema mutation proof",
      packageScript: "test:livemap-hson-schema-mutation-proof", repositoryModule: "tests/livemap-hson-schema-mutation-proof.acceptance.mts", runtime: "node", collections: ["livemap", "hson-schema", "mutation", "public-api"],
    }),
    launcher({
      id: "livemap-hson-schema-transition-proof", subject: "LiveMap", displayName: "LiveMap Hson Schema transition proof",
      packageScript: "test:livemap-hson-schema-transition-proof", repositoryModule: "tests/livemap-hson-schema-transition-proof.acceptance.mts", runtime: "node", collections: ["livemap", "hson-schema", "transitions"],
    }),
    launcher({
      id: "hson-schema-mvp", subject: "LiveMap", displayName: "Hson Schema MVP",
      packageScript: "test:hson-schema-mvp", repositoryModule: "tests/hson-schema-mvp.acceptance.mts", runtime: "node", collections: ["hson-schema", "compiler", "canonical-schema"],
    }),
    launcher({
      id: "hson-schema-livemap-convergence", subject: "LiveMap", displayName: "Hson Schema LiveMap convergence",
      packageScript: "test:hson-schema-livemap-convergence", repositoryModule: "tests/hson-schema-livemap-convergence.acceptance.mts", runtime: "node", collections: ["hson-schema", "livemap", "convergence"],
    }),
    launcher({
      id: "hson-schema-composition-recursion", subject: "LiveMap", displayName: "Hson Schema composition and recursion",
      packageScript: "test:hson-schema-composition-recursion", repositoryModule: "tests/hson-schema-composition-recursion.acceptance.mts", runtime: "node", collections: ["hson-schema", "composition", "recursion"],
    }),
    launcher({
      id: "hson-schema-document", subject: "LiveMap", displayName: "Hson document Schema",
      packageScript: "test:hson-schema-document", repositoryModule: "tests/hson-schema-document.acceptance.mts", runtime: "node", collections: ["hson-schema", "document", "canonical-schema"],
    }),
    launcher({
      id: "hson-schema-analyzer", subject: "LiveMap", displayName: "Hson Schema analyzer",
      packageScript: "test:hson-schema-analyzer", repositoryModule: "tests/hson-schema-analyzer.acceptance.mts", runtime: "node", collections: ["hson-schema", "analyzer", "tooling"],
    }),
    launcher({
      id: "canonical-schema-verifier", subject: "LiveMap", displayName: "Canonical Schema verifier",
      packageScript: "test:canonical-schema-verifier", repositoryModule: "tests/canonical-schema-verifier.acceptance.mts", runtime: "node", collections: ["hson-schema", "canonical-schema", "verification"],
    }),
    launcher({
      id: "canonical-schema-refinement", subject: "LiveMap", displayName: "Canonical Schema refinement",
      packageScript: "test:canonical-schema-refinement", repositoryModule: "tests/canonical-schema-refinement.acceptance.mts", runtime: "node", collections: ["hson-schema", "canonical-schema", "refinement"],
    }),
    launcher({
      id: "canonical-schema-resource-semantics", subject: "LiveMap", displayName: "Canonical Schema resource semantics",
      packageScript: "test:canonical-schema-resource-semantics", repositoryModule: "tests/canonical-schema-resource-semantics.acceptance.mts", runtime: "node", collections: ["hson-schema", "canonical-schema", "resources"],
    }),
    launcher({
      id: "canonical-schema-static-authoring", subject: "LiveMap", displayName: "Canonical Schema static authoring",
      packageScript: "test:canonical-schema-static-authoring", repositoryModule: "tests/canonical-schema-static-authoring.acceptance.mts", runtime: "node", collections: ["hson-schema", "canonical-schema", "authoring"],
    }),
    launcher({
      id: "static-hson-js-literal-mapping", subject: "Transform", displayName: "D4 JavaScript literal cooking and source mapping",
      packageScript: "test:static-hson-js-literal-mapping", repositoryModule: "tests/static-hson-js-literal-mapping.acceptance.mts", runtime: "node", collections: ["hson", "authoring", "diagnostics", "internal"],
    }),
    launcher({
      id: "from-hson-static-discovery", subject: "Transform", displayName: "D4 official fromHson binding discovery",
      packageScript: "test:from-hson-static-discovery", repositoryModule: "tests/from-hson-static-discovery.acceptance.mts", runtime: "node", collections: ["hson", "authoring", "discovery", "internal"],
    }),
    launcher({
      id: "transform.hson-serializer",
      subject: "Transform",
      displayName: "Hson serializer",
      packageScript: "test:hson-serializer",
      repositoryModule: "tests/hson-serializer.acceptance.mts",
      runtime: "node",
      collections: ["hson", "serialization", "round-trip"],
    }),
    launcher({
      id: "transform.sha256",
      subject: "Transform",
      displayName: "Transform serialized SHA-256",
      packageScript: "test:transform-sha256",
      repositoryModule: "tests/transform-sha256.acceptance.mts",
      runtime: "node",
      collections: ["serialization", "sha256", "webcrypto", "public-api", "externally-discoverable"],
    }),
    launcher({
      id: "transform.binary-hson-vectors",
      subject: "Transform",
      displayName: "Canonical Binary Hson golden vectors",
      packageScript: "test:binary-hson-vectors",
      repositoryModule: "tests/binary-hson.acceptance.mts",
      runtime: "node",
      collections: ["binary", "serialization", "canonical-graph", "sha256", "public-api", "externally-discoverable"],
    }),
    launcher({
      id: "transform.json-ingress",
      subject: "Transform",
      displayName: "Detached JSON ingress and root metadata",
      packageScript: "test:json-ingress",
      repositoryModule: "tests/json-ingress.acceptance.mts",
      runtime: "node",
      collections: ["json", "ingress", "canonical-graph", "externally-discoverable"],
    }),
    launcher({
      id: "core.hson-node-quid",
      subject: "Transform",
      displayName: "Canonical HsonNode QUID primitives",
      packageScript: "test:hson-node-quid",
      repositoryModule: "tests/hson-node-quid.acceptance.mts",
      runtime: "node",
      collections: ["quid", "canonical-graph", "externally-discoverable"],
    }),
    launcher({
      id: "transform.hson-node-quid-ingress",
      subject: "Transform",
      displayName: "Canonical HsonNode QUID ingress",
      packageScript: "test:hson-node-quid-ingress",
      repositoryModule: "tests/hson-node-quid-ingress.acceptance.mts",
      runtime: "node-synthetic-dom",
      collections: ["quid", "ingress", "externally-discoverable"],
    }),
    launcher({
      id: "transform.hson-node-quid-egress",
      subject: "Transform",
      displayName: "Canonical HsonNode QUID egress",
      packageScript: "test:hson-node-quid-egress",
      repositoryModule: "tests/hson-node-quid-egress.acceptance.mts",
      runtime: "node-synthetic-dom",
      collections: ["quid", "egress", "serialization", "externally-discoverable"],
    }),
    launcher({
      id: "core.canonical-hson-equality",
      subject: "Core",
      displayName: "Canonical Hson equality",
      packageScript: "test:canonical-hson-equality",
      repositoryModule: "tests/canonical-hson-equality.acceptance.mts",
      runtime: "node",
      collections: ["canonical-graph", "equality"],
    }),
    launcher({
      id: "transform.canonical-oracle",
      subject: "Transform",
      displayName: "Canonical Transform oracle and deterministic witnesses",
      packageScript: "test:transform-oracle",
      repositoryModule: "tests/transform-oracle.acceptance.mts",
      runtime: "node",
      collections: ["canonical-graph", "oracle", "deterministic-witness"],
    }),
    launcher({
      id: "diagnostics.circuit-semantic-engine",
      subject: "Transform",
      displayName: "Circuit semantic engine",
      packageScript: "test:circuit-semantic-engine",
      repositoryModule: "tests/circuit-semantic-engine.acceptance.mts",
      runtime: "node",
      collections: ["diagnostics", "circuit", "canonical-graph", "strict-comparison"],
    }),
    launcher({
      id: "diagnostics.circuit-failure-control",
      subject: "Transform",
      displayName: "Circuit failure and execution control",
      packageScript: "test:circuit-failure-control",
      repositoryModule: "tests/circuit-failure-control.acceptance.mts",
      runtime: "node",
      collections: ["diagnostics", "circuit", "failure-propagation", "operation-accounting"],
    }),
    launcher({
      id: "diagnostics.circuit-legacy-wrapper",
      subject: "Transform",
      displayName: "Circuit legacy wrapper compatibility",
      packageScript: "test:circuit-legacy-wrapper",
      repositoryModule: "tests/circuit-legacy-wrapper.acceptance.mts",
      runtime: "node-synthetic-dom",
      collections: ["diagnostics", "circuit", "browser-html", "compatibility"],
    }),
    launcher({
      id: "diagnostics.universal-circuit-verification",
      subject: "Transform",
      displayName: "Universal circuit verification facade",
      packageScript: "test:universal-circuit-verification",
      repositoryModule: "tests/universal-circuit-verification.acceptance.mts",
      runtime: "node",
      collections: ["diagnostics", "circuit", "universal", "worker", "externally-discoverable"],
    }),
    launcher({
      id: "livemap.view-state-snapshot-codec",
      subject: "LiveMap",
      displayName: "View-state snapshot codec",
      packageScript: "test:view-state-snapshot-codec",
      repositoryModule: "tests/view-state-snapshot-codec.acceptance.mts",
      runtime: "node",
      collections: ["document", "snapshot", "codec"],
    }),
    launcher({
      id: "core.public-boundaries",
      subject: "Core",
      displayName: "Public package boundaries",
      packageScript: "test:public-boundaries",
      repositoryModule: "tests/public-boundaries.acceptance.mts",
      runtime: "node",
      collections: ["public-api", "LiveMap", "LiveTree", "Transform"],
    }),
    launcher({
      id: "livetree.attrs",
      subject: "LiveTree",
      displayName: "LiveTree canonical attributes",
      packageScript: "test:livetree-attrs",
      repositoryModule: "tests/livetree-attrs.acceptance.mts",
      runtime: "node-synthetic-dom",
      collections: ["attributes", "style", "dom-projection"],
    }),
    launcher({
      id: "livetree.dom-realm",
      subject: "LiveTree",
      displayName: "LiveTree mapped DOM realm boundaries",
      packageScript: "test:livetree-dom-realm",
      repositoryModule: "tests/livetree-dom-realm.acceptance.mts",
      runtime: "node",
      collections: ["dom-projection", "runtime", "realm", "externally-discoverable"],
    }),
    launcher({
      id: "livetree.quid-eligibility",
      subject: "LiveTree",
      displayName: "LiveTree QUID eligibility",
      packageScript: "test:livetree-quid-eligibility",
      repositoryModule: "tests/livetree-quid-eligibility.acceptance.mts",
      runtime: "node",
      collections: ["quid", "eligibility", "identity", "externally-discoverable"],
    }),
    launcher({
      id: "livetree.runtime-scope",
      subject: "LiveTree",
      displayName: "LiveTree runtime scope isolation",
      packageScript: "test:livetree-runtime-scope",
      repositoryModule: "tests/livetree-runtime-scope.acceptance.mts",
      runtime: "node-synthetic-dom",
      collections: ["quid", "runtime", "lifecycle", "css", "Reflect", "externally-discoverable"],
    }),
    launcher({
      id: "livetree.issued-quid-lifecycle",
      subject: "LiveTree",
      displayName: "LiveTree runtime issued-QUID lifecycle",
      packageScript: "test:livetree-issued-quid-lifecycle",
      repositoryModule: "tests/livetree-issued-quid-lifecycle.acceptance.mts",
      runtime: "node-synthetic-dom",
      collections: ["quid", "runtime", "lifecycle", "identity", "externally-discoverable"],
    }),
    launcher({
      id: "livetree.terminal-reuse-boundaries",
      subject: "LiveTree",
      displayName: "LiveTree terminal QUID reuse boundaries",
      packageScript: "test:livetree-terminal-reuse-boundaries",
      repositoryModule: "tests/livetree-terminal-reuse-boundaries.acceptance.mts",
      runtime: "node-synthetic-dom",
      collections: ["quid", "runtime", "lifecycle", "identity", "externally-discoverable"],
    }),
    launcher({
      id: "livetree.quid-runtime-closure",
      subject: "LiveTree",
      displayName: "LiveTree QUID runtime closure",
      packageScript: "test:livetree-quid-runtime-closure",
      repositoryModule: "tests/livetree-quid-runtime-closure.acceptance.mts",
      runtime: "node-synthetic-dom",
      collections: ["quid", "runtime", "lifecycle", "Reflect", "externally-discoverable"],
    }),
    launcher({
      id: "reflect.document-attrs",
      subject: "Reflect",
      displayName: "Document Reflect attributes",
      packageScript: "test:reflect-document-attrs",
      repositoryModule: "tests/reflect-document-attrs.acceptance.mts",
      runtime: "node-synthetic-dom",
      collections: ["document", "binding", "attributes"],
    }),
    launcher({
      id: "reflect.document-structure",
      subject: "Reflect",
      displayName: "Document Reflect structure",
      packageScript: "test:reflect-document-structure",
      repositoryModule: "tests/reflect-document-structure.acceptance.mts",
      runtime: "node-synthetic-dom",
      collections: ["document", "binding", "structure"],
    }),
    launcher({
      id: "reflect.document-root",
      subject: "Reflect",
      displayName: "Document Reflect root update",
      packageScript: "test:reflect-document-root",
      repositoryModule: "tests/reflect-document-root.acceptance.mts",
      runtime: "node-synthetic-dom",
      collections: ["document", "binding", "root"],
    }),
    launcher({
      id: "reflect.document-snapshot",
      subject: "Reflect",
      displayName: "Document Reflect snapshot update",
      packageScript: "test:reflect-document-snapshot",
      repositoryModule: "tests/reflect-document-snapshot.acceptance.mts",
      runtime: "node-synthetic-dom",
      collections: ["document", "binding", "snapshot"],
    }),
    launcher({
      id: "reflect.document-path-authority",
      subject: "Reflect",
      displayName: "Document Reflect path authority",
      packageScript: "test:reflect-document-path-authority",
      repositoryModule: "tests/reflect-document-path-authority.acceptance.mts",
      runtime: "node-synthetic-dom",
      collections: ["document", "binding", "path", "identity", "externally-discoverable"],
    }),
    launcher({
      id: "reflect.document-continuity",
      subject: "Reflect",
      displayName: "Document Reflect continuity",
      packageScript: "test:reflect-document-continuity",
      repositoryModule: "tests/reflect-document-continuity.acceptance.mts",
      runtime: "node-synthetic-dom",
      collections: ["document", "binding", "continuity", "lifecycle", "externally-discoverable"],
    }),
    launcher({
      id: "reflect.livemap-publication-order",
      subject: "Reflect",
      displayName: "LiveMap and Reflection publication ordering",
      packageScript: "test:livemap-reflection-publication-order",
      repositoryModule: "tests/livemap-reflection-publication-order.acceptance.mts",
      runtime: "node-synthetic-dom",
      collections: ["document", "binding", "publication", "observer", "reentrancy", "failure", "externally-discoverable"],
    }),
    launcher({
      id: "reflect.document-correspondence",
      subject: "Reflect",
      displayName: "Document Reflect correspondence",
      packageScript: "test:reflect-document-correspondence",
      repositoryModule: "tests/reflect-document-correspondence.acceptance.mts",
      runtime: "node-synthetic-dom",
      collections: ["document", "binding", "correspondence", "failure", "externally-discoverable"],
    }),
    launcher({
      id: "reflect.linked-no-mint-projection",
      subject: "Reflect",
      displayName: "Document Reflect linked no-mint projection",
      packageScript: "test:reflect-linked-no-mint-projection",
      repositoryModule: "tests/reflect-linked-no-mint-projection.acceptance.mts",
      runtime: "node-synthetic-dom",
      collections: ["document", "binding", "quid", "runtime", "externally-discoverable"],
    }),
    launcher({
      id: "reflect.supplied-identity-preservation",
      subject: "Reflect",
      displayName: "Document Reflect supplied identity preservation",
      packageScript: "test:reflect-supplied-identity-preservation",
      repositoryModule: "tests/reflect-supplied-identity-preservation.acceptance.mts",
      runtime: "node-synthetic-dom",
      collections: ["document", "binding", "quid", "runtime", "externally-discoverable"],
    }),
    launcher({
      id: "reflect.no-mint-regression-boundaries",
      subject: "Reflect",
      displayName: "Document Reflect no-mint regression boundaries",
      packageScript: "test:reflect-no-mint-regression-boundaries",
      repositoryModule: "tests/reflect-no-mint-regression-boundaries.acceptance.mts",
      runtime: "node-synthetic-dom",
      collections: ["document", "binding", "quid", "runtime", "provenance", "externally-discoverable"],
    }),
    launcher({
      id: "livemap.linked-identity-registration",
      subject: "LiveMap",
      displayName: "Linked identity authority registration",
      packageScript: "test:livemap-linked-identity-registration",
      repositoryModule: "tests/livemap-linked-identity-registration.acceptance.mts",
      runtime: "node-synthetic-dom",
      collections: ["document", "binding", "quid", "runtime", "authority", "externally-discoverable"],
    }),
    launcher({
      id: "livemap.linked-identity-atomicity",
      subject: "LiveMap",
      displayName: "Linked identity preflight and atomicity",
      packageScript: "test:livemap-linked-identity-atomicity",
      repositoryModule: "tests/livemap-linked-identity-atomicity.acceptance.mts",
      runtime: "node-synthetic-dom",
      collections: ["document", "binding", "quid", "runtime", "atomicity", "externally-discoverable"],
    }),
    launcher({
      id: "livemap.linked-identity-closure",
      subject: "LiveMap",
      displayName: "Linked identity replay and resource closure",
      packageScript: "test:livemap-linked-identity-closure",
      repositoryModule: "tests/livemap-linked-identity-closure.acceptance.mts",
      runtime: "node-synthetic-dom",
      collections: ["document", "binding", "quid", "runtime", "locus", "externally-discoverable"],
    }),
    launcher({
      id: "livemap.document-identity-acquisition",
      subject: "LiveMap",
      displayName: "Internal sparse document identity acquisition",
      packageScript: "test:livemap-document-identity-acquisition",
      repositoryModule: "tests/livemap-document-identity-acquisition.acceptance.mts",
      runtime: "node",
      collections: ["document", "quid", "identity-handle", "authority", "externally-discoverable"],
    }),
    launcher({
      id: "livemap.document-identity-handle",
      subject: "LiveMap",
      displayName: "Active-epoch document identity handle lifecycle",
      packageScript: "test:livemap-document-identity-handle",
      repositoryModule: "tests/livemap-document-identity-handle.acceptance.mts",
      runtime: "node",
      collections: ["document", "quid", "identity-handle", "lifecycle", "provenance", "externally-discoverable"],
    }),
    launcher({
      id: "livemap.document-identity-compatibility",
      subject: "LiveMap",
      displayName: "Raw-QUID compatibility fences and reflected closure",
      packageScript: "test:livemap-document-identity-compatibility",
      repositoryModule: "tests/livemap-document-identity-compatibility.acceptance.mts",
      runtime: "node-synthetic-dom",
      collections: ["document", "quid", "identity-handle", "compatibility", "binding", "externally-discoverable"],
    }),
    launcher({
      id: "livemap.quid-canonical-state",
      subject: "LiveMap",
      displayName: "LiveMap QUID canonical-state contract",
      packageScript: "test:livemap-quid-canonical-state",
      repositoryModule: "tests/livemap-quid-canonical-state.acceptance.mts",
      runtime: "node",
      collections: ["document", "quid", "canonical-graph", "revision", "externally-discoverable"],
    }),
    launcher({
      id: "livemap.quid-non-minting",
      subject: "LiveMap",
      displayName: "LiveMap sparse QUID non-minting contract",
      packageScript: "test:livemap-quid-non-minting",
      repositoryModule: "tests/livemap-quid-non-minting.acceptance.mts",
      runtime: "node",
      collections: ["document", "quid", "sparse-identity", "non-minting", "externally-discoverable"],
    }),
    launcher({
      id: "livemap.capture-categories",
      subject: "LiveMap",
      displayName: "Document capture identity categories",
      packageScript: "test:livemap-capture-categories",
      repositoryModule: "tests/livemap-capture-categories.acceptance.mts",
      runtime: "node",
      collections: ["document", "quid", "capture", "admission", "externally-discoverable"],
    }),
    launcher({
      id: "livemap.capture-provenance",
      subject: "LiveMap",
      displayName: "Document capture epoch provenance",
      packageScript: "test:livemap-capture-provenance",
      repositoryModule: "tests/livemap-capture-provenance.acceptance.mts",
      runtime: "node",
      collections: ["document", "quid", "capture", "provenance", "atomicity", "externally-discoverable"],
    }),
    launcher({
      id: "locus.capture-identity-closure",
      subject: "Locus",
      displayName: "Locus and Reflection capture identity closure",
      packageScript: "test:locus-capture-identity-closure",
      repositoryModule: "tests/locus-capture-identity-closure.acceptance.mts",
      runtime: "node-synthetic-dom",
      collections: ["document", "quid", "capture", "locus", "reflection", "externally-discoverable"],
    }),
    launcher({
      id: "livemap.projected-identity-acquisition",
      subject: "LiveMap",
      displayName: "Internal sparse data identity acquisition",
      packageScript: "test:livemap-projected-identity-acquisition",
      repositoryModule: "tests/livemap-projected-identity-acquisition.acceptance.mts",
      runtime: "node",
      collections: ["projected-value", "quid", "identity-handle", "authority", "externally-discoverable"],
    }),
    launcher({
      id: "livemap.identity-aba-prevention",
      subject: "LiveMap",
      displayName: "Same-epoch QUID ABA prevention",
      packageScript: "test:livemap-identity-aba-prevention",
      repositoryModule: "tests/livemap-identity-aba-prevention.acceptance.mts",
      runtime: "node",
      collections: ["projected-value", "document", "quid", "identity-handle", "lifecycle", "provenance", "externally-discoverable"],
    }),
    launcher({
      id: "livemap.document-identity-overlay-construction",
      subject: "LiveMap",
      displayName: "Sparse document identity overlay construction",
      packageScript: "test:livemap-document-identity-overlay-construction",
      repositoryModule: "tests/livemap-document-identity-overlay-construction.acceptance.mts",
      runtime: "node",
      collections: ["document", "quid", "path", "sparse-identity", "construction", "externally-discoverable"],
    }),
    launcher({
      id: "livemap.document-identity-overlay-lookup",
      subject: "LiveMap",
      displayName: "Document identity overlay lookup and agreement",
      packageScript: "test:livemap-document-identity-overlay-lookup",
      repositoryModule: "tests/livemap-document-identity-overlay-lookup.acceptance.mts",
      runtime: "node",
      collections: ["document", "quid", "path", "lookup", "invariants", "externally-discoverable"],
    }),
    launcher({
      id: "livemap.document-identity-overlay-lifecycle",
      subject: "LiveMap",
      displayName: "Document identity overlay lifecycle and atomic installation",
      packageScript: "test:livemap-document-identity-overlay-lifecycle",
      repositoryModule: "tests/livemap-document-identity-overlay-lifecycle.acceptance.mts",
      runtime: "node",
      collections: ["document", "quid", "path", "lifecycle", "atomicity", "externally-discoverable"],
    }),
    launcher({
      id: "livemap.document-operation-identity-effects",
      subject: "LiveMap",
      displayName: "Document operation-derived identity effects",
      packageScript: "test:livemap-document-operation-identity-effects",
      repositoryModule: "tests/livemap-document-operation-identity-effects.acceptance.mts",
      runtime: "node",
      collections: ["document", "quid", "path", "identity-effects", "reconciliation", "externally-discoverable"],
    }),
    launcher({
      id: "livemap.document-atomic-reconciliation",
      subject: "LiveMap",
      displayName: "Atomic document identity reconciliation",
      packageScript: "test:livemap-document-atomic-reconciliation",
      repositoryModule: "tests/livemap-document-atomic-reconciliation.acceptance.mts",
      runtime: "node",
      collections: ["document", "quid", "path", "atomicity", "rollback", "externally-discoverable"],
    }),
    launcher({
      id: "livemap.document-staged-reconciliation",
      subject: "LiveMap",
      displayName: "Staged document identity reconciliation",
      packageScript: "test:livemap-document-staged-reconciliation",
      repositoryModule: "tests/livemap-document-staged-reconciliation.acceptance.mts",
      runtime: "node",
      collections: ["document", "quid", "path", "staging", "replay", "reconciliation", "externally-discoverable"],
    }),
    launcher({
      id: "livemap.document-request-lowering",
      subject: "LiveMap",
      displayName: "Document QUID-request lowering boundary",
      packageScript: "test:livemap-document-request-lowering",
      repositoryModule: "tests/livemap-document-request-lowering.acceptance.mts",
      runtime: "node",
      collections: ["document", "quid", "path", "request-lowering", "canonical-target", "externally-discoverable"],
    }),
    launcher({
      id: "livemap.document-staged-request-lowering",
      subject: "LiveMap",
      displayName: "Staged document QUID-request lowering",
      packageScript: "test:livemap-document-staged-request-lowering",
      repositoryModule: "tests/livemap-document-staged-request-lowering.acceptance.mts",
      runtime: "node",
      collections: ["document", "quid", "path", "request-lowering", "staging", "atomicity", "externally-discoverable"],
    }),
    launcher({
      id: "livemap.document-path-contract",
      subject: "LiveMap",
      displayName: "Canonical document-path contract",
      packageScript: "test:livemap-document-path-contract",
      repositoryModule: "tests/livemap-document-path-contract.acceptance.mts",
      runtime: "node",
      collections: ["document", "path", "canonical-graph", "externally-discoverable"],
    }),
    launcher({
      id: "livemap.document-logical-traversal",
      subject: "LiveMap",
      displayName: "Internal logical document traversal",
      packageScript: "test:livemap-document-logical-traversal",
      repositoryModule: "tests/livemap-document-logical-traversal.acceptance.mts",
      runtime: "node",
      collections: ["document", "path", "traversal", "canonical-graph", "externally-discoverable"],
    }),
    launcher({
      id: "livemap.document-location",
      subject: "LiveMap",
      displayName: "Public logical document locations",
      packageScript: "test:livemap-document-location",
      repositoryModule: "tests/livemap-document-location.acceptance.mts",
      runtime: "node",
      collections: ["document", "path", "traversal", "watch", "public-api", "externally-discoverable"],
    }),
    launcher({
      id: "livemap.document-location-mutation",
      subject: "LiveMap",
      displayName: "Document location replace and delete convergence",
      packageScript: "test:livemap-document-location-mutation",
      repositoryModule: "tests/livemap-document-location-mutation.acceptance.mts",
      runtime: "node-synthetic-dom",
      collections: ["document", "path", "mutation", "proxy", "reflection", "public-api", "externally-discoverable"],
    }),
    launcher({
      id: "livemap.document-location-content",
      subject: "LiveMap",
      displayName: "Document location ordered-content convergence",
      packageScript: "test:livemap-document-location-content",
      repositoryModule: "tests/livemap-document-location-content.acceptance.mts",
      runtime: "node-synthetic-dom",
      collections: ["document", "path", "mutation", "proxy", "reflection", "public-api", "externally-discoverable"],
    }),
    launcher({
      id: "livemap.document-location-attrs",
      subject: "LiveMap",
      displayName: "Document location attrs convergence",
      packageScript: "test:livemap-document-location-attrs",
      repositoryModule: "tests/livemap-document-location-attrs.acceptance.mts",
      runtime: "node-synthetic-dom",
      collections: ["document", "path", "mutation", "attrs", "proxy", "reflection", "public-api", "externally-discoverable"],
    }),
    launcher({
      id: "livemap.document-staging",
      subject: "LiveMap",
      displayName: "Staged canonical document operations",
      packageScript: "test:livemap-document-staging",
      repositoryModule: "tests/livemap-document-staging.acceptance.mts",
      runtime: "node",
      collections: ["document", "path", "staging", "replay", "externally-discoverable"],
    }),
    launcher({
      id: "livemap.document-install",
      subject: "LiveMap",
      displayName: "Document LiveMap installation",
      packageScript: "test:livemap-document-install",
      repositoryModule: "tests/livemap-document-install.acceptance.mts",
      runtime: "node",
      collections: ["document", "installation", "identity"],
    }),
    launcher({
      id: "livemap.document-mutation",
      subject: "LiveMap",
      displayName: "Document LiveMap mutation",
      packageScript: "test:livemap-document-mutation",
      repositoryModule: "tests/livemap-document-mutation.acceptance.mts",
      runtime: "node",
      collections: ["document", "mutation", "attributes", "content"],
    }),
    launcher({
      id: "livemap.projected-value-equivalence",
      subject: "LiveMap",
      displayName: "LiveMap ordered projected-value equivalence",
      packageScript: "test:livemap-projected-value-equivalence",
      repositoryModule: "tests/livemap-projected-value-equivalence.acceptance.mts",
      runtime: "node",
      collections: ["projected-value", "canonical-graph", "equivalence", "externally-discoverable"],
    }),
    launcher({
      id: "livemap.exact-propagation",
      subject: "LiveMap",
      displayName: "LiveMap exact carrier propagation",
      packageScript: "test:livemap-exact-propagation",
      repositoryModule: "tests/livemap-exact-propagation.acceptance.mts",
      runtime: "node",
      collections: ["projected-value", "feed", "link", "store", "locus", "externally-discoverable"],
    }),
    launcher({
      id: "livemap.transform-accepted-closure",
      subject: "LiveMap",
      displayName: "Transform–LiveMap accepted-value closure",
      packageScript: "test:livemap-transform-accepted-closure",
      repositoryModule: "tests/livemap-transform-accepted-closure.acceptance.mts",
      runtime: "node",
      collections: ["projected-value", "equivalence", "canonical-graph", "closure", "externally-discoverable"],
    }),
    launcher({
      id: "livemap.deterministic-mutation-operators",
      subject: "LiveMap",
      displayName: "Deterministic LiveMap mutation operators",
      packageScript: "test:livemap-deterministic-mutation-operators",
      repositoryModule: "tests/livemap-deterministic-mutation-operators.acceptance.mts",
      runtime: "node",
      collections: ["projected-value", "operators", "mutation", "deterministic", "externally-discoverable"],
    }),
    launcher({
      id: "livemap.deterministic-admission-schema-operators",
      subject: "LiveMap",
      displayName: "Deterministic LiveMap admission and schema operators",
      packageScript: "test:livemap-deterministic-admission-schema-operators",
      repositoryModule: "tests/livemap-deterministic-admission-schema-operators.acceptance.mts",
      runtime: "node",
      collections: ["projected-value", "operators", "admission", "schema", "deterministic", "externally-discoverable"],
    }),
    launcher({
      id: "core.projected-value-admission",
      subject: "LiveMap",
      displayName: "Projected-value admission and materialization",
      packageScript: "test:projected-value-admission",
      repositoryModule: "tests/projected-value-admission.acceptance.mts",
      runtime: "node",
      collections: ["projected-value", "admission", "materialization", "externally-discoverable"],
    }),
    launcher({
      id: "core.projected-value-equality",
      subject: "LiveMap",
      displayName: "Ordered projected-value equality",
      packageScript: "test:projected-value-equality",
      repositoryModule: "tests/projected-value-equality.acceptance.mts",
      runtime: "node",
      collections: ["projected-value", "equality", "same-value", "externally-discoverable"],
    }),
    launcher({
      id: "locus.authority",
      subject: "Locus",
      displayName: "Locus authority",
      packageScript: "test:locus-authority",
      repositoryModule: "tests/runtime-probes/locus-authority.acceptance.mjs",
      runtime: "node",
      collections: ["authority", "lifecycle", "commit"],
    }),
    launcher({
      id: "locus.persistence",
      subject: "Locus",
      displayName: "Persistent Locus",
      packageScript: "test:locus-persistence",
      repositoryModule: "tests/runtime-probes/locus-persistence.acceptance.mjs",
      runtime: "node",
      collections: ["persistence", "authority", "recovery"],
    }),
    launcher({
      id: "locus.recovery",
      subject: "Locus",
      displayName: "Locus recovery",
      packageScript: "test:locus-recovery",
      repositoryModule: "tests/runtime-probes/locus-recovery.acceptance.mjs",
      runtime: "node",
      collections: ["recovery", "history", "snapshot"],
    }),
    launcher({
      id: "locus.client-recovery",
      subject: "Locus",
      displayName: "Locus client recovery",
      packageScript: "test:locus-client-recovery",
      repositoryModule: "tests/runtime-probes/locus-client-recovery.acceptance.mjs",
      runtime: "node-real-websocket",
      collections: ["client", "recovery", "protocol", "websocket"],
    }),
    launcher({
      id: "locus.document-recovery",
      subject: "Locus",
      displayName: "Locus document recovery",
      packageScript: "test:locus-document-recovery",
      repositoryModule: "tests/runtime-probes/locus-document-recovery.acceptance.mjs",
      runtime: "node",
      collections: ["document", "recovery", "snapshot"],
    }),
    launcher({
      id: "locus.document-actions",
      subject: "Locus",
      displayName: "Locus document actions",
      packageScript: "test:locus-document-actions",
      repositoryModule: "tests/runtime-probes/locus-document-actions.acceptance.mjs",
      runtime: "node",
      collections: ["document", "actions", "recovery"],
    }),
    launcher({
      id: "locus.protocol-document",
      subject: "Locus",
      displayName: "Locus document protocol",
      packageScript: "test:locus-protocol-document",
      repositoryModule: "tests/runtime-probes/locus-protocol-document.acceptance.mjs",
      runtime: "node",
      collections: ["document", "protocol", "validation"],
    }),
    launcher({
      id: "locus.document-request-compatibility",
      subject: "Locus",
      displayName: "Locus document request and legacy compatibility closure",
      packageScript: "test:locus-document-request-compatibility",
      repositoryModule: "tests/locus-document-request-compatibility.acceptance.mts",
      runtime: "node",
      collections: ["locus", "document", "quid", "path", "request-lowering", "history", "recovery", "persistence", "externally-discoverable"],
    }),
    launcher({
      id: "locus.session",
      subject: "Locus",
      displayName: "Locus session",
      packageScript: "test:locus-session",
      repositoryModule: "tests/runtime-probes/locus-session.acceptance.mjs",
      runtime: "node-real-websocket",
      collections: ["session", "recovery", "websocket"],
    }),
    launcher({
      id: "locus.action-dedupe",
      subject: "Locus",
      displayName: "Locus action deduplication",
      packageScript: "test:locus-action-dedupe",
      repositoryModule: "tests/runtime-probes/locus-action-dedupe.acceptance.mjs",
      runtime: "node-real-websocket-process",
      collections: ["actions", "deduplication", "identity", "websocket"],
    }),
    launcher({
      id: "locus.trace",
      subject: "Locus",
      displayName: "Locus tracing",
      packageScript: "test:locus-trace",
      repositoryModule: "tests/runtime-probes/locus-trace.acceptance.mjs",
      runtime: "node",
      collections: ["trace", "actions", "redaction"],
    }),
    launcher({
      id: "locus.authorization",
      subject: "Locus",
      displayName: "Locus action authorization",
      packageScript: "test:locus-authorization",
      repositoryModule: "tests/runtime-probes/locus-authorization.acceptance.mjs",
      runtime: "node",
      collections: ["actions", "authorization", "policy"],
    }),
    launcher({
      id: "livehost.node-hosting",
      subject: "LiveHost",
      displayName: "LiveHost Node hosting",
      packageScript: "test:livehost-node-hosting",
      repositoryModule: "tests/livehost-node-hosting.acceptance.mts",
      runtime: "node-real-websocket",
      collections: ["transport", "websocket", "node-host", "externally-discoverable"],
    }),
    launcher({
      id: "locus.bootstrap",
      subject: "Locus",
      displayName: "Locus HTTP Hson bootstrap",
      packageScript: "test:locus-bootstrap",
      repositoryModule: "tests/locus-bootstrap.acceptance.mts",
      runtime: "node-real-websocket",
      collections: ["bootstrap", "hson", "recovery", "http", "websocket", "externally-discoverable"],
    }),
    launcher({
      id: "transform.hson-structural-mode",
      subject: "Transform",
      displayName: "Hson canonical structural mode",
      packageScript: "test:hson-structural-mode",
      repositoryModule: "tests/hson-structural-mode.acceptance.mts",
      runtime: "node",
      collections: ["hson", "parsing", "canonical-graph", "structural-mode"],
    }),
    launcher({
      id: "hson-completion-context", subject: "Transform", displayName: "D6 authoritative cursor context",
      packageScript: "test:hson-completion-context", repositoryModule: "tests/hson-completion-context.acceptance.mts", runtime: "node", collections: ["hson", "authoring", "internal"],
    }),
    launcher({
      id: "transform.representation-sha-worker",
      subject: "Transform",
      displayName: "Representation SHA-256 actual Worker parity",
      packageScript: "test:representation-sha-worker",
      repositoryModule: "tests/representation-sha-worker.acceptance.mts",
      runtime: "node",
      collections: ["serialization", "sha256", "worker", "runtime-parity", "public-api", "externally-discoverable"],
    }),
    launcher({
      id: "transform.binary-hson-rejection",
      subject: "Transform",
      displayName: "Strict Binary Hson rejection and resource safety",
      packageScript: "test:binary-hson-rejection",
      repositoryModule: "tests/binary-hson-rejection.acceptance.mts",
      runtime: "node",
      collections: ["binary", "rejection", "resource-limits", "worker", "public-api", "externally-discoverable"],
    }),
    launcher({
      id: "transform.certified-authored-hson-corpus",
      subject: "Transform",
      displayName: "Certified authored-Hson corpus",
      packageScript: "test:certified-authored-hson-corpus",
      repositoryModule: "tests/certified-authored-hson-corpus.acceptance.mts",
      runtime: "node",
      collections: ["hson", "certified-corpus", "transport", "externally-discoverable"],
    }),
    launcher({
      id: "livetree-livemap.attrs-convergence",
      subject: "LiveTree",
      displayName: "LiveTree and LiveMap attrs/flags convergence",
      packageScript: "test:livetree-livemap-attrs-convergence",
      repositoryModule: "tests/livetree-livemap-attrs-convergence.acceptance.mts",
      runtime: "node",
      collections: ["attributes", "flags", "document", "canonical-graph", "externally-discoverable"],
    }),
    launcher({
      id: "reflect.document-same-quid-replacement-continuity",
      subject: "Reflect",
      displayName: "Document same-QUID replacement continuity",
      packageScript: "test:document-same-quid-replacement-continuity",
      repositoryModule: "tests/document-same-quid-replacement-continuity.acceptance.mts",
      runtime: "node-synthetic-dom",
      collections: ["document", "binding", "quid", "continuity", "replay", "lifecycle", "externally-discoverable"],
    }),
    launcher({
      id: "livemap.document",
      subject: "LiveMap",
      displayName: "Document LiveMap",
      packageScript: "test:livemap-document",
      repositoryModule: "tests/livemap-document.acceptance.mts",
      runtime: "node",
      collections: ["document", "construction", "identity"],
    }),
    launcher({
      id: "livemap.projected-rename-intent",
      subject: "LiveMap",
      displayName: "Data object rename intent",
      packageScript: "test:livemap-projected-rename-intent",
      repositoryModule: "tests/livemap-projected-rename-intent.acceptance.mts",
      runtime: "node",
      collections: ["projected-value", "object", "rename", "replay", "externally-discoverable"],
    }),
    launcher({
      id: "livemap.projected-array-move-intent",
      subject: "LiveMap",
      displayName: "Data array move intent",
      packageScript: "test:livemap-projected-array-move-intent",
      repositoryModule: "tests/livemap-projected-array-move-intent.acceptance.mts",
      runtime: "node",
      collections: ["projected-value", "array", "move", "replay", "externally-discoverable"],
    }),
    launcher({
      id: "livemap.projected-intent-propagation",
      subject: "LiveMap",
      displayName: "Projected rename and move propagation closure",
      packageScript: "test:livemap-projected-intent-propagation",
      repositoryModule: "tests/livemap-projected-intent-propagation.acceptance.mts",
      runtime: "node",
      collections: ["projected-value", "rename", "move", "feeds", "links", "stores", "locus", "externally-discoverable"],
    }),
    launcher({
      id: "livemap.projected-identity-lifecycle",
      subject: "LiveMap",
      displayName: "Active-epoch data identity handle lifecycle",
      packageScript: "test:livemap-projected-identity-lifecycle",
      repositoryModule: "tests/livemap-projected-identity-lifecycle.acceptance.mts",
      runtime: "node",
      collections: ["projected-value", "quid", "identity-handle", "lifecycle", "provenance", "externally-discoverable"],
    }),
    launcher({
      id: "livemap.issued-quid-ledger",
      subject: "LiveMap",
      displayName: "Same-epoch issued-QUID ledger invariants",
      packageScript: "test:livemap-issued-quid-ledger",
      repositoryModule: "tests/livemap-issued-quid-ledger.acceptance.mts",
      runtime: "node",
      collections: ["projected-value", "document", "quid", "identity-handle", "lifecycle", "externally-discoverable"],
    }),
    launcher({
      id: "livemap.identity-replay-provenance",
      subject: "LiveMap",
      displayName: "Identity replay and provenance ABA closure",
      packageScript: "test:livemap-identity-replay-provenance",
      repositoryModule: "tests/livemap-identity-replay-provenance.acceptance.mts",
      runtime: "node",
      collections: ["projected-value", "document", "quid", "identity-handle", "replay", "provenance", "externally-discoverable"],
    }),
    launcher({
      id: "livemap.document-id-discovery",
      subject: "LiveMap",
      displayName: "Internal canonical document ID discovery",
      packageScript: "test:livemap-document-id-discovery",
      repositoryModule: "tests/livemap-document-id-discovery.acceptance.mts",
      runtime: "node",
      collections: ["document", "path", "traversal", "discovery", "canonical-graph", "externally-discoverable"],
    }),
    launcher({
      id: "livemap.document-id-public",
      subject: "LiveMap",
      displayName: "Public canonical document ID discovery",
      packageScript: "test:livemap-document-id-public",
      repositoryModule: "tests/livemap-document-id-public.acceptance.mts",
      runtime: "node",
      collections: ["document", "path", "proxy", "discovery", "public-api", "externally-discoverable"],
    }),
    launcher({
      id: "livemap.document-target-boundary",
      subject: "LiveMap",
      displayName: "Document request and commit target boundary",
      packageScript: "test:livemap-document-target-boundary",
      repositoryModule: "tests/livemap-document-target-boundary.acceptance.mts",
      runtime: "node",
      collections: ["document", "path", "quid", "witness", "externally-discoverable"],
    }),
    launcher({
      id: "livemap.document-attrs-read",
      subject: "LiveMap",
      displayName: "Document LiveMap attribute reads",
      packageScript: "test:livemap-document-attrs-read",
      repositoryModule: "tests/livemap-document-attrs-read.acceptance.mts",
      runtime: "node",
      collections: ["document", "attributes", "reads"],
    }),
    launcher({
      id: "livemap.document-replay",
      subject: "LiveMap",
      displayName: "Document LiveMap observation and replay",
      packageScript: "test:livemap-document-replay",
      repositoryModule: "tests/livemap-document-replay.acceptance.mts",
      runtime: "node",
      collections: ["document", "observation", "replay"],
    }),
    launcher({
      id: "livemap.exact-route-closure",
      subject: "LiveMap",
      displayName: "LiveMap exact multi-route closure",
      packageScript: "test:livemap-exact-route-closure",
      repositoryModule: "tests/livemap-exact-route-closure.acceptance.mts",
      runtime: "node",
      collections: ["projected-value", "capture", "replay", "propagation", "closure", "externally-discoverable"],
    }),
    launcher({
      id: "livemap.deterministic-transport-propagation-operators",
      subject: "LiveMap",
      displayName: "Deterministic LiveMap transport and propagation operators",
      packageScript: "test:livemap-deterministic-transport-propagation-operators",
      repositoryModule: "tests/livemap-deterministic-transport-propagation-operators.acceptance.mts",
      runtime: "node",
      collections: ["projected-value", "operators", "capture", "replay", "propagation", "deterministic", "externally-discoverable"],
    }),
    launcher({
      id: "livehost.authority-lifecycle",
      subject: "LiveHost",
      displayName: "LiveHost Locus registry lifecycle",
      packageScript: "test:livehost-authority-lifecycle",
      repositoryModule: "tests/livehost-authority-lifecycle.acceptance.mts",
      runtime: "node",
      collections: ["locus-registry", "lifecycle", "eviction", "capacity", "restart", "externally-discoverable"],
    }),
  ]);

/**
 * Package test scripts intentionally outside the external launcher contract.
 * Every other test:* script must have exactly one hson_live_test_launchers entry.
 */
export const hson_live_non_launcher_test_scripts:
readonly HsonLiveNonLauncherTestScript[] = Object.freeze([
  Object.freeze({
    packageScript: "test:diagnostics-inventory",
    reason: "Validates the launcher manifest itself and would recurse if launched externally.",
  }),
  Object.freeze({
    packageScript: "test:hson-array-index",
    reason: "Command-only Transform integration journey; not an externally selectable launcher.",
  }),
  Object.freeze({
    packageScript: "test:hson-attribute-transport",
    reason: "Command-only Transform integration journey; not an externally selectable launcher.",
  }),
  Object.freeze({
    packageScript: "test:locus-graph-content-codec",
    reason: "Command-only Locus integration journey; not an externally selectable launcher.",
  }),
  Object.freeze({
    packageScript: "test:locus-public-contract",
    reason: "Built-package export certification; not an externally selectable semantic launcher.",
  }),
  Object.freeze({
    packageScript: "test:hson-authoring-package",
    reason: "Built-package tree-shaking certification using the editor bundler; not a semantic launcher.",
  }),
  Object.freeze({
    packageScript: "test:root-compatibility",
    reason: "Production artifact compatibility certification; not an external semantic launcher.",
  }),
  Object.freeze({
    packageScript: "test:transform-worker",
    reason: "Worker entrypoint integration journey; not an externally selectable launcher.",
  }),
  Object.freeze({
    packageScript: "test:typescript-observability",
    reason: "Repository observability inventory check; it emits no external launcher completion record.",
  }),
  Object.freeze({
    packageScript: "test:schema-editor-proof",
    reason: "Editor diagnostic proof command; it emits no external launcher completion record.",
  }),
  Object.freeze({
    packageScript: "test:public-entrypoint-runtime",
    reason: "Fresh-process built-package entrypoint check; it emits no external launcher completion record.",
  }),
  Object.freeze({
    packageScript: "test:production-dependency-boundary",
    reason: "Production dependency boundary check; it emits no external launcher completion record.",
  }),
  Object.freeze({
    packageScript: "test:hson-schema-document-consumer",
    reason: "Build-orchestrating Hson Schema document consumer check; it emits no external launcher completion record.",
  }),
  Object.freeze({
    packageScript: "test:hson-schema-consumer",
    reason: "Build-orchestrating Hson Schema consumer check; it emits no external launcher completion record.",
  }),
]);
