export type HsonLiveTestSubject =
  | "LiveHost"
  | "LiveMap"
  | "Reflect"
  | "LiveTree"
  | "Transform"
  | "Core";

export type HsonLiveTestRuntime =
  | "node"
  | "node-synthetic-dom"
  | "node-real-websocket"
  | "node-real-websocket-process";

/**
 * Every registered launcher must emit exactly one terminal completion record
 * whose executed count equals its manifested executableChecks value.
 */
export const HSON_LIVE_TEST_COMPLETION_REQUIREMENT =
  "exact-declared-check-count" as const;

export type HsonLiveTestLauncher = Readonly<{
  id: string;
  subject: HsonLiveTestSubject;
  displayName: string;
  packageScript: `test:${string}`;
  repositoryModule: `tests/${string}`;
  runtime: HsonLiveTestRuntime;
  executableChecks: number;
  collections: readonly string[];
}>;

export type HsonLiveNonLauncherTestScript = Readonly<{
  packageScript: `test:${string}`;
  reason: string;
}>;

function launcher(
  value: Omit<HsonLiveTestLauncher, "collections"> & {
    collections: readonly string[];
  },
): HsonLiveTestLauncher {
  return Object.freeze({
    ...value,
    collections: Object.freeze([...value.collections]),
  });
}

export const hson_live_test_launchers: readonly HsonLiveTestLauncher[] =
  Object.freeze([
    launcher({
      id: "core.hson-number",
      subject: "Core",
      displayName: "HSON numeric admission",
      packageScript: "test:hson-number",
      repositoryModule: "tests/hson-number.acceptance.mts",
      runtime: "node",
      executableChecks: 24,
      collections: ["hson", "number", "admission", "public-api", "externally-discoverable"],
    }),
    launcher({
      id: "transform.hson-tokenizer",
      subject: "Transform",
      displayName: "HSON tokenizer",
      packageScript: "test:hson-tokenizer",
      repositoryModule: "tests/hson-tokenizer.acceptance.mts",
      runtime: "node",
      executableChecks: 139,
      collections: ["hson", "tokenization", "parsing"],
    }),
    launcher({
      id: "transform.hson-tagged-template",
      subject: "Transform",
      displayName: "HSON tagged-template admission",
      packageScript: "test:hson-tagged-template",
      repositoryModule: "tests/hson-tagged-template.acceptance.mts",
      runtime: "node",
      executableChecks: 16,
      collections: ["hson", "admission", "tagged-template", "public-api", "diagnostics", "externally-discoverable"],
    }),
    launcher({
      id: "transform.hson-quoted-name-acceptance",
      subject: "Transform",
      displayName: "HSON single-quoted name acceptance and canonicalization",
      packageScript: "test:hson-quoted-name-acceptance",
      repositoryModule: "tests/hson-quoted-name-acceptance.acceptance.mts",
      runtime: "node",
      executableChecks: 24,
      collections: ["hson", "quoted-name", "parsing", "serialization", "round-trip", "externally-discoverable"],
    }),
    launcher({
      id: "transform.hson-quoted-name-rejection",
      subject: "Transform",
      displayName: "HSON quoted-name rejection and legacy syntax",
      packageScript: "test:hson-quoted-name-rejection",
      repositoryModule: "tests/hson-quoted-name-rejection.acceptance.mts",
      runtime: "node",
      executableChecks: 25,
      collections: ["hson", "quoted-name", "rejection", "diagnostics", "externally-discoverable"],
    }),
    launcher({
      id: "transform.hson-structural-mode",
      subject: "Transform",
      displayName: "HSON canonical structural mode",
      packageScript: "test:hson-structural-mode",
      repositoryModule: "tests/hson-structural-mode.acceptance.mts",
      runtime: "node",
      executableChecks: 44,
      collections: ["hson", "parsing", "canonical-graph", "structural-mode"],
    }),
    launcher({
      id: "transform.hson-root-boundary",
      subject: "Transform",
      displayName: "HSON root detachment and source shaping",
      packageScript: "test:hson-root-boundary",
      repositoryModule: "tests/hson-root-boundary.acceptance.mts",
      runtime: "node",
      executableChecks: 79,
      collections: ["hson", "parsing", "root-boundary", "source-shaping"],
    }),
    launcher({
      id: "transform.hson-serializer",
      subject: "Transform",
      displayName: "HSON serializer",
      packageScript: "test:hson-serializer",
      repositoryModule: "tests/hson-serializer.acceptance.mts",
      runtime: "node",
      executableChecks: 109,
      collections: ["hson", "serialization", "round-trip"],
    }),
    launcher({
      id: "transform.json-ingress",
      subject: "Transform",
      displayName: "Detached JSON ingress and root metadata",
      packageScript: "test:json-ingress",
      repositoryModule: "tests/json-ingress.acceptance.mts",
      runtime: "node",
      executableChecks: 31,
      collections: ["json", "ingress", "canonical-graph", "externally-discoverable"],
    }),
    launcher({
      id: "core.hson-node-quid",
      subject: "Transform",
      displayName: "Canonical HsonNode QUID primitives",
      packageScript: "test:hson-node-quid",
      repositoryModule: "tests/hson-node-quid.acceptance.mts",
      runtime: "node",
      executableChecks: 14,
      collections: ["quid", "canonical-graph", "externally-discoverable"],
    }),
    launcher({
      id: "transform.hson-node-quid-ingress",
      subject: "Transform",
      displayName: "Canonical HsonNode QUID ingress",
      packageScript: "test:hson-node-quid-ingress",
      repositoryModule: "tests/hson-node-quid-ingress.acceptance.mts",
      runtime: "node-synthetic-dom",
      executableChecks: 33,
      collections: ["quid", "ingress", "externally-discoverable"],
    }),
    launcher({
      id: "transform.hson-node-quid-egress",
      subject: "Transform",
      displayName: "Canonical HsonNode QUID egress",
      packageScript: "test:hson-node-quid-egress",
      repositoryModule: "tests/hson-node-quid-egress.acceptance.mts",
      runtime: "node-synthetic-dom",
      executableChecks: 13,
      collections: ["quid", "egress", "serialization", "externally-discoverable"],
    }),
    launcher({
      id: "core.canonical-hson-equality",
      subject: "Core",
      displayName: "Canonical HSON equality",
      packageScript: "test:canonical-hson-equality",
      repositoryModule: "tests/canonical-hson-equality.acceptance.mts",
      runtime: "node",
      executableChecks: 16,
      collections: ["canonical-graph", "equality"],
    }),
    launcher({
      id: "transform.canonical-oracle",
      subject: "Transform",
      displayName: "Canonical Transform oracle and deterministic witnesses",
      packageScript: "test:transform-oracle",
      repositoryModule: "tests/transform-oracle.acceptance.mts",
      runtime: "node",
      executableChecks: 27,
      collections: ["canonical-graph", "oracle", "deterministic-witness"],
    }),
    launcher({
      id: "diagnostics.circuit-semantic-engine",
      subject: "Transform",
      displayName: "Circuit semantic engine",
      packageScript: "test:circuit-semantic-engine",
      repositoryModule: "tests/circuit-semantic-engine.acceptance.mts",
      runtime: "node",
      executableChecks: 25,
      collections: ["diagnostics", "circuit", "canonical-graph", "strict-comparison"],
    }),
    launcher({
      id: "diagnostics.circuit-failure-control",
      subject: "Transform",
      displayName: "Circuit failure and execution control",
      packageScript: "test:circuit-failure-control",
      repositoryModule: "tests/circuit-failure-control.acceptance.mts",
      runtime: "node",
      executableChecks: 25,
      collections: ["diagnostics", "circuit", "failure-propagation", "operation-accounting"],
    }),
    launcher({
      id: "diagnostics.circuit-legacy-wrapper",
      subject: "Transform",
      displayName: "Circuit legacy wrapper compatibility",
      packageScript: "test:circuit-legacy-wrapper",
      repositoryModule: "tests/circuit-legacy-wrapper.acceptance.mts",
      runtime: "node-synthetic-dom",
      executableChecks: 25,
      collections: ["diagnostics", "circuit", "browser-html", "compatibility"],
    }),
    launcher({
      id: "diagnostics.universal-circuit-verification",
      subject: "Transform",
      displayName: "Universal circuit verification facade",
      packageScript: "test:universal-circuit-verification",
      repositoryModule: "tests/universal-circuit-verification.acceptance.mts",
      runtime: "node",
      executableChecks: 22,
      collections: ["diagnostics", "circuit", "universal", "worker", "externally-discoverable"],
    }),
    launcher({
      id: "transform.certified-authored-hson-corpus",
      subject: "Transform",
      displayName: "Certified authored-HSON corpus",
      packageScript: "test:certified-authored-hson-corpus",
      repositoryModule: "tests/certified-authored-hson-corpus.acceptance.mts",
      runtime: "node",
      executableChecks: 29,
      collections: ["hson", "certified-corpus", "transport", "externally-discoverable"],
    }),
    launcher({
      id: "livemap.view-state-snapshot-codec",
      subject: "LiveMap",
      displayName: "View-state snapshot codec",
      packageScript: "test:view-state-snapshot-codec",
      repositoryModule: "tests/view-state-snapshot-codec.acceptance.mts",
      runtime: "node",
      executableChecks: 24,
      collections: ["document", "snapshot", "codec"],
    }),
    launcher({
      id: "core.public-boundaries",
      subject: "Core",
      displayName: "Public package boundaries",
      packageScript: "test:public-boundaries",
      repositoryModule: "tests/public-boundaries.acceptance.mts",
      runtime: "node",
      executableChecks: 6,
      collections: ["public-api", "LiveMap", "LiveTree", "Transform"],
    }),
    launcher({
      id: "livetree.attrs",
      subject: "LiveTree",
      displayName: "LiveTree canonical attributes",
      packageScript: "test:livetree-attrs",
      repositoryModule: "tests/livetree-attrs.acceptance.mts",
      runtime: "node-synthetic-dom",
      executableChecks: 12,
      collections: ["attributes", "style", "dom-projection"],
    }),
    launcher({
      id: "livetree.quid-eligibility",
      subject: "LiveTree",
      displayName: "LiveTree QUID eligibility",
      packageScript: "test:livetree-quid-eligibility",
      repositoryModule: "tests/livetree-quid-eligibility.acceptance.mts",
      runtime: "node",
      executableChecks: 6,
      collections: ["quid", "eligibility", "identity", "externally-discoverable"],
    }),
    launcher({
      id: "livetree.runtime-scope",
      subject: "LiveTree",
      displayName: "LiveTree runtime scope isolation",
      packageScript: "test:livetree-runtime-scope",
      repositoryModule: "tests/livetree-runtime-scope.acceptance.mts",
      runtime: "node-synthetic-dom",
      executableChecks: 24,
      collections: ["quid", "runtime", "lifecycle", "css", "Reflect", "externally-discoverable"],
    }),
    launcher({
      id: "reflect.document-attrs",
      subject: "Reflect",
      displayName: "Document Reflect attributes",
      packageScript: "test:reflect-document-attrs",
      repositoryModule: "tests/reflect-document-attrs.acceptance.mts",
      runtime: "node-synthetic-dom",
      executableChecks: 10,
      collections: ["document", "binding", "attributes"],
    }),
    launcher({
      id: "reflect.document-structure",
      subject: "Reflect",
      displayName: "Document Reflect structure",
      packageScript: "test:reflect-document-structure",
      repositoryModule: "tests/reflect-document-structure.acceptance.mts",
      runtime: "node-synthetic-dom",
      executableChecks: 11,
      collections: ["document", "binding", "structure"],
    }),
    launcher({
      id: "reflect.document-delegation",
      subject: "Reflect",
      displayName: "Document Reflect mutation delegation",
      packageScript: "test:reflect-document-delegation",
      repositoryModule: "tests/reflect-document-delegation.acceptance.mts",
      runtime: "node-synthetic-dom",
      executableChecks: 8,
      collections: ["document", "binding", "delegation"],
    }),
    launcher({
      id: "reflect.document-root",
      subject: "Reflect",
      displayName: "Document Reflect root update",
      packageScript: "test:reflect-document-root",
      repositoryModule: "tests/reflect-document-root.acceptance.mts",
      runtime: "node-synthetic-dom",
      executableChecks: 8,
      collections: ["document", "binding", "root"],
    }),
    launcher({
      id: "reflect.document-snapshot",
      subject: "Reflect",
      displayName: "Document Reflect snapshot update",
      packageScript: "test:reflect-document-snapshot",
      repositoryModule: "tests/reflect-document-snapshot.acceptance.mts",
      runtime: "node-synthetic-dom",
      executableChecks: 9,
      collections: ["document", "binding", "snapshot"],
    }),
    launcher({
      id: "reflect.document-path-authority",
      subject: "Reflect",
      displayName: "Document Reflect path authority",
      packageScript: "test:reflect-document-path-authority",
      repositoryModule: "tests/reflect-document-path-authority.acceptance.mts",
      runtime: "node-synthetic-dom",
      executableChecks: 21,
      collections: ["document", "binding", "path", "identity", "externally-discoverable"],
    }),
    launcher({
      id: "reflect.document-continuity",
      subject: "Reflect",
      displayName: "Document Reflect continuity",
      packageScript: "test:reflect-document-continuity",
      repositoryModule: "tests/reflect-document-continuity.acceptance.mts",
      runtime: "node-synthetic-dom",
      executableChecks: 20,
      collections: ["document", "binding", "continuity", "lifecycle", "externally-discoverable"],
    }),
    launcher({
      id: "reflect.document-correspondence",
      subject: "Reflect",
      displayName: "Document Reflect correspondence",
      packageScript: "test:reflect-document-correspondence",
      repositoryModule: "tests/reflect-document-correspondence.acceptance.mts",
      runtime: "node-synthetic-dom",
      executableChecks: 21,
      collections: ["document", "binding", "correspondence", "failure", "externally-discoverable"],
    }),
    launcher({
      id: "reflect.linked-no-mint-projection",
      subject: "Reflect",
      displayName: "Document Reflect linked no-mint projection",
      packageScript: "test:reflect-linked-no-mint-projection",
      repositoryModule: "tests/reflect-linked-no-mint-projection.acceptance.mts",
      runtime: "node-synthetic-dom",
      executableChecks: 20,
      collections: ["document", "binding", "quid", "runtime", "externally-discoverable"],
    }),
    launcher({
      id: "reflect.supplied-identity-preservation",
      subject: "Reflect",
      displayName: "Document Reflect supplied identity preservation",
      packageScript: "test:reflect-supplied-identity-preservation",
      repositoryModule: "tests/reflect-supplied-identity-preservation.acceptance.mts",
      runtime: "node-synthetic-dom",
      executableChecks: 20,
      collections: ["document", "binding", "quid", "runtime", "externally-discoverable"],
    }),
    launcher({
      id: "reflect.no-mint-regression-boundaries",
      subject: "Reflect",
      displayName: "Document Reflect no-mint regression boundaries",
      packageScript: "test:reflect-no-mint-regression-boundaries",
      repositoryModule: "tests/reflect-no-mint-regression-boundaries.acceptance.mts",
      runtime: "node-synthetic-dom",
      executableChecks: 20,
      collections: ["document", "binding", "quid", "runtime", "provenance", "externally-discoverable"],
    }),
    launcher({
      id: "livemap.linked-identity-registration",
      subject: "LiveMap",
      displayName: "Linked identity authority registration",
      packageScript: "test:livemap-linked-identity-registration",
      repositoryModule: "tests/livemap-linked-identity-registration.acceptance.mts",
      runtime: "node-synthetic-dom",
      executableChecks: 20,
      collections: ["document", "binding", "quid", "runtime", "authority", "externally-discoverable"],
    }),
    launcher({
      id: "livemap.linked-identity-atomicity",
      subject: "LiveMap",
      displayName: "Linked identity preflight and atomicity",
      packageScript: "test:livemap-linked-identity-atomicity",
      repositoryModule: "tests/livemap-linked-identity-atomicity.acceptance.mts",
      runtime: "node-synthetic-dom",
      executableChecks: 20,
      collections: ["document", "binding", "quid", "runtime", "atomicity", "externally-discoverable"],
    }),
    launcher({
      id: "livemap.linked-identity-closure",
      subject: "LiveMap",
      displayName: "Linked identity replay and resource closure",
      packageScript: "test:livemap-linked-identity-closure",
      repositoryModule: "tests/livemap-linked-identity-closure.acceptance.mts",
      runtime: "node-synthetic-dom",
      executableChecks: 22,
      collections: ["document", "binding", "quid", "runtime", "livehost", "externally-discoverable"],
    }),
    launcher({
      id: "livemap.document",
      subject: "LiveMap",
      displayName: "Document LiveMap",
      packageScript: "test:livemap-document",
      repositoryModule: "tests/livemap-document.acceptance.mts",
      runtime: "node",
      executableChecks: 14,
      collections: ["document", "construction", "identity"],
    }),
    launcher({
      id: "livemap.quid-canonical-state",
      subject: "LiveMap",
      displayName: "LiveMap QUID canonical-state contract",
      packageScript: "test:livemap-quid-canonical-state",
      repositoryModule: "tests/livemap-quid-canonical-state.acceptance.mts",
      runtime: "node",
      executableChecks: 22,
      collections: ["document", "quid", "canonical-graph", "revision", "externally-discoverable"],
    }),
    launcher({
      id: "livemap.quid-non-minting",
      subject: "LiveMap",
      displayName: "LiveMap sparse QUID non-minting contract",
      packageScript: "test:livemap-quid-non-minting",
      repositoryModule: "tests/livemap-quid-non-minting.acceptance.mts",
      runtime: "node",
      executableChecks: 24,
      collections: ["document", "quid", "sparse-identity", "non-minting", "externally-discoverable"],
    }),
    launcher({
      id: "livemap.capture-categories",
      subject: "LiveMap",
      displayName: "Document capture identity categories",
      packageScript: "test:livemap-capture-categories",
      repositoryModule: "tests/livemap-capture-categories.acceptance.mts",
      runtime: "node",
      executableChecks: 22,
      collections: ["document", "quid", "capture", "admission", "externally-discoverable"],
    }),
    launcher({
      id: "livemap.capture-provenance",
      subject: "LiveMap",
      displayName: "Document capture epoch provenance",
      packageScript: "test:livemap-capture-provenance",
      repositoryModule: "tests/livemap-capture-provenance.acceptance.mts",
      runtime: "node",
      executableChecks: 23,
      collections: ["document", "quid", "capture", "provenance", "atomicity", "externally-discoverable"],
    }),
    launcher({
      id: "livehost.capture-identity-closure",
      subject: "LiveHost",
      displayName: "LiveHost and Reflection capture identity closure",
      packageScript: "test:livehost-capture-identity-closure",
      repositoryModule: "tests/livehost-capture-identity-closure.acceptance.mts",
      runtime: "node-synthetic-dom",
      executableChecks: 23,
      collections: ["document", "quid", "capture", "livehost", "reflection", "externally-discoverable"],
    }),
    launcher({
      id: "livemap.projected-rename-intent",
      subject: "LiveMap",
      displayName: "Projected object rename intent",
      packageScript: "test:livemap-projected-rename-intent",
      repositoryModule: "tests/livemap-projected-rename-intent.acceptance.mts",
      runtime: "node",
      executableChecks: 22,
      collections: ["projected-value", "object", "rename", "replay", "externally-discoverable"],
    }),
    launcher({
      id: "livemap.projected-array-move-intent",
      subject: "LiveMap",
      displayName: "Projected array move intent",
      packageScript: "test:livemap-projected-array-move-intent",
      repositoryModule: "tests/livemap-projected-array-move-intent.acceptance.mts",
      runtime: "node",
      executableChecks: 24,
      collections: ["projected-value", "array", "move", "replay", "externally-discoverable"],
    }),
    launcher({
      id: "livemap.projected-intent-propagation",
      subject: "LiveMap",
      displayName: "Projected rename and move propagation closure",
      packageScript: "test:livemap-projected-intent-propagation",
      repositoryModule: "tests/livemap-projected-intent-propagation.acceptance.mts",
      runtime: "node",
      executableChecks: 24,
      collections: ["projected-value", "rename", "move", "feeds", "links", "stores", "livehost", "externally-discoverable"],
    }),
    launcher({
      id: "livemap.document-identity-overlay-construction",
      subject: "LiveMap",
      displayName: "Sparse document identity overlay construction",
      packageScript: "test:livemap-document-identity-overlay-construction",
      repositoryModule: "tests/livemap-document-identity-overlay-construction.acceptance.mts",
      runtime: "node",
      executableChecks: 22,
      collections: ["document", "quid", "path", "sparse-identity", "construction", "externally-discoverable"],
    }),
    launcher({
      id: "livemap.document-identity-overlay-lookup",
      subject: "LiveMap",
      displayName: "Document identity overlay lookup and agreement",
      packageScript: "test:livemap-document-identity-overlay-lookup",
      repositoryModule: "tests/livemap-document-identity-overlay-lookup.acceptance.mts",
      runtime: "node",
      executableChecks: 22,
      collections: ["document", "quid", "path", "lookup", "invariants", "externally-discoverable"],
    }),
    launcher({
      id: "livemap.document-identity-overlay-lifecycle",
      subject: "LiveMap",
      displayName: "Document identity overlay lifecycle and atomic installation",
      packageScript: "test:livemap-document-identity-overlay-lifecycle",
      repositoryModule: "tests/livemap-document-identity-overlay-lifecycle.acceptance.mts",
      runtime: "node",
      executableChecks: 22,
      collections: ["document", "quid", "path", "lifecycle", "atomicity", "externally-discoverable"],
    }),
    launcher({
      id: "livemap.document-operation-identity-effects",
      subject: "LiveMap",
      displayName: "Document operation-derived identity effects",
      packageScript: "test:livemap-document-operation-identity-effects",
      repositoryModule: "tests/livemap-document-operation-identity-effects.acceptance.mts",
      runtime: "node",
      executableChecks: 22,
      collections: ["document", "quid", "path", "identity-effects", "reconciliation", "externally-discoverable"],
    }),
    launcher({
      id: "livemap.document-atomic-reconciliation",
      subject: "LiveMap",
      displayName: "Atomic document identity reconciliation",
      packageScript: "test:livemap-document-atomic-reconciliation",
      repositoryModule: "tests/livemap-document-atomic-reconciliation.acceptance.mts",
      runtime: "node",
      executableChecks: 23,
      collections: ["document", "quid", "path", "atomicity", "rollback", "externally-discoverable"],
    }),
    launcher({
      id: "livemap.document-staged-reconciliation",
      subject: "LiveMap",
      displayName: "Staged document identity reconciliation",
      packageScript: "test:livemap-document-staged-reconciliation",
      repositoryModule: "tests/livemap-document-staged-reconciliation.acceptance.mts",
      runtime: "node",
      executableChecks: 23,
      collections: ["document", "quid", "path", "staging", "replay", "reconciliation", "externally-discoverable"],
    }),
    launcher({
      id: "livemap.document-request-lowering",
      subject: "LiveMap",
      displayName: "Document QUID-request lowering boundary",
      packageScript: "test:livemap-document-request-lowering",
      repositoryModule: "tests/livemap-document-request-lowering.acceptance.mts",
      runtime: "node",
      executableChecks: 23,
      collections: ["document", "quid", "path", "request-lowering", "canonical-target", "externally-discoverable"],
    }),
    launcher({
      id: "livemap.document-staged-request-lowering",
      subject: "LiveMap",
      displayName: "Staged document QUID-request lowering",
      packageScript: "test:livemap-document-staged-request-lowering",
      repositoryModule: "tests/livemap-document-staged-request-lowering.acceptance.mts",
      runtime: "node",
      executableChecks: 24,
      collections: ["document", "quid", "path", "request-lowering", "staging", "atomicity", "externally-discoverable"],
    }),
    launcher({
      id: "livemap.document-path-contract",
      subject: "LiveMap",
      displayName: "Canonical document-path contract",
      packageScript: "test:livemap-document-path-contract",
      repositoryModule: "tests/livemap-document-path-contract.acceptance.mts",
      runtime: "node",
      executableChecks: 25,
      collections: ["document", "path", "canonical-graph", "externally-discoverable"],
    }),
    launcher({
      id: "livemap.document-staging",
      subject: "LiveMap",
      displayName: "Staged canonical document operations",
      packageScript: "test:livemap-document-staging",
      repositoryModule: "tests/livemap-document-staging.acceptance.mts",
      runtime: "node",
      executableChecks: 23,
      collections: ["document", "path", "staging", "replay", "externally-discoverable"],
    }),
    launcher({
      id: "livemap.document-target-boundary",
      subject: "LiveMap",
      displayName: "Document request and commit target boundary",
      packageScript: "test:livemap-document-target-boundary",
      repositoryModule: "tests/livemap-document-target-boundary.acceptance.mts",
      runtime: "node",
      executableChecks: 22,
      collections: ["document", "path", "quid", "witness", "externally-discoverable"],
    }),
    launcher({
      id: "livemap.document-install",
      subject: "LiveMap",
      displayName: "Document LiveMap installation",
      packageScript: "test:livemap-document-install",
      repositoryModule: "tests/livemap-document-install.acceptance.mts",
      runtime: "node",
      executableChecks: 11,
      collections: ["document", "installation", "identity"],
    }),
    launcher({
      id: "livemap.document-mutation",
      subject: "LiveMap",
      displayName: "Document LiveMap mutation",
      packageScript: "test:livemap-document-mutation",
      repositoryModule: "tests/livemap-document-mutation.acceptance.mts",
      runtime: "node",
      executableChecks: 21,
      collections: ["document", "mutation", "attributes", "content"],
    }),
    launcher({
      id: "livemap.document-attrs-read",
      subject: "LiveMap",
      displayName: "Document LiveMap attribute reads",
      packageScript: "test:livemap-document-attrs-read",
      repositoryModule: "tests/livemap-document-attrs-read.acceptance.mts",
      runtime: "node",
      executableChecks: 8,
      collections: ["document", "attributes", "reads"],
    }),
    launcher({
      id: "livemap.document-replay",
      subject: "LiveMap",
      displayName: "Document LiveMap observation and replay",
      packageScript: "test:livemap-document-replay",
      repositoryModule: "tests/livemap-document-replay.acceptance.mts",
      runtime: "node",
      executableChecks: 16,
      collections: ["document", "observation", "replay"],
    }),
    launcher({
      id: "livemap.path-handle",
      subject: "LiveMap",
      displayName: "LiveMap path handles",
      packageScript: "test:livemap-path-handle",
      repositoryModule: "tests/livemap-path-handle.acceptance.mts",
      runtime: "node",
      executableChecks: 10,
      collections: ["path-handle", "proxy", "bridge", "externally-discoverable"],
    }),
    launcher({
      id: "livemap.staged-authority",
      subject: "LiveMap",
      displayName: "Staged LiveMap authority",
      packageScript: "test:livemap-staged-authority",
      repositoryModule: "tests/livemap-staged-authority.acceptance.mts",
      runtime: "node",
      executableChecks: 13,
      collections: ["authority", "lifecycle", "commit"],
    }),
    launcher({
      id: "livemap.projected-value-equivalence",
      subject: "LiveMap",
      displayName: "LiveMap ordered projected-value equivalence",
      packageScript: "test:livemap-projected-value-equivalence",
      repositoryModule: "tests/livemap-projected-value-equivalence.acceptance.mts",
      runtime: "node",
      executableChecks: 25,
      collections: ["projected-value", "canonical-graph", "equivalence", "externally-discoverable"],
    }),
    launcher({
      id: "livemap.carrier-mutation-planning",
      subject: "LiveMap",
      displayName: "LiveMap carrier mutation planning",
      packageScript: "test:livemap-carrier-mutation-planning",
      repositoryModule: "tests/livemap-carrier-planning.acceptance.mts",
      runtime: "node",
      executableChecks: 25,
      collections: ["projected-value", "mutation", "commit", "canonical-graph", "externally-discoverable"],
    }),
    launcher({
      id: "livemap.exact-transport",
      subject: "LiveMap",
      displayName: "LiveMap exact capture and replay transport",
      packageScript: "test:livemap-exact-transport",
      repositoryModule: "tests/livemap-exact-transport.acceptance.mts",
      runtime: "node",
      executableChecks: 25,
      collections: ["projected-value", "capture", "replay", "transport", "externally-discoverable"],
    }),
    launcher({
      id: "livemap.exact-transport-rejection",
      subject: "LiveMap",
      displayName: "LiveMap exact transport compatibility and rejection",
      packageScript: "test:livemap-exact-transport-rejection",
      repositoryModule: "tests/livemap-exact-transport-rejection.acceptance.mts",
      runtime: "node",
      executableChecks: 13,
      collections: ["projected-value", "capture", "replay", "compatibility", "rejection", "externally-discoverable"],
    }),
    launcher({
      id: "livemap.exact-propagation",
      subject: "LiveMap",
      displayName: "LiveMap exact carrier propagation",
      packageScript: "test:livemap-exact-propagation",
      repositoryModule: "tests/livemap-exact-propagation.acceptance.mts",
      runtime: "node",
      executableChecks: 25,
      collections: ["projected-value", "feed", "link", "store", "livehost", "externally-discoverable"],
    }),
    launcher({
      id: "livemap.schema-value-boundary",
      subject: "LiveMap",
      displayName: "LiveMap schema value boundary",
      packageScript: "test:livemap-schema-value-boundary",
      repositoryModule: "tests/livemap-schema-value-boundary.acceptance.mts",
      runtime: "node",
      executableChecks: 25,
      collections: ["projected-value", "schema", "admission", "externally-discoverable"],
    }),
    launcher({
      id: "livemap.transform-accepted-closure",
      subject: "LiveMap",
      displayName: "Transform–LiveMap accepted-value closure",
      packageScript: "test:livemap-transform-accepted-closure",
      repositoryModule: "tests/livemap-transform-accepted-closure.acceptance.mts",
      runtime: "node",
      executableChecks: 24,
      collections: ["projected-value", "equivalence", "canonical-graph", "closure", "externally-discoverable"],
    }),
    launcher({
      id: "livemap.rejection-closure",
      subject: "LiveMap",
      displayName: "LiveMap projected-value rejection closure",
      packageScript: "test:livemap-rejection-closure",
      repositoryModule: "tests/livemap-rejection-closure.acceptance.mts",
      runtime: "node",
      executableChecks: 24,
      collections: ["projected-value", "rejection", "atomicity", "closure", "externally-discoverable"],
    }),
    launcher({
      id: "livemap.exact-route-closure",
      subject: "LiveMap",
      displayName: "LiveMap exact multi-route closure",
      packageScript: "test:livemap-exact-route-closure",
      repositoryModule: "tests/livemap-exact-route-closure.acceptance.mts",
      runtime: "node",
      executableChecks: 25,
      collections: ["projected-value", "capture", "replay", "propagation", "closure", "externally-discoverable"],
    }),
    launcher({
      id: "livemap.deterministic-mutation-operators",
      subject: "LiveMap",
      displayName: "Deterministic LiveMap mutation operators",
      packageScript: "test:livemap-deterministic-mutation-operators",
      repositoryModule: "tests/livemap-deterministic-mutation-operators.acceptance.mts",
      runtime: "node",
      executableChecks: 20,
      collections: ["projected-value", "operators", "mutation", "deterministic", "externally-discoverable"],
    }),
    launcher({
      id: "livemap.deterministic-admission-schema-operators",
      subject: "LiveMap",
      displayName: "Deterministic LiveMap admission and schema operators",
      packageScript: "test:livemap-deterministic-admission-schema-operators",
      repositoryModule: "tests/livemap-deterministic-admission-schema-operators.acceptance.mts",
      runtime: "node",
      executableChecks: 20,
      collections: ["projected-value", "operators", "admission", "schema", "deterministic", "externally-discoverable"],
    }),
    launcher({
      id: "livemap.deterministic-transport-propagation-operators",
      subject: "LiveMap",
      displayName: "Deterministic LiveMap transport and propagation operators",
      packageScript: "test:livemap-deterministic-transport-propagation-operators",
      repositoryModule: "tests/livemap-deterministic-transport-propagation-operators.acceptance.mts",
      runtime: "node",
      executableChecks: 20,
      collections: ["projected-value", "operators", "capture", "replay", "propagation", "deterministic", "externally-discoverable"],
    }),
    launcher({
      id: "core.projected-value-admission",
      subject: "LiveMap",
      displayName: "Projected-value admission and materialization",
      packageScript: "test:projected-value-admission",
      repositoryModule: "tests/projected-value-admission.acceptance.mts",
      runtime: "node",
      executableChecks: 25,
      collections: ["projected-value", "admission", "materialization", "externally-discoverable"],
    }),
    launcher({
      id: "core.projected-value-equality",
      subject: "LiveMap",
      displayName: "Ordered projected-value equality",
      packageScript: "test:projected-value-equality",
      repositoryModule: "tests/projected-value-equality.acceptance.mts",
      runtime: "node",
      executableChecks: 24,
      collections: ["projected-value", "equality", "same-value", "externally-discoverable"],
    }),
    launcher({
      id: "livehost.authority",
      subject: "LiveHost",
      displayName: "Exclusive LiveHost authority",
      packageScript: "test:livehost-authority",
      repositoryModule: "tests/runtime-probes/livehost-authority.acceptance.mjs",
      runtime: "node",
      executableChecks: 19,
      collections: ["authority", "lifecycle", "commit"],
    }),
    launcher({
      id: "livehost.persistence",
      subject: "LiveHost",
      displayName: "Persistent LiveHost",
      packageScript: "test:livehost-persistence",
      repositoryModule: "tests/runtime-probes/livehost-persistence.acceptance.mjs",
      runtime: "node",
      executableChecks: 16,
      collections: ["persistence", "authority", "recovery"],
    }),
    launcher({
      id: "livehost.recovery",
      subject: "LiveHost",
      displayName: "LiveHost recovery",
      packageScript: "test:livehost-recovery",
      repositoryModule: "tests/runtime-probes/livehost-recovery.acceptance.mjs",
      runtime: "node",
      executableChecks: 11,
      collections: ["recovery", "history", "snapshot"],
    }),
    launcher({
      id: "livehost.client-recovery",
      subject: "LiveHost",
      displayName: "LiveHost client recovery",
      packageScript: "test:livehost-client-recovery",
      repositoryModule: "tests/runtime-probes/livehost-client-recovery.acceptance.mjs",
      runtime: "node-real-websocket",
      executableChecks: 28,
      collections: ["client", "recovery", "protocol", "websocket"],
    }),
    launcher({
      id: "livehost.document-recovery",
      subject: "LiveHost",
      displayName: "LiveHost document recovery",
      packageScript: "test:livehost-document-recovery",
      repositoryModule: "tests/runtime-probes/livehost-document-recovery.acceptance.mjs",
      runtime: "node",
      executableChecks: 28,
      collections: ["document", "recovery", "snapshot"],
    }),
    launcher({
      id: "livehost.document-actions",
      subject: "LiveHost",
      displayName: "Hosted document actions",
      packageScript: "test:livehost-document-actions",
      repositoryModule: "tests/runtime-probes/livehost-document-actions.acceptance.mjs",
      runtime: "node",
      executableChecks: 28,
      collections: ["document", "actions", "recovery"],
    }),
    launcher({
      id: "livehost.protocol-document",
      subject: "LiveHost",
      displayName: "LiveHost document protocol",
      packageScript: "test:livehost-protocol-document",
      repositoryModule: "tests/runtime-probes/livehost-protocol-document.acceptance.mjs",
      runtime: "node",
      executableChecks: 8,
      collections: ["document", "protocol", "validation"],
    }),
    launcher({
      id: "livehost.document-request-compatibility",
      subject: "LiveHost",
      displayName: "LiveHost document request and legacy compatibility closure",
      packageScript: "test:livehost-document-request-compatibility",
      repositoryModule: "tests/livehost-document-request-compatibility.acceptance.mts",
      runtime: "node",
      executableChecks: 24,
      collections: ["livehost", "document", "quid", "path", "request-lowering", "history", "recovery", "persistence", "externally-discoverable"],
    }),
    launcher({
      id: "livehost.session",
      subject: "LiveHost",
      displayName: "LiveHost session",
      packageScript: "test:livehost-session",
      repositoryModule: "tests/runtime-probes/livehost-session.acceptance.mjs",
      runtime: "node-real-websocket",
      executableChecks: 15,
      collections: ["session", "recovery", "websocket"],
    }),
    launcher({
      id: "livehost.action-dedupe",
      subject: "LiveHost",
      displayName: "LiveHost action deduplication",
      packageScript: "test:livehost-action-dedupe",
      repositoryModule: "tests/runtime-probes/livehost-action-dedupe.acceptance.mjs",
      runtime: "node-real-websocket-process",
      executableChecks: 21,
      collections: ["actions", "deduplication", "identity", "websocket"],
    }),
    launcher({
      id: "livehost.trace",
      subject: "LiveHost",
      displayName: "LiveHost tracing",
      packageScript: "test:livehost-trace",
      repositoryModule: "tests/runtime-probes/livehost-trace.acceptance.mjs",
      runtime: "node",
      executableChecks: 12,
      collections: ["trace", "actions", "redaction"],
    }),
    launcher({
      id: "livehost.authorization",
      subject: "LiveHost",
      displayName: "LiveHost action authorization",
      packageScript: "test:livehost-authorization",
      repositoryModule: "tests/runtime-probes/livehost-authorization.acceptance.mjs",
      runtime: "node",
      executableChecks: 11,
      collections: ["actions", "authorization", "policy"],
    }),
    launcher({
      id: "livehost.node-hosting",
      subject: "LiveHost",
      displayName: "LiveHost Node hosting",
      packageScript: "test:livehost-node-hosting",
      repositoryModule: "tests/livehost-node-hosting.acceptance.mts",
      runtime: "node-real-websocket",
      executableChecks: 44,
      collections: ["transport", "websocket", "node-host", "externally-discoverable"],
    }),
    launcher({
      id: "livehost.bootstrap",
      subject: "LiveHost",
      displayName: "LiveHost HTTP HSON bootstrap",
      packageScript: "test:livehost-bootstrap",
      repositoryModule: "tests/livehost-bootstrap.acceptance.mts",
      runtime: "node-real-websocket",
      executableChecks: 31,
      collections: ["bootstrap", "hson", "recovery", "http", "websocket", "externally-discoverable"],
    }),
    launcher({
      id: "livehost.authority-lifecycle",
      subject: "LiveHost",
      displayName: "LiveHost authority lifecycle",
      packageScript: "test:livehost-authority-lifecycle",
      repositoryModule: "tests/livehost-authority-lifecycle.acceptance.mts",
      runtime: "node",
      executableChecks: 18,
      collections: ["authority", "lifecycle", "eviction", "capacity", "restart", "externally-discoverable"],
    }),
  ]);

/**
 * Package test scripts intentionally outside the external launcher contract.
 * Every other test:* script must have exactly one hson_live_test_launchers entry.
 */
export const hson_live_non_launcher_test_scripts:
readonly HsonLiveNonLauncherTestScript[] = Object.freeze([
  Object.freeze({
    packageScript: "test:diagnostics-inventory",
    reason: "Validates the launcher manifest itself and would recurse if launched externally.",
  }),
  Object.freeze({
    packageScript: "test:hson-array-index",
    reason: "Command-only Transform integration journey; not an externally selectable launcher.",
  }),
  Object.freeze({
    packageScript: "test:hson-attribute-transport",
    reason: "Command-only Transform integration journey; not an externally selectable launcher.",
  }),
  Object.freeze({
    packageScript: "test:livehost-graph-content-codec",
    reason: "Command-only LiveHost integration journey; not an externally selectable launcher.",
  }),
  Object.freeze({
    packageScript: "test:root-compatibility",
    reason: "Production artifact compatibility certification; not an external semantic launcher.",
  }),
  Object.freeze({
    packageScript: "test:transform-worker",
    reason: "Worker entrypoint integration journey; not an externally selectable launcher.",
  }),
]);
