export const COLLECTION_REFLECT_INVALID_SOURCE_ERROR_CODE = "COLLECTION_REFLECT_INVALID_SOURCE" as const;
export const COLLECTION_REFLECT_DUPLICATE_KEY_ERROR_CODE = "COLLECTION_REFLECT_DUPLICATE_KEY" as const;
export const COLLECTION_REFLECT_MISSING_IDENTITY_ERROR_CODE = "COLLECTION_REFLECT_MISSING_IDENTITY" as const;
export const COLLECTION_REFLECT_INVALID_BRANCH_ERROR_CODE = "COLLECTION_REFLECT_INVALID_BRANCH" as const;
export const COLLECTION_REFLECT_BRANCH_ATTACHED_ERROR_CODE = "COLLECTION_REFLECT_BRANCH_ATTACHED" as const;
export const COLLECTION_REFLECT_MAPPING_CONFLICT_ERROR_CODE = "COLLECTION_REFLECT_MAPPING_CONFLICT" as const;
export const COLLECTION_REFLECT_DISPOSED_ERROR_CODE = "COLLECTION_REFLECT_DISPOSED" as const;
export const COLLECTION_REFLECT_SOURCE_REPLACEMENT_ERROR_CODE = "COLLECTION_REFLECT_SOURCE_REPLACEMENT_FAILED" as const;
export const COLLECTION_REFLECT_UNSUPPORTED_OPERATION_ERROR_CODE = "COLLECTION_REFLECT_UNSUPPORTED_OPERATION" as const;
export const COLLECTION_REFLECT_RENDERER_CREATE_ERROR_CODE = "COLLECTION_REFLECT_RENDERER_CREATE_FAILED" as const;
export const COLLECTION_REFLECT_RENDERER_UPDATE_ERROR_CODE = "COLLECTION_REFLECT_RENDERER_UPDATE_FAILED" as const;
export const COLLECTION_REFLECT_HOST_NOT_EMPTY_ERROR_CODE = "COLLECTION_REFLECT_HOST_NOT_EMPTY" as const;

export type CollectionReflectErrorCode =
  | typeof COLLECTION_REFLECT_INVALID_SOURCE_ERROR_CODE
  | typeof COLLECTION_REFLECT_DUPLICATE_KEY_ERROR_CODE
  | typeof COLLECTION_REFLECT_MISSING_IDENTITY_ERROR_CODE
  | typeof COLLECTION_REFLECT_INVALID_BRANCH_ERROR_CODE
  | typeof COLLECTION_REFLECT_BRANCH_ATTACHED_ERROR_CODE
  | typeof COLLECTION_REFLECT_MAPPING_CONFLICT_ERROR_CODE
  | typeof COLLECTION_REFLECT_DISPOSED_ERROR_CODE
  | typeof COLLECTION_REFLECT_SOURCE_REPLACEMENT_ERROR_CODE
  | typeof COLLECTION_REFLECT_UNSUPPORTED_OPERATION_ERROR_CODE
  | typeof COLLECTION_REFLECT_RENDERER_CREATE_ERROR_CODE
  | typeof COLLECTION_REFLECT_RENDERER_UPDATE_ERROR_CODE
  | typeof COLLECTION_REFLECT_HOST_NOT_EMPTY_ERROR_CODE;

/** Stable classified failure raised by the experimental projection engine. */
export class CollectionReflectError extends Error {
  public readonly code: CollectionReflectErrorCode;
  public readonly cause: unknown;

  public constructor(code: CollectionReflectErrorCode, message: string, cause?: unknown) {
    super(message);
    this.name = "CollectionReflectError";
    this.code = code;
    this.cause = cause;
  }
}
