import { createHash, randomUUID } from "node:crypto";
import { existsSync, lstatSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { basename, dirname, extname, isAbsolute, join, relative, resolve, sep } from "node:path";
import ts from "typescript";
import { SchemaProjectSnapshot } from "./project-snapshot.js";
import { HSON_SCHEMA_MVP_COMPATIBILITY_VERSION } from "./compiler.js";
import { generate_hson_schema_evidence } from "./generated-evidence.js";
import {
  apply_source_edits, schema_source_plan, type SchemaSourceEdit,
} from "./source-transformation.js";

type SchemaDeclaration = Readonly<{
  sourceFile: ts.SourceFile;
  declaration: ts.VariableDeclaration;
  name: string;
  source: string;
}>;
type SourceOverlay = SchemaSourceEdit & Readonly<{ file: string }>;
type OwnedFile = Readonly<{ path: string; digest: string }>;
export type SourceRecord = Readonly<{
  source: string;
  generated: string;
  sourceDigest: string;
  edits: readonly SchemaSourceEdit[];
  schemas: readonly Readonly<{ name: string; start: number; end: number; evidence: string }>[];
}>;

export const SCHEMA_PROJECT_COMPATIBILITY = `compiler-project-6/${HSON_SCHEMA_MVP_COMPATIBILITY_VERSION}/typescript-${ts.version}`;
const OWNER = "hson-schema-compiler-input-v1";
const HEADER = "/* Generated by Hson Schema compiler project. Do not edit. */\n";

/** Full source filename and a directory boundary make foo.ts/Foo and foo.mts/Foo distinct. */
export function compiler_project_evidence_path(source: string, name: string): string {
  const extension = extname(source);
  const suffix = extension === ".mts" ? ".mts" : extension === ".cts" ? ".cts" : ".ts";
  return `evidence/${slash(source)}/${name}.hson-schema.generated${suffix}`;
}

/**
 * Checking project materialization. Publication uses isolated staged candidates.
 * Runtime/declaration emission is separate and never changes these inputs.
 */
export function generate_schema_compiler_project(
  projectPath: string,
  config: ts.ParsedCommandLine,
  program: ts.Program,
  schemas: readonly SchemaDeclaration[],
  overlays: readonly SourceOverlay[],
  candidate: Readonly<{ outputRoot: string; finalRoot?: string; snapshot: SchemaProjectSnapshot; diagnostics: readonly string[] }>,
): Readonly<{ project: string; manifest: string; sources: number; schemas: number }> {
  const projectRoot = dirname(resolve(projectPath));
  const outputRoot = candidate.finalRoot ?? candidate.outputRoot;
  if (config.projectReferences?.length) throw new Error("Hson compiler projects do not yet support project references.");
  const sourceFiles = program.getSourceFiles().filter(file => {
    if (program.isSourceFileDefaultLibrary(file) || program.isSourceFileFromExternalLibrary(file)
      || slash(file.fileName).split("/").includes("node_modules")) return false;
    if (!within(projectRoot, file.fileName)) {
      if (file.isDeclarationFile) return false; // External declaration dependencies keep one original identity.
      throw new Error(`Hson compiler project input is outside its project directory: ${file.fileName}`);
    }
    if (within(join(projectRoot, ".hson"), file.fileName)) throw new Error("Authored project inputs must not include generated .hson compiler projects.");
    return true;
  });
  const mirrors = new Map(sourceFiles.map(file => [resolve(file.fileName), join(outputRoot, "sources", relative(projectRoot, file.fileName))]));
  for (const schema of schemas) {
    if (!/\.(?:ts|tsx|mts|cts)$/.test(schema.sourceFile.fileName)) throw new Error(`Hson compiler projects require TypeScript Schema producers: ${schema.sourceFile.fileName}`);
    if (!mirrors.has(resolve(schema.sourceFile.fileName))) throw new Error(`Cannot mirror Schema source ${schema.sourceFile.fileName}.`);
  }
  const planned = new Map<string, Buffer>();
  const collisionKeys = new Map<string, string>();
  const add = (path: string, content: string | Buffer): void => {
    const normalized = owned_path(outputRoot, path);
    const key = normalized.normalize("NFC").toLowerCase();
    const previous = collisionKeys.get(key);
    if (previous !== undefined && previous !== normalized) throw new Error(`Generated filename collision: ${previous} and ${normalized}.`);
    const buffer = typeof content === "string" ? Buffer.from(content) : content;
    const old = planned.get(normalized);
    if (old !== undefined && !old.equals(buffer)) throw new Error(`Conflicting generated contents for ${normalized}.`);
    collisionKeys.set(key, normalized);
    planned.set(normalized, buffer);
  };
  const records: SourceRecord[] = [];
  for (const sourceFile of sourceFiles) {
    const source = slash(relative(projectRoot, sourceFile.fileName));
    const generated = `sources/${source}`;
    const originalBytes = candidate.snapshot.readBytes(sourceFile.fileName);
    const declarations = schemas.filter(schema => schema.sourceFile === sourceFile);
    const associations: { declaration: ts.VariableDeclaration; name: string; specifier: string }[] = [];
    const schemaRecords: SourceRecord["schemas"][number][] = [];
    for (const schema of declarations) {
      const evidencePath = compiler_project_evidence_path(source, schema.name);
      const evidence = generate_hson_schema_evidence(schema.name, schema.source, `${source}#${schema.name}`);
      add(evidencePath, evidence.declaration);
      add(evidencePath.replace(/\.[cm]?ts$/, ".json"), evidence.metadata);
      const runtimePath = evidencePath.replace(/\.mts$/, ".mjs").replace(/\.cts$/, ".cjs").replace(/\.ts$/, ".js");
      const specifier = module_path(relative(dirname(join(outputRoot, generated)), join(outputRoot, runtimePath)));
      associations.push({ declaration: schema.declaration, name: schema.name, specifier });
      schemaRecords.push({ name: schema.name, start: schema.declaration.getStart(), end: schema.declaration.getEnd(), evidence: evidencePath });
    }
    const edits: SchemaSourceEdit[] = [
      ...schema_source_plan(sourceFile, associations).edits,
      ...overlays.filter(overlay => resolve(overlay.file) === resolve(sourceFile.fileName)).map(({ start, end, text }) => ({ start, end, text })),
    ];
    if (!sourceFile.fileName.endsWith(".json")) {
      const shebangOnly = sourceFile.text.startsWith("#!") && !sourceFile.text.includes("\n");
      const headerPosition = shebangOnly ? sourceFile.text.length : sourceFile.text.startsWith("#!") ? sourceFile.text.indexOf("\n") + 1 : 0;
      edits.push({ start: headerPosition, end: headerPosition, text: shebangOnly ? `\n${HEADER}` : HEADER });
      add(generated, apply_source_edits(sourceFile.text, edits));
    } else {
      add(generated, originalBytes); // JSON has no comment syntax; the manifest establishes ownership.
    }
    records.push({ source, generated, sourceDigest: digest(originalBytes), edits, schemas: schemaRecords });
    // Preserve each original package scope, including type/imports/exports and nested scopes.
    for (let directory = dirname(sourceFile.fileName); within(projectRoot, directory); directory = dirname(directory)) {
      const manifest = join(directory, "package.json");
      if (candidate.snapshot.fileExists(manifest)) add(`sources/${slash(relative(projectRoot, manifest))}`, candidate.snapshot.readBytes(manifest));
      if (resolve(directory) === projectRoot) break;
    }
  }

  const remap = (path: string): string => within(projectRoot, path) && !resolve(path).split(sep).includes("node_modules")
    ? join(outputRoot, "sources", relative(projectRoot, path)) : resolve(path);
  const options = config.options;
  const pathsBase = options.baseUrl ?? (typeof options.pathsBasePath === "string" ? options.pathsBasePath : projectRoot);
  const paths = options.paths === undefined ? undefined : Object.fromEntries(Object.entries(options.paths).map(([name, entries]) => [name, entries.map(entry => slash(remap(resolve(pathsBase, entry))))]));
  const externalDeclarationRoots = config.fileNames.filter(path => !mirrors.has(resolve(path)) && program.getSourceFile(path)?.isDeclarationFile === true);
  if (records.length === 0 && externalDeclarationRoots.length === 0) add("sources/__empty__.ts", `${HEADER}export {};\n`);
  add("tsconfig.json", `${JSON.stringify({
    compilerOptions: {
      ...frozen_compiler_options(options),
      noEmit: true, composite: false, incremental: false, tsBuildInfoFile: null,
      declaration: false, declarationMap: false, emitDeclarationOnly: false,
      outFile: null, declarationDir: null, outDir: "./unused-output", rootDir: ".",
      ...(options.baseUrl === undefined ? {} : { baseUrl: slash(remap(options.baseUrl)) }),
      ...(paths === undefined ? {} : { paths }),
      ...(options.rootDirs === undefined ? {} : { rootDirs: options.rootDirs.map(path => slash(remap(path))) }),
      // An explicit typeRoots changes TypeScript's fallback for stub @types packages.
      // Keep implicit discovery implicit; rebase only an authored override.
      ...(options.typeRoots === undefined ? {} : { typeRoots: options.typeRoots.map(path => slash(remap(path))) }),
    },
    // Explicit roots prevent default discovery of either the authored or an old generated graph.
    files: records.length === 0 && externalDeclarationRoots.length === 0 ? ["./sources/__empty__.ts"] : [...records.map(record => `./${record.generated}`), ...externalDeclarationRoots.map(path => slash(resolve(path)))].sort(),
    include: [], exclude: [], references: [],
  }, null, 2)}\n`);
  publish_owned_files(projectRoot, candidate.outputRoot, basename(projectPath), planned, records, { revision: candidate.snapshot.fingerprint(), diagnostics: candidate.diagnostics, observations: candidate.snapshot.records() });
  const generatedProject = join(outputRoot, "tsconfig.json");
  verify_module_graph(generatedProject, program, sourceFiles, mirrors, new SchemaProjectSnapshot({ root: outputRoot, files: new Map([...planned].map(([path, bytes]) => [join(outputRoot, path), bytes])) }));
  return { project: generatedProject, manifest: join(candidate.outputRoot, "manifest.json"), sources: records.length, schemas: schemas.length };
}

/** Reject a changed resolution instead of quietly mixing original and mirrored source identities. */
function verify_module_graph(projectPath: string, original: ts.Program, sources: readonly ts.SourceFile[], mirrors: ReadonlyMap<string, string>, snapshot: SchemaProjectSnapshot): void {
  const read = ts.readConfigFile(projectPath, snapshot.readFile);
  const config = ts.parseJsonConfigFileContent(read.config, snapshot.host, dirname(projectPath), undefined, projectPath);
  const diagnostics = read.error === undefined ? config.errors : [read.error];
  if (diagnostics.length > 0) throw new Error(diagnostics.map(entry => ts.flattenDiagnosticMessageText(entry.messageText, "\n")).join("\n"));
  const generated = ts.createProgram(config.fileNames, config.options, snapshot.compilerHost(config.options));
  for (const file of generated.getSourceFiles()) {
    if (mirrors.has(resolve(file.fileName))) throw new Error(`Generated project resolved an authored input: ${file.fileName}`);
  }
  for (const source of sources) {
    const target = mirrors.get(resolve(source.fileName));
    const copy = target === undefined ? undefined : generated.getSourceFile(target);
    if (copy === undefined) throw new Error(`Missing mirrored module for ${source.fileName}.`);
    if (source.impliedNodeFormat !== copy.impliedNodeFormat) throw new Error(`Package module format changed for ${source.fileName}.`);
    for (const reference of source.referencedFiles) {
      const before = resolve(dirname(source.fileName), reference.fileName);
      const expected = mirrors.get(before) ?? before;
      if (resolve(dirname(copy.fileName), reference.fileName) !== expected) {
        throw new Error(`Hson compiler project cannot preserve reference path ${JSON.stringify(reference.fileName)} from ${source.fileName}.`);
      }
    }
    const visit = (node: ts.Node): void => {
      if (ts.isStringLiteralLike(node) && is_module_reference(node)) {
        const mode = original.getModeForUsageLocation(source, node);
        const before = ts.resolveModuleName(node.text, source.fileName, original.getCompilerOptions(), snapshot.compilerHost(original.getCompilerOptions()), undefined, undefined, mode).resolvedModule;
        if (before !== undefined) {
          const expected = mirrors.get(resolve(before.resolvedFileName)) ?? resolve(before.resolvedFileName);
          const after = ts.resolveModuleName(node.text, copy.fileName, config.options, snapshot.compilerHost(config.options), undefined, undefined, mode).resolvedModule;
          if (after === undefined || resolve(after.resolvedFileName) !== expected) {
            throw new Error(`Hson compiler project cannot preserve resolution of ${JSON.stringify(node.text)} from ${source.fileName}.`);
          }
        }
      }
      ts.forEachChild(node, visit);
    };
    visit(source);
  }
}

function is_module_reference(node: ts.StringLiteralLike): boolean {
  const parent = node.parent;
  return (ts.isImportDeclaration(parent) || ts.isExportDeclaration(parent)) && parent.moduleSpecifier === node
    || ts.isExternalModuleReference(parent)
    || ts.isLiteralTypeNode(parent) && ts.isImportTypeNode(parent.parent)
    || ts.isCallExpression(parent) && parent.arguments[0] === node
      && (parent.expression.kind === ts.SyntaxKind.ImportKeyword || ts.isIdentifier(parent.expression) && parent.expression.text === "require");
}

function publish_owned_files(projectRoot: string, outputRoot: string, project: string, planned: ReadonlyMap<string, Buffer>, sources: readonly SourceRecord[], revision?: Readonly<{ revision: string; diagnostics: readonly string[]; observations: ReturnType<SchemaProjectSnapshot["records"]> }>): void {
  assert_no_symlinks(projectRoot, outputRoot);
  const manifestPath = join(outputRoot, "manifest.json");
  assert_no_symlinks(projectRoot, manifestPath);
  if (existsSync(manifestPath)) throw new Error(`Refusing to mutate an existing compiler revision: ${outputRoot}`);
  for (const path of planned.keys()) {
    const destination = join(outputRoot, owned_path(outputRoot, path));
    assert_no_symlinks(projectRoot, destination);
    if (existsSync(destination)) throw new Error(`Refusing to replace an occupied compiler revision file: ${destination}`);
  }
  const files = [...planned].map(([path, content]): OwnedFile => ({ path, digest: digest(content) })).sort((a, b) => a.path.localeCompare(b.path));
  const contents = { owner: OWNER, compatibility: SCHEMA_PROJECT_COMPATIBILITY, publication: randomUUID(), project, files, sources, ...revision };
  const manifest = `${JSON.stringify({ ...contents, contentDigest: digest(Buffer.from(JSON.stringify(contents))) }, null, 2)}\n`;
  // A staging manifest owns even a partially written candidate; it is never authoritative here.
  writeFileSync(manifestPath, manifest, { flag: "wx" });
  for (const [path, content] of planned) {
    const destination = join(outputRoot, path);
    mkdirSync(dirname(destination), { recursive: true });
    writeFileSync(destination, content, { flag: "wx" });
  }
}

export function read_owned_files(outputRoot: string, manifestPath: string, project: string): readonly OwnedFile[] {
  if (!existsSync(manifestPath)) return [];
  const parsed: unknown = JSON.parse(readFileSync(manifestPath, "utf8"));
  if (!record(parsed) || parsed.owner !== OWNER || parsed.project !== project || !Array.isArray(parsed.files)) {
    throw new Error(`Unrecognized Hson compiler-project ownership manifest: ${manifestPath}`);
  }
  const result: OwnedFile[] = [];
  const seen = new Set<string>();
  for (const file of parsed.files) {
    if (!record(file) || typeof file.path !== "string" || typeof file.digest !== "string" || !/^[a-f0-9]{64}$/.test(file.digest)) throw new Error(`Invalid ownership entry in ${manifestPath}.`);
    const path = owned_path(outputRoot, file.path);
    if (seen.has(path)) throw new Error(`Duplicate ownership entry in ${manifestPath}.`);
    seen.add(path);
    result.push({ path, digest: file.digest });
  }
  return result;
}

function owned_path(root: string, path: string): string {
  if (isAbsolute(path) || path.includes("\\") || path.split("/").some(part => part === ".." || part === "." || part === "")) throw new Error(`Invalid generated path ${path}.`);
  if (path !== "tsconfig.json" && !path.startsWith("sources/") && !path.startsWith("evidence/")) throw new Error(`Unowned generated path ${path}.`);
  if (!within(root, resolve(root, path))) throw new Error(`Generated path escapes output directory: ${path}`);
  return path;
}

export function assert_no_symlinks(root: string, target: string): void {
  if (!within(root, target)) throw new Error(`Generated destination escapes project: ${target}`);
  let current = resolve(root);
  for (const part of relative(root, target).split(sep)) {
    current = join(current, part);
    try {
      if (lstatSync(current).isSymbolicLink() || current !== resolve(target) && !lstatSync(current).isDirectory()) throw new Error(`Generated destination must not traverse a symlink: ${current}`);
    } catch (error) {
      if (!record(error) || error.code !== "ENOENT") throw error;
    }
  }
}

function record(value: unknown): value is Record<string, unknown> { return typeof value === "object" && value !== null; }
function slash(path: string): string { return path.split(sep).join("/"); }
function module_path(path: string): string { const value = slash(path); return value.startsWith(".") ? value : `./${value}`; }
function within(root: string, path: string): boolean { const value = relative(resolve(root), resolve(path)); return value === "" || value !== ".." && !value.startsWith(`..${sep}`) && !isAbsolute(value); }
function digest(value: Buffer): string { return createHash("sha256").update(value).digest("hex"); }

/** Parsed path options are absolute. Serialize the public enum options without retaining mutable extends files. */
function frozen_compiler_options(options: ts.CompilerOptions): Record<string, unknown> {
  const result: Record<string, unknown> = { ...options };
  delete result.configFilePath;
  delete result.configFile;
  delete result.pathsBasePath;
  const enums: Record<string, Record<number, string>> = {
    target: ts.ScriptTarget, module: ts.ModuleKind, moduleResolution: ts.ModuleResolutionKind,
    jsx: ts.JsxEmit, newLine: ts.NewLineKind, moduleDetection: ts.ModuleDetectionKind,
  };
  for (const [key, values] of Object.entries(enums)) {
    const value = result[key];
    if (typeof value === "number") result[key] = values[value]?.toLowerCase();
  }
  if (options.target === ts.ScriptTarget.ESNext) result.target = "esnext";
  if (options.jsx === ts.JsxEmit.ReactJSX) result.jsx = "react-jsx";
  if (options.jsx === ts.JsxEmit.ReactJSXDev) result.jsx = "react-jsxdev";
  if (options.newLine !== undefined) result.newLine = options.newLine === ts.NewLineKind.LineFeed ? "lf" : "crlf";
  if (options.lib !== undefined) result.lib = options.lib.map(lib => lib.replace(/^lib\./, "").replace(/\.d\.ts$/, ""));
  const roundTrip = ts.convertCompilerOptionsFromJson(result, "/");
  if (roundTrip.errors.length) throw new Error(`Cannot freeze generated compiler options: ${roundTrip.errors.map(d => ts.flattenDiagnosticMessageText(d.messageText, "\n")).join("\n")}`);
  for (const key of Object.keys(result)) {
    if (JSON.stringify(roundTrip.options[key]) !== JSON.stringify(options[key])) throw new Error(`Cannot preserve generated compiler option ${key}.`);
  }
  return result;
}

/** Validate the manifest boundary before selecting or retiring a generated project. */
export function validate_schema_project_ownership(projectRoot: string, outputRoot: string, project: string): void {
  assert_no_symlinks(projectRoot, outputRoot);
  const manifest = join(outputRoot, "manifest.json");
  assert_no_symlinks(projectRoot, manifest);
  if (!existsSync(manifest)) throw new Error(`Missing Hson compiler-project ownership manifest: ${manifest}`);
  for (const file of read_owned_files(outputRoot, manifest, project)) {
    const path = join(outputRoot, file.path);
    assert_no_symlinks(projectRoot, path);
    if (!existsSync(path) || !lstatSync(path).isFile() || digest(readFileSync(path)) !== file.digest) {
      throw new Error(`Unowned/edited Hson compiler-project file: ${path}`);
    }
  }
}
