import { legacy_schema_import, legacy_evidence_import } from "./legacy-detection.js";
import { createHash } from "node:crypto";
import { existsSync, lstatSync, readFileSync, readdirSync, unlinkSync, writeFileSync } from "node:fs";
import { dirname, extname, join, resolve } from "node:path";
import ts from "typescript";
import { apply_source_edits, GENERATED_EXPORTS_START, GENERATED_EXPORTS_END, type SchemaSourceEdit } from "./source-transformation.js";

/** Explicit migration only. Removal preserves all bytes outside proven generated syntax. */
export function migrate_schema_associations(project: string, write: boolean) {
  const root = dirname(resolve(project));
  const read = ts.readConfigFile(project, ts.sys.readFile);
  const config = ts.parseJsonConfigFileContent(read.config, ts.sys, root);
  if (read.error || config.errors.length) throw new Error("Cannot migrate a project with invalid configuration.");
  const changes = new Map<string, { before: Buffer; after?: string }>();
  const refused: string[] = [];
  for (const path of config.fileNames) {
    if (!/\.[cm]?tsx?$/.test(path) || path.includes(".hson-schema.generated.")) continue;
    const before = readFileSync(path), text = before.toString("utf8");
    if (before[0] === 0xff && before[1] === 0xfe || before[0] === 0xfe && before[1] === 0xff) { refused.push(`${path}: UTF-16 migration requires explicit manual review; no bytes will be guessed.`); continue; }
    if (!text.includes(GENERATED_EXPORTS_START)) continue;
    try { changes.set(path, { before, after: clean_source(path, text) }); }
    catch (error) { refused.push(`${path}: ${error instanceof Error ? error.message : error}`); }
  }
  // The old metadata binds both the filename and the declaration digest. Never delete by suffix alone.
  const visit = (directory: string): void => {
    for (const entry of readdirSync(directory, { withFileTypes: true })) {
      if (entry.isSymbolicLink() || ["node_modules", "dist", ".git", ".hson", "tmp"].includes(entry.name)) continue;
      const path = join(directory, entry.name);
      if (entry.isDirectory()) { visit(path); continue; }
      if (!entry.name.endsWith(".hson-schema.generated.json")) continue;
      try {
        const before = readFileSync(path), metadata = JSON.parse(before.toString("utf8"));
        if (typeof metadata.declarationIdentity !== "string" || typeof metadata.generatedDeclarationDigest !== "string") continue;
        const split = metadata.declarationIdentity.lastIndexOf("#");
        const source = resolve(root, metadata.declarationIdentity.slice(0, split));
        const name = metadata.declarationIdentity.slice(split + 1);
        if (split < 1 || !/^[A-Za-z_$][\w$]*$/.test(name) || !source.startsWith(root + "/")) continue;
        const stem = source.slice(0, -extname(source).length);
        if (resolve(path) !== `${stem}.${name}.hson-schema.generated.json`) continue;
        const declaration = path.slice(0, -4) + "ts";
        if (!existsSync(declaration) || lstatSync(declaration).isSymbolicLink()) throw new Error("Missing or linked declaration; leave metadata untouched.");
        const bytes = readFileSync(declaration);
        if (createHash("sha256").update(bytes).digest("hex") !== metadata.generatedDeclarationDigest
          || !bytes.toString("utf8").startsWith("/* Generated by Hson Schema ")) throw new Error("Edited generated declaration; cleanup refused.");
        changes.set(path, { before }); changes.set(declaration, { before: bytes });
      } catch (error) { refused.push(`${path}: ${error instanceof Error ? error.message : error}`); }
    }
  };
  visit(root);
  // One ambiguous source blocks this operation, including removal of its still-referenced sidecars.
  if (refused.length) throw new Error(`Legacy migration refused; no files changed:\n${refused.join("\n")}`);
  if (write) {
    for (const [path, change] of changes) if (lstatSync(path).isSymbolicLink() || !readFileSync(path).equals(change.before)) throw new Error(`Migration input changed: ${path}`);
    for (const [path, change] of changes) if (change.after === undefined) unlinkSync(path); else writeFileSync(path, change.after);
  }
  return { hsonSchema: "migrate", applied: write, changes: [...changes].map(([path, change]) => ({ path, operation: change.after === undefined ? "remove-owned-artifact" : "remove-legacy-syntax" })), note: "Original formatting and overwritten local annotations cannot be recovered. Only recognized generated syntax is removed." };
}

function clean_source(path: string, text: string): string {
  const start = text.indexOf(GENERATED_EXPORTS_START), markerEnd = text.indexOf(GENERATED_EXPORTS_END, start);
  if (markerEnd < 0 || text.indexOf(GENERATED_EXPORTS_START, start + 1) >= 0) throw new Error("Ambiguous legacy markers.");
  const end = markerEnd + GENERATED_EXPORTS_END.length;
  const source = ts.createSourceFile(path, text, ts.ScriptTarget.Latest, true);
  const block = text.slice(start + GENERATED_EXPORTS_START.length, markerEnd);
  const parsed = ts.createSourceFile(path, block, ts.ScriptTarget.Latest, true);
  const aliases = new Map<string, string>();
  let schemaAlias: string | undefined;
  for (const statement of parsed.statements) {
    if (!ts.isImportDeclaration(statement) || !statement.importClause?.isTypeOnly || !ts.isStringLiteral(statement.moduleSpecifier)) throw new Error("Legacy block contains authored or unrecognized syntax.");
    const bindings = statement.importClause.namedBindings;
    if (bindings === undefined || !ts.isNamedImports(bindings) || bindings.elements.length !== 1) throw new Error("Ambiguous legacy import.");
    const binding = bindings.elements[0]!;
    if (legacy_schema_import(binding, statement.moduleSpecifier.text) && schemaAlias === undefined) schemaAlias = binding.name.text;
    else if (legacy_evidence_import(binding, statement.moduleSpecifier.text)) aliases.set(binding.name.text, statement.moduleSpecifier.text);
    else throw new Error("Unrecognized generated import.");
  }
  if (schemaAlias === undefined || !aliases.size || /\/\*|\/\//.test(block)) throw new Error("Unrecognized or commented legacy block.");
  const edits: SchemaSourceEdit[] = [{ start, end, text: "" }];
  const normalized = (node: ts.Node): string => node.getText(source).replace(/\s/g, "");
  for (const statement of source.statements) if (ts.isVariableStatement(statement)) for (const declaration of statement.declarationList.declarations) {
    if (!ts.isIdentifier(declaration.name) || declaration.type === undefined || declaration.initializer === undefined) continue;
    const alias = `__${declaration.name.text}Evidence`;
    if (!aliases.has(alias)) continue;
    const expected = `${schemaAlias}<${alias}["value"],${alias}["mode"],${alias}["identity"]>`;
    if (normalized(declaration.type).replace(/'/g, '"') !== expected) throw new Error("Legacy annotation was edited.");
    const init = declaration.initializer;
    if (!ts.isParenthesizedExpression(init) || !ts.isAsExpression(init.expression) || normalized(init.expression.type).replace(/'/g, '"') !== expected
      || !ts.isAsExpression(init.expression.expression) || init.expression.expression.type.kind !== ts.SyntaxKind.UnknownKeyword
      || !ts.isTaggedTemplateExpression(init.expression.expression.expression)) throw new Error("Legacy initializer shape is ambiguous.");
    const tag = init.expression.expression.expression;
    const colon = text.slice(declaration.name.end, declaration.type.getStart()).indexOf(":") + declaration.name.end;
    if (colon < declaration.name.end) throw new Error("Missing generated annotation colon.");
    edits.push({ start: colon, end: declaration.type.end, text: "" }, { start: init.getStart(), end: tag.getStart(), text: "" }, { start: tag.end, end: init.end, text: "" });
  }
  for (const edit of edits.slice(1)) if (/\/\*|\/\//.test(text.slice(edit.start, edit.end))) throw new Error("Comment inside generated syntax; cleanup refused.");
  const result = apply_source_edits(text, edits);
  const remaining = ts.createSourceFile(path, result, ts.ScriptTarget.Latest, true);
  const visit = (node: ts.Node): void => {
    if (ts.isIdentifier(node) && (node.text === schemaAlias || aliases.has(node.text))) throw new Error("Generated alias has an unrecognized authored use.");
    ts.forEachChild(node, visit);
  };
  visit(remaining);
  return result;
}
