import ts from "typescript";
import { basename, dirname, extname, resolve } from "node:path";
import { GENERATED_EXPORTS_START, GENERATED_EXPORTS_END } from "./source-transformation.js";

export const SCHEMA_MIGRATION_REQUIRED = "Legacy Hson Schema source or colocated evidence detected. Run `hson-schema migrate` to preview the cleanup, then `hson-schema migrate --write` to apply it.";

/** Shared recognition only; this never establishes cleanup ownership or plans edits. */
export function legacy_schema_import(binding: ts.ImportSpecifier, module: string): boolean {
  return binding.propertyName?.text === "HsonSchema" && binding.name.text === "__HsonSchema" && module === "hson-live";
}
export function legacy_evidence_import(binding: ts.ImportSpecifier, module: string): boolean {
  return binding.propertyName?.text === "Evidence" && /^__[\w$]+Evidence$/.test(binding.name.text)
    && /^\.\/[^/]+\.hson-schema\.generated\.[cm]?js$/.test(module);
}

/** Authored-tree preflight. Current .hson compiler/editor evidence is never legacy. */
export function requires_schema_migration(
  source: ts.SourceFile,
  project: string,
  readFile: (path: string) => string | undefined = ts.sys.readFile,
  readDirectory: ts.ParseConfigHost["readDirectory"] = ts.sys.readDirectory,
): boolean {
  if (source.isDeclarationFile || source.fileName.replaceAll("\\", "/").split("/").includes(".hson")) return false;
  let legacy = false;
  const visit = (node: ts.Node): void => {
    if (ts.isTypeReferenceNode(node) && ts.isIdentifier(node.typeName) && node.typeName.text === "__HsonSchema") legacy = true;
    if (ts.isImportDeclaration(node) && node.importClause?.isTypeOnly && ts.isStringLiteral(node.moduleSpecifier)) {
      const bindings = node.importClause.namedBindings;
      if (bindings !== undefined && ts.isNamedImports(bindings)) {
        const module = node.moduleSpecifier.text;
        if (bindings.elements.some(binding => legacy_schema_import(binding, module) || legacy_evidence_import(binding, module))) legacy = true;
      }
    }
    ts.forEachChild(node, visit);
  };
  visit(source);
  for (const node of [...source.statements, source.endOfFileToken]) {
    for (const comment of ts.getLeadingCommentRanges(source.text, node.getFullStart()) ?? []) {
      const text = source.text.slice(comment.pos, comment.end);
      if (text === GENERATED_EXPORTS_START || text === GENERATED_EXPORTS_END) legacy = true;
    }
  }
  if (legacy) return true;
  const stem = basename(source.fileName, extname(source.fileName));
  for (const path of readDirectory(dirname(source.fileName), [".ts", ".json"], [], [`${stem}.*.hson-schema.generated.*`], 1)) {
    const text = readFile(path);
    if (text === undefined) continue;
    if (path.endsWith(".ts") && text.startsWith("/* Generated by Hson Schema ")) return true;
    if (path.endsWith(".json")) try {
      const metadata = JSON.parse(text);
      if (typeof metadata.declarationIdentity !== "string" || typeof metadata.generatedDeclarationDigest !== "string") continue;
      const split = metadata.declarationIdentity.lastIndexOf("#");
      const name = metadata.declarationIdentity.slice(split + 1);
      if (split > 0 && /^[A-Za-z_$][\w$]*$/.test(name)
        && resolve(dirname(project), metadata.declarationIdentity.slice(0, split)) === resolve(source.fileName)
        && basename(path) === `${stem}.${name}.hson-schema.generated.json`) return true;
    } catch { /* Unrecognized metadata does not establish legacy ownership. */ }
  }
  return false;
}
