// index.ts

export * from "./hson.js";
export { LiveTree } from "./api/livetree/livetree.js";
export {
    LIVETREE_ALREADY_ATTACHED_ERROR_CODE,
    LIVETREE_DISPOSED_ERROR_CODE,
    LIVETREE_PROTECTED_ROOT_ERROR_CODE,
    LIVETREE_BATCH_ATTACHMENT_ERROR_CODE,
    LIVETREE_BATCH_VALIDATION_ERROR_CODE,
    LiveTreeBatchError,
    LiveTreeAlreadyAttachedError,
    LiveTreeDisposedError,
    LiveTreeProtectedRootError,
} from "./api/livetree/livetree.error.js";
export type { DetachedLiveContent, LiveTreeLifecycleResult } from "./types/lifecycle.types.js";
export { CssManager } from "./api/livetree/managers/css-manager.js";
export { make_tree_selector } from "./api/livetree/creation/make-tree-selector.js";

export { make_livemap_core } from "./api/livemap/livemap.core.js";
export { project_keyed_collection } from "./api/liveproject/liveproject.keyed.js";
export { create_live_inspector } from "./api/liveinspect/liveinspect.js";
export {
    LIVE_INSPECTOR_DISPOSED_ERROR_CODE,
    LIVE_INSPECTOR_DUPLICATE_ARRAY_KEY_ERROR_CODE,
    LIVE_INSPECTOR_EXPAND_LIMIT_ERROR_CODE,
    LIVE_INSPECTOR_INVALID_PATH_ERROR_CODE,
    LIVE_INSPECTOR_INVALID_ROOT_ERROR_CODE,
    LIVE_INSPECTOR_MISSING_ARRAY_KEY_ERROR_CODE,
    LIVE_INSPECTOR_NON_STRUCTURAL_EXPANSION_ERROR_CODE,
    LIVE_INSPECTOR_OBSERVER_ERROR_CODE,
    LIVE_INSPECTOR_PROJECTION_ERROR_CODE,
    LIVE_INSPECTOR_RENDERER_HOOK_ERROR_CODE,
    LIVE_INSPECTOR_SOURCE_REPLACEMENT_ERROR_CODE,
    LIVE_INSPECTOR_SPECIALIZATION_ERROR_CODE,
    LIVE_INSPECTOR_UNREPRESENTABLE_CONVERSION_ERROR_CODE,
    LIVE_INSPECTOR_UNSUPPORTED_SERIALIZATION_ERROR_CODE,
    LIVE_INSPECTOR_UNSUPPORTED_SOURCE_ERROR_CODE,
    LiveInspectorError,
} from "./api/liveinspect/liveinspect.error.js";
export type { LiveInspectorErrorCode } from "./api/liveinspect/liveinspect.error.js";
export {
    LIVE_PROJECTION_BRANCH_ATTACHED_ERROR_CODE,
    LIVE_PROJECTION_DISPOSED_ERROR_CODE,
    LIVE_PROJECTION_DUPLICATE_KEY_ERROR_CODE,
    LIVE_PROJECTION_HOST_NOT_EMPTY_ERROR_CODE,
    LIVE_PROJECTION_INVALID_BRANCH_ERROR_CODE,
    LIVE_PROJECTION_INVALID_SOURCE_ERROR_CODE,
    LIVE_PROJECTION_MAPPING_CONFLICT_ERROR_CODE,
    LIVE_PROJECTION_MISSING_IDENTITY_ERROR_CODE,
    LIVE_PROJECTION_RENDERER_CREATE_ERROR_CODE,
    LIVE_PROJECTION_RENDERER_UPDATE_ERROR_CODE,
    LIVE_PROJECTION_SOURCE_REPLACEMENT_ERROR_CODE,
    LIVE_PROJECTION_UNSUPPORTED_OPERATION_ERROR_CODE,
    LiveProjectionError,
} from "./api/liveproject/liveproject.error.js";
export type { LiveProjectionErrorCode } from "./api/liveproject/liveproject.error.js";
export { make_livemap_store_api } from "./api/livemap/livemap.store.js";
export { LiveMapDocumentInstallError, LiveMapDocumentMutationError } from "./api/livemap/livemap.error.js";
export type { LiveMapDocumentMutationErrorCode } from "./api/livemap/livemap.error.js";
export { format_live_path, path_is_prefix, paths_overlap } from "./api/livemap/livemap.path.js";
export { link_livemap } from "./api/livemap/livemap.link.js";
export { make_livemap_feed_hub } from "./api/livemap/livemap.feed.js";
export { make_livemap_proxy } from "./api/livemap/livemap.proxy.js";
export {
    bind_path,
    bind_paths,
    derive_from_paths,
    make_microtask_scheduler,
    stop_all,
    subscribe_paths,
} from "./api/livemap/livemap-helpers.js";
export {
    get_livemap_quid,
    get_livemap_owner,
    ensure_livemap_quid,
    reindex_livemap_quid,
    drop_livemap_quid,
    remint_livemap_quid,
    debug_livemap_quids
} from "./api/livemap/livemap.quid.js";
export { create_livehost_store, create_livehost_store as create_livehost_registry } from "./api/livehost/livehost.store.js";
export { make_livehost_resume_log } from "./api/livehost/livehost.resume.js";
export { create_livehost_client } from "./api/livehost/livehost.client.js";
export {
    LiveHostDisconnectedError,
    LiveHostDuplicateActionIdError,
    LiveHostClientRecoveryError,
    LiveHostClientSessionError,
    LiveHostRecoveryError,
} from "./api/livehost/livehost.error.js";
export { make_livehost_sync_manager } from "./api/livehost/livehost.sync.js";
export { make_livehost_canonical_stream } from "./api/livehost/livehost.history.js";
export { make_livehost_recovery_planner } from "./api/livehost/livehost.recovery.js";
export { decode_livehost_message, decode_livehost_server_message, encode_livehost_message } from "./api/livehost/livehost.protocol.js";
export { create_livehost } from "./api/livehost/livehost.core.js";
export type {
    LiveMapPathHandle,
    LiveMapProxy,
    LivePath,
    LivePathPart,
    LiveMapEditResult,
    LiveMapCommit,
    LiveMapOp,
    LiveMapAnyOp,
    LiveMapDataOp,
    LiveMapGraphOp,
    LiveMapGraphReplaceRootOp,
    LiveMapGraphSetAttrOp,
    LiveMapGraphRemoveAttrOp,
    LiveMapGraphReplaceContentOp,
    LiveMapGraphCommit,
    LiveMapFeedEvent,
    LiveMapFeedListener,
    LiveMapDisposer,
    LiveMapCore,
    LiveMapNodeHandle,
    LiveMap,
    LiveMapRootMode,
    DataLiveMapMode,
    DocumentLiveMapMode,
    DocumentLiveMapCapture,
    DocumentLiveMapInstallOptions,
    LiveMapDocumentPath,
    LiveMapDocumentTarget,
    LiveMapDocumentAttributeValue,
    LiveMapDocumentContent,
    DocumentLiveMapAttrsApi,
    DocumentLiveMapContentApi,
    DocumentLiveMapReadApi,
    ElementLiveMapReadApi,
    ElementLiveMap,
    FragmentLiveMap,
    DocumentLiveMap,
    ClassifiedLiveMap,
    LiveKeyedProjection,
    LiveKeyedProjectionOptions,
    LiveProjectionChange,
    LiveProjectionChangeKind,
    LiveProjectionDiagnostics,
    LiveProjectionItemContext,
    LiveProjectionItemUpdate,
    LiveProjectionKey,
    LiveProjectionListener,
    LiveProjectionMappingSummary,
    LiveProjectionRender,
    LiveProjectionRenderResult,
    LiveProjectionSnapshot,
    LiveProjectionStatus,
    LiveInspector,
    LiveInspectorArrayIdentity,
    LiveInspectorArrayKeyContext,
    LiveInspectorArrayKeyResolver,
    LiveInspectorBranchRole,
    LiveInspectorDiagnostics,
    LiveInspectorHsonMode,
    LiveInspectorListener,
    LiveInspectorMappingSummary,
    LiveInspectorOptions,
    LiveInspectorOwnedHsonOptions,
    LiveInspectorOwnedJsonOptions,
    LiveInspectorReadHandle,
    LiveInspectorRendererResult,
    LiveInspectorRendererUpdate,
    LiveInspectorRenderers,
    LiveInspectorSelection,
    LiveInspectorSemanticContext,
    LiveInspectorSemanticRenderer,
    LiveInspectorSerializationTarget,
    LiveInspectorSnapshot,
    LiveInspectorSource,
    LiveInspectorSpecialization,
    LiveInspectorStatus,
    LiveInspectorValueKind,
    LiveHost,
    LiveHostActionContext,
    LiveHostActionOrigin,
    LiveHostActionHandler,
    LiveHostActionId,
    LiveHostActionRequestId,
    LiveHostActionStatusId,
    LiveHostActionDelivery,
    LiveHostActionDedupeDiagnostics,
    LiveHostActionDedupeInspector,
    LiveHostActionDedupeOptions,
    LiveHostActionDedupeSchedule,
    LiveHostActionRequestErrorCode,
    LiveHostActionStatusState,
    LiveHostActionTerminalOutcome,
    LiveHostActionName,
    LiveHostActionPayloads,
    LiveHostActions,
    LiveHostClient,
    LiveHostClientActionFn,
    LiveHostClientActionResult,
    LiveHostClientActionPromise,
    LiveHostClientActionRequest,
    LiveHostClientActionStatusResult,
    LiveHostClientActionStatusMessage,
    LiveHostClientRetryActionFn,
    LiveHostClientRecoverMessage,
    LiveHostClientSession,
    LiveHostClientSessionAttachMessage,
    LiveHostClientSessionCreateMessage,
    LiveHostClientSessionDiagnostics,
    LiveHostClientSessionFailure,
    LiveHostClientSessionGoodbyeMessage,
    LiveHostClientSessionOptions,
    LiveHostClientSessionResult,
    LiveHostClientSessionStatus,
    LiveHostClientRecovery,
    LiveHostClientRecoveryChange,
    LiveHostClientRecoveryChangeListener,
    LiveHostClientRecoveryCursor,
    LiveHostClientRecoveryDiagnostics,
    LiveHostClientRecoveryFailure,
    LiveHostClientRecoveryOptions,
    LiveHostClientRecoveryResult,
    LiveHostClientRecoveryStatus,
    LiveHostClientRecoveryStrategy,
    LiveHostClientHelloMessage,
    LiveHostClientMessage,
    LiveHostClientOptions,
    LiveHostCanonicalCommit,
    LiveHostCanonicalCommitListener,
    LiveHostCanonicalDeleteOp,
    LiveHostCanonicalHistory,
    LiveHostCanonicalHistoryDiagnostics,
    LiveHostCanonicalHistoryOptions,
    LiveHostCanonicalOp,
    LiveHostCanonicalReplaceOp,
    LiveHostCanonicalSetOp,
    LiveHostCanonicalSpliceOp,
    LiveHostCanonicalStream,
    LiveHostCanonicalStreamOptions,
    LiveHostRecoveryAttemptBase,
    LiveHostRecoveryAttemptDiagnostics,
    LiveHostRecoveryAttemptState,
    LiveHostRecoveryBodyItem,
    LiveHostRecoveryBodyObserver,
    LiveHostRecoveryCaughtUp,
    LiveHostRecoveryCompletion,
    LiveHostRecoveryCurrentPlan,
    LiveHostRecoveryHooks,
    LiveHostRecoveryId,
    LiveHostRecoveryOptions,
    LiveHostRecoveryPlan,
    LiveHostRecoveryPlanner,
    LiveHostRecoveryPlannerDiagnostics,
    LiveHostRecoveryRejectCode,
    LiveHostRecoveryRejectPlan,
    LiveHostRecoveryRejection,
    LiveHostRecoveryReplayPlan,
    LiveHostRecoveryRequest,
    LiveHostRecoveryRuntimeErrorCode,
    LiveHostRecoverySnapshotPlan,
    LiveHostRecoverySnapshotReason,
    LiveHostDisposer,
    LiveHostConnection,
    LiveHostEventListener,
    LiveHostError,
    LiveHostId,
    LiveHostIncarnationId,
    LiveHostLogicalMapId,
    LiveHostOptions,
    LiveTraceSink,
    LiveHostResult,
    LiveHostSchema,
    LiveHostSchemaDecoder,
    LiveHostSchemaIssue,
    LiveHostSchemaResult,
    LiveHostSeq,
    LiveHostConnectionEpoch,
    LiveHostServerMessage,
    LiveHostServerActionStatusMessage,
    LiveHostServerCanonicalCommitMessage,
    LiveHostServerEventMessage,
    LiveHostServerRecoveryCaughtUpMessage,
    LiveHostServerRecoveryCommitMessage,
    LiveHostServerRecoveryErrorMessage,
    LiveHostServerRecoveryPlanMessage,
    LiveHostServerRecoverySnapshotMessage,
    LiveHostServerSessionAttachedMessage,
    LiveHostServerSessionCreatedMessage,
    LiveHostServerSessionEndedMessage,
    LiveHostServerSessionFencedMessage,
    LiveHostServerSessionRejectedMessage,
    LiveHostSocketLike,
    LiveHostSessionCredential,
    LiveHostSessionDiagnostic,
    LiveHostSessionDiagnostics,
    LiveHostSessionInspector,
    LiveHostSessionLifecycleEvent,
    LiveHostSessionOptions,
    LiveHostSessionRejectCode,
    LiveHostSessionRequestId,
    LiveHostSessionSchedule,
    LiveHostSessionState,
    LiveHostSnapshotEnvelope,
    LiveHostStore,
    LiveHostStoreCreateOptions,
    LiveHostStoreEntry,
    LiveHostStoreId,
    LiveHostValidator,
    LiveHostWireValue,
} from "./types/index.js";
export { LiveMapSchemaError } from "./api/livemap/livemap.error.js";
export { snap_live_path } from "./api/livemap/livemap.editor.js";
export { make_livemap_schema, define_livemap_schema, LIVEMAP_SCHEMA } from "./api/livemap/livemap.schema.js";
export type { InferLiveMapSchema, LiveMapSchema, InferLiveMapSchemaToken, LiveMapSchemaValue, LiveMapSchemaBuilder, LiveMapSchemaValidation, LiveMapSchemaIssue, LiveMapSchemaInput, LiveMapSchemaKind, LiveMapSchemaRule, LiveMapSchemaShape, LiveMapSchemaToken } from "./api/livemap/livemap.schema.js";
export { ELEM_TAG, OBJ_TAG, ARR_TAG, ROOT_TAG, II_TAG, STR_TAG, VAL_TAG, ATTRS_KEY, META_KEY, TAG_KEY, CONTENT_KEY } from "./core/constants.js";
export { make_sanitizer, type SanitizerLike } from "./safety/sanitize-html.utils.js";
