// index.ts

export { hson, hsonCalc, hsonNumber, hsonString, type HsonFacade } from "./hson.js";
export {
    TransformError,
    is_transform_error,
    read_transform_error_details,
} from "./core/errors.js";
export type {
    TransformErrorDetails,
    TransformErrorRelated,
    TransformErrorSource,
} from "./core/errors.js";
export {
    HSON_CALC_FUNCTION_REQUIRED,
} from "./api/transform/hson-calc.js";
export {
    HSON_NUMBER_NONFINITE,
    HSON_NUMBER_TYPE_REQUIRED,
    type HsonNumber,
} from "./api/transform/hson-number.js";
export { hsonReflect, type Reflect } from "./api/reflect/reflect.facade.js";
export { LiveTree } from "./api/livetree/livetree.js";
export {
    LIVETREE_ALREADY_ATTACHED_ERROR_CODE,
    LIVETREE_DISPOSED_ERROR_CODE,
    LIVETREE_PROTECTED_ROOT_ERROR_CODE,
    LIVETREE_BATCH_ATTACHMENT_ERROR_CODE,
    LIVETREE_BATCH_VALIDATION_ERROR_CODE,
    LIVETREE_ATTRIBUTE_NOT_FOUND_ERROR_CODE,
    LIVETREE_INVALID_ATTRIBUTE_NAME_ERROR_CODE,
    LIVETREE_INVALID_ATTRIBUTE_VALUE_ERROR_CODE,
    LIVETREE_PROTECTED_ATTRIBUTE_ERROR_CODE,
    LIVETREE_QUID_REUSE_ERROR_CODE,
    LiveTreeAttributeError,
    LiveTreeBatchError,
    LiveTreeAlreadyAttachedError,
    LiveTreeDisposedError,
    LiveTreeProtectedRootError,
    LiveTreeQuidReuseError,
} from "./api/livetree/livetree.error.js";
export {
    LIVETREE_LINKED_IDENTITY_REQUIRED_ERROR_CODE,
    LiveTreeLinkedIdentityRequiredError,
} from "./api/livetree/lifecycle/document-binding-state.js";
export type { LiveTreeAttributeErrorCode } from "./api/livetree/livetree.error.js";
export type { DetachedLiveContent, LiveTreeLifecycleResult } from "./types/lifecycle.types.js";
export { CssManager } from "./api/livetree/managers/css-manager.js";
export { make_tree_selector } from "./api/livetree/creation/make-tree-selector.js";
export { TreeSelector } from "./api/livetree/creation/tree-selector.js";

export { make_livemap_core } from "./api/livemap/livemap.core.js";
export { reflect_collection } from "./api/reflect/reflect.collection.js";
export {
    reflect_document,
    type DocumentReflect,
    type DocumentReflectStatus,
} from "./api/reflect/reflect.document.js";
export * from "./api/reflect/reflect.document.error.js";
export { create_live_inspector } from "./api/liveinspect/liveinspect.js";
export {
    LIVE_INSPECTOR_DISPOSED_ERROR_CODE,
    LIVE_INSPECTOR_DUPLICATE_ARRAY_KEY_ERROR_CODE,
    LIVE_INSPECTOR_EXPAND_LIMIT_ERROR_CODE,
    LIVE_INSPECTOR_INVALID_PATH_ERROR_CODE,
    LIVE_INSPECTOR_INVALID_ROOT_ERROR_CODE,
    LIVE_INSPECTOR_MISSING_ARRAY_KEY_ERROR_CODE,
    LIVE_INSPECTOR_NON_STRUCTURAL_EXPANSION_ERROR_CODE,
    LIVE_INSPECTOR_OBSERVER_ERROR_CODE,
    LIVE_INSPECTOR_PROJECTION_ERROR_CODE,
    LIVE_INSPECTOR_RENDERER_HOOK_ERROR_CODE,
    LIVE_INSPECTOR_SOURCE_REPLACEMENT_ERROR_CODE,
    LIVE_INSPECTOR_SPECIALIZATION_ERROR_CODE,
    LIVE_INSPECTOR_UNREPRESENTABLE_CONVERSION_ERROR_CODE,
    LIVE_INSPECTOR_UNSUPPORTED_SERIALIZATION_ERROR_CODE,
    LIVE_INSPECTOR_UNSUPPORTED_SOURCE_ERROR_CODE,
    LiveInspectorError,
} from "./api/liveinspect/liveinspect.error.js";
export type { LiveInspectorErrorCode } from "./api/liveinspect/liveinspect.error.js";
export {
    COLLECTION_REFLECT_BRANCH_ATTACHED_ERROR_CODE,
    COLLECTION_REFLECT_DISPOSED_ERROR_CODE,
    COLLECTION_REFLECT_DUPLICATE_KEY_ERROR_CODE,
    COLLECTION_REFLECT_HOST_NOT_EMPTY_ERROR_CODE,
    COLLECTION_REFLECT_INVALID_BRANCH_ERROR_CODE,
    COLLECTION_REFLECT_INVALID_SOURCE_ERROR_CODE,
    COLLECTION_REFLECT_MAPPING_CONFLICT_ERROR_CODE,
    COLLECTION_REFLECT_MISSING_IDENTITY_ERROR_CODE,
    COLLECTION_REFLECT_RENDERER_CREATE_ERROR_CODE,
    COLLECTION_REFLECT_RENDERER_UPDATE_ERROR_CODE,
    COLLECTION_REFLECT_SOURCE_REPLACEMENT_ERROR_CODE,
    COLLECTION_REFLECT_UNSUPPORTED_OPERATION_ERROR_CODE,
    CollectionReflectError,
} from "./api/reflect/reflect.collection.error.js";
export type { CollectionReflectErrorCode } from "./api/reflect/reflect.collection.error.js";
export { make_livemap_store_api } from "./api/livemap/livemap.store.js";
export {
    LiveMapDocumentAttributeNotFoundError,
    LiveMapDocumentInstallError,
    LiveMapDocumentIdentityProvenanceError,
    LiveMapDocumentIdentityRegistrationError,
    LiveMapDocumentMutationError,
    LiveMapDocumentStagingError,
    LiveMapProjectedTransportError,
    LiveMapProjectedValueError,
    LiveMapProjectedMutationError,
    LiveMapReplayError,
    LiveMapReplayInputError,
    LiveMapRevError,
} from "./api/livemap/livemap.error.js";
export type {
    LiveMapDocumentIdentityProvenanceErrorCode,
    LiveMapDocumentIdentityRegistrationErrorCode,
    LiveMapDocumentInstallFailureCode,
    LiveMapDocumentMutationErrorCode,
    LiveMapProjectedMutationErrorCode,
} from "./api/livemap/livemap.error.js";
export { format_live_path, path_is_prefix, paths_overlap } from "./api/livemap/livemap.path.js";
export {
    LiveMapDocumentPathError,
    validate_document_path,
} from "./api/livemap/livemap.document.path.js";
export { link_livemap } from "./api/livemap/livemap.link.js";
export { make_livemap_feed_hub } from "./api/livemap/livemap.feed.js";
export { make_livemap_proxy } from "./api/livemap/livemap.proxy.js";
export {
    bind_path,
    bind_paths,
    derive_from_paths,
    make_microtask_scheduler,
    stop_all,
    subscribe_paths,
} from "./api/livemap/livemap-helpers.js";
export { create_livehost_store, create_livehost_store as create_livehost_registry } from "./api/livehost/livehost.store.js";
export {
  create_persistent_livehost,
  create_livehost_persistent_store,
  LiveHostPersistenceError,
} from "./api/livehost/livehost.persistence.js";
export type { LiveHostPersistenceErrorCode } from "./api/livehost/livehost.persistence.error.js";
export { create_livehost_client } from "./api/livehost/livehost.client.js";
export {
    LiveHostDisconnectedError,
    LiveHostDuplicateActionIdError,
    LiveHostClientRecoveryError,
    LiveHostClientSessionError,
    LiveHostRecoveryError,
} from "./api/livehost/livehost.error.js";
export {
    make_livehost_sync_manager,
    type LiveHostSyncManager,
    type LiveHostSyncSend,
    type LiveHostSyncSession,
} from "./api/livehost/livehost.sync.js";
export { make_livehost_canonical_stream } from "./api/livehost/livehost.history.js";
export { make_livehost_recovery_planner } from "./api/livehost/livehost.recovery.js";
export { decode_livehost_message, decode_livehost_server_message, encode_livehost_message } from "./api/livehost/livehost.protocol.js";
export { create_livehost } from "./api/livehost/livehost.core.js";
export {
    LiveHostAuthorityError,
    type LiveHostAuthorityErrorCode,
} from "./api/livehost/livehost.authority.js";
export type {
    LiveMapPathHandle,
    LiveMapProxy,
    LivePath,
    LivePathPart,
    LiveMapEditResult,
    LiveMapCommit,
    LiveMapStructuralJsonEnvelope,
    LiveMapExactCapture,
    LiveMapCanonicalCapture,
    LiveMapLegacyCapture,
    LiveMapCapture,
    LiveMapCaptureInput,
    LiveMapExactApply,
    LiveMapLegacyApply,
    LiveMapApply,
    LiveMapExactReplay,
    LiveMapLegacyReplay,
    LiveMapReplay,
    LiveMapOp,
    LiveMapAnyOp,
    LiveMapDataOp,
    LiveMapRenameOp,
    LiveMapMoveOp,
    LiveMapGraphOp,
    LiveMapGraphReplaceRootOp,
    LiveMapGraphSetAttrOp,
    LiveMapGraphRemoveAttrOp,
    LiveMapGraphReplaceAttrsOp,
    LiveMapGraphReplaceContentOp,
    LiveMapGraphInsertContentOp,
    LiveMapGraphRemoveContentOp,
    LiveMapGraphMoveContentOp,
    LiveMapGraphEnsureQuidOp,
    LiveMapProjectedGraphEnsureQuidOp,
    LiveMapGraphCommit,
    LiveMapFeedEvent,
    LiveMapFeedListener,
    LiveMapDisposer,
    LiveMapCore,
    LiveMapNodeHandle,
    LiveMap,
    LiveMapRootMode,
    DataLiveMapMode,
    DocumentLiveMapMode,
    DocumentLiveMapCapture,
    DocumentLiveMapCaptureApi,
    DocumentLiveMapCaptureIdentity,
    DocumentLiveMapCaptureOptions,
    DocumentLiveMapInstallIdentity,
    DocumentLiveMapInstallOptions,
    LiveMapDocumentPath,
    LiveMapDocumentPathInput,
    LiveMapDocumentIdentityHandle,
    LiveMapProjectedIdentityHandle,
    LiveMapProjectedIdentityCommitTarget,
    LiveMapDocumentRequestTarget,
    LiveMapDocumentCommitTarget,
    LiveMapDocumentTargetWitness,
    LiveMapDocumentTarget,
    LiveMapDocumentAttributeValue,
    LiveMapDocumentAttrs,
    LiveMapDocumentContent,
    DocumentLiveMapAttrsMustApi,
    DocumentLiveMapAttrsReadApi,
    DocumentLiveMapAttrsMutationApi,
    DocumentLiveMapAttrsApi,
    DocumentLiveMapContentApi,
    LiveMapDocumentApi,
    ElementLiveMap,
    FragmentLiveMap,
    DocumentLiveMap,
    ClassifiedLiveMap,
    LiveMapAuthority,
    LiveMapCommitOrigin,
    LiveMapCommitObservation,
    LiveMapCommitObserver,
    LiveMapCommitObserverApi,
    CollectionReflect,
    CollectionReflectOptions,
    CollectionReflectChange,
    CollectionReflectChangeKind,
    CollectionReflectDiagnostics,
    CollectionReflectItemContext,
    CollectionReflectItemUpdate,
    CollectionReflectKey,
    CollectionReflectListener,
    CollectionReflectMappingSummary,
    CollectionReflectRender,
    CollectionReflectRenderResult,
    CollectionReflectSnapshot,
    CollectionReflectStatus,
    LiveInspector,
    LiveInspectorArrayIdentity,
    LiveInspectorArrayKeyContext,
    LiveInspectorArrayKeyResolver,
    LiveInspectorBranchRole,
    LiveInspectorDiagnostics,
    LiveInspectorHsonMode,
    LiveInspectorListener,
    LiveInspectorMappingSummary,
    LiveInspectorOptions,
    LiveInspectorOwnedHsonOptions,
    LiveInspectorOwnedJsonOptions,
    LiveInspectorReadHandle,
    LiveInspectorRendererResult,
    LiveInspectorRendererUpdate,
    LiveInspectorRenderers,
    LiveInspectorSelection,
    LiveInspectorSemanticContext,
    LiveInspectorSemanticRenderer,
    LiveInspectorSerializationTarget,
    LiveInspectorSnapshot,
    LiveInspectorSource,
    LiveInspectorSpecialization,
    LiveInspectorStatus,
    LiveInspectorValueKind,
    LiveHost,
    LiveHostForMap,
    LiveHostActionContext,
    LiveHostActionContextForMap,
  LiveHostActionOrigin,
  LiveHostActionAuthorizationSession,
  LiveHostActionAuthorizationContext,
  LiveHostActionAuthorizer,
    LiveHostActionHandler,
    LiveHostActionHandlerForMap,
    LiveHostActionId,
    LiveHostActionRequestId,
    LiveHostActionStatusId,
    LiveHostActionDelivery,
    LiveHostActionDedupeDiagnostics,
    LiveHostActionDedupeInspector,
    LiveHostActionDedupeOptions,
    LiveHostActionDedupeSchedule,
    LiveHostActionRequestErrorCode,
    LiveHostActionStatusState,
    LiveHostActionTerminalOutcome,
    LiveHostActionName,
    LiveHostActionPayloads,
    LiveHostDocumentActionName,
    LiveHostDocumentActionFn,
    LiveHostDocumentActionPayloads,
    LiveHostDocumentActionPromise,
    LiveHostDocumentActionRequest,
    LiveHostDocumentRetryActionFn,
    LiveHostDocumentTargetPayload,
    LiveHostActions,
    LiveHostActionsForMap,
    ExistingMapLiveHostOptions,
    ProjectedLiveHostOptions,
    LiveHostClient,
    LiveHostClientForMap,
    LiveHostClientActionFn,
    LiveHostClientActionResult,
    LiveHostClientActionPromise,
    LiveHostClientActionRequest,
    LiveHostClientActionStatusResult,
    LiveHostClientActionStatusMessage,
    LiveHostClientRetryActionFn,
    LiveHostClientRecoverMessage,
    LiveHostClientSession,
    LiveHostClientSessionAttachMessage,
    LiveHostClientSessionCreateMessage,
    LiveHostClientSessionDiagnostics,
    LiveHostClientSessionFailure,
    LiveHostClientSessionGoodbyeMessage,
    LiveHostClientSessionOptions,
    LiveHostClientSessionResult,
    LiveHostClientSessionStatus,
    LiveHostClientRecovery,
    LiveHostClientRecoveryForMap,
    LiveHostClientRecoveryChange,
    LiveHostClientRecoveryChangeForMap,
    LiveHostClientRecoveryChangeListener,
    LiveHostClientRecoveryChangeListenerForMap,
    LiveHostClientRecoveryCursor,
    LiveHostClientRecoveryDiagnostics,
    LiveHostClientRecoveryFailure,
    LiveHostClientRecoveryOptions,
    LiveHostClientRecoveryResult,
    LiveHostClientRecoveryStatus,
    LiveHostClientRecoveryStrategy,
    LiveHostClientHelloMessage,
    LiveHostClientMessage,
    LiveHostClientOptions,
    LiveHostClientOptionsForMap,
    LiveHostCanonicalCommit,
    LiveHostCanonicalCommitListener,
    LiveHostEncodedGraphContent,
    LiveHostEncodedGraphOp,
    LiveHostEncodedGraphReplaceRootOp,
    LiveHostEncodedGraphReplaceContentOp,
    LiveHostEncodedGraphInsertContentOp,
    LiveHostCanonicalDeleteOp,
    LiveHostCanonicalHistory,
    LiveHostCanonicalHistoryDiagnostics,
    LiveHostCanonicalHistoryOptions,
    LiveHostCanonicalOp,
    LiveHostCanonicalReplaceOp,
    LiveHostCanonicalRenameOp,
    LiveHostCanonicalMoveOp,
    LiveHostCanonicalSetOp,
    LiveHostCanonicalSpliceOp,
    LiveHostCanonicalStream,
    LiveHostCanonicalStreamOptions,
    LiveHostRecoveryAttemptBase,
    LiveHostRecoveryAttemptDiagnostics,
    LiveHostRecoveryAttemptState,
    LiveHostRecoveryBodyItem,
    LiveHostRecoveryBodyObserver,
    LiveHostRecoveryCaughtUp,
    LiveHostRecoveryCompletion,
    LiveHostRecoveryCurrentPlan,
    LiveHostRecoveryHooks,
    LiveHostRecoveryId,
    LiveHostRecoveryOptions,
    LiveHostRecoveryPlan,
    LiveHostRecoveryPlanner,
    LiveHostRecoveryPlannerDiagnostics,
    LiveHostRecoveryRejectCode,
    LiveHostRecoveryRejectPlan,
    LiveHostRecoveryRejection,
    LiveHostRecoveryReplayPlan,
    LiveHostRecoveryRequest,
    LiveHostRecoveryRuntimeErrorCode,
    LiveHostRecoverySnapshotPlan,
    LiveHostRecoverySnapshotReason,
    LiveHostDisposer,
    LiveHostConnection,
    LiveHostEventListener,
    LiveHostError,
    LiveHostId,
    LiveHostIncarnationId,
    LiveHostLogicalMapId,
    LiveHostModeErrorCode,
    LiveHostMapValue,
    LiveHostOptions,
    LiveTraceSink,
    LiveHostResult,
    LiveHostSchema,
    LiveHostSchemaDecoder,
    LiveHostSchemaIssue,
    LiveHostSchemaResult,
    LiveHostSeq,
    LiveHostConnectionEpoch,
    LiveHostServerMessage,
    LiveHostServerActionStatusMessage,
    LiveHostServerCanonicalCommitMessage,
    LiveHostServerEventMessage,
    LiveHostServerRecoveryCaughtUpMessage,
    LiveHostServerRecoveryCommitMessage,
    LiveHostServerRecoveryErrorMessage,
    LiveHostServerRecoveryPlanMessage,
    LiveHostServerRecoverySnapshotMessage,
    LiveHostServerSessionAttachedMessage,
    LiveHostServerSessionCreatedMessage,
    LiveHostServerSessionEndedMessage,
    LiveHostServerSessionFencedMessage,
    LiveHostServerSessionRejectedMessage,
    LiveHostSocketLike,
    LiveHostSessionCredential,
    LiveHostSessionDiagnostic,
    LiveHostSessionDiagnostics,
    LiveHostSessionInspector,
    LiveHostSessionLifecycleEvent,
    LiveHostSessionOptions,
    LiveHostSessionRejectCode,
    LiveHostSessionRequestId,
    LiveHostSessionSchedule,
    LiveHostSessionState,
    LiveHostSnapshotEnvelope,
    LiveHostStore,
    LiveHostStoreCreateOptions,
    LiveHostStoreEntry,
    LiveHostStoreId,
    LiveHostPersistenceAdapter,
    LiveHostPersistedMapKind,
    LiveHostPersistedViewState,
    LiveHostPersistedDocumentCheckpoint,
    LiveHostPersistedCheckpoint,
    LiveHostPersistedCommit,
    LiveHostPersistedMapState,
    PersistentDocumentLiveHostOptions,
    PersistentLiveHostForMap,
    LiveHostPersistentStore,
    LiveHostPersistentStoreEntry,
    LiveHostValidator,
    LiveHostWireValue,
} from "./types/index.js";
export type { LiveHostDocumentSnapshotEncoding } from "./api/livehost/livehost.document-snapshot.js";
export { LiveMapSchemaError } from "./api/livemap/livemap.error.js";
export { snap_live_path } from "./api/livemap/livemap.editor.js";
export type { InferLiveMapSchema, LiveMapSchema, LiveMapSchemaValue, LiveMapSchemaValidation, LiveMapSchemaIssue, LiveMapSchemaRule } from "./api/livemap/livemap.schema.js";
export { ELEM_TAG, OBJ_TAG, ARR_TAG, ROOT_TAG, II_TAG, STR_TAG, VAL_TAG, ATTRS_KEY, META_KEY, TAG_KEY, CONTENT_KEY } from "./core/constants.js";
export { make_sanitizer, type SanitizerLike } from "./safety/sanitize-html.utils.js";
