/* Generated by Hson Schema hson-schema-mvp-10. Do not edit. */
import type { HsonNumber, HsonSchemaMutationCandidate } from "hson-live";
abstract class __UserSchemaD0ObjectProof0 { declare private readonly __hsonSchemaProof0: void; }
abstract class __UserSchemaD0DefinitionProof1 { declare private readonly __hsonSchemaProof1: void; }
abstract class __UserSchemaD1DefinitionProof2 { declare private readonly __hsonSchemaProof2: void; }
abstract class __UserSchemaRootObjectProof3 { declare private readonly __hsonSchemaProof3: void; }
type __UserSchemaDefinition0MutationCandidate = { age: __UserSchemaDefinition1MutationCandidate; };
type __UserSchemaDefinition1MutationCandidate = number;
type __UserSchemaDefinition0 = (Readonly<{ readonly age: __UserSchemaDefinition1; }> & __UserSchemaD0ObjectProof0 & HsonSchemaMutationCandidate<{ age: __UserSchemaDefinition1MutationCandidate; }>) & __UserSchemaD0DefinitionProof1 & HsonSchemaMutationCandidate<__UserSchemaDefinition0MutationCandidate>;
type __UserSchemaDefinition1 = (HsonNumber & HsonSchemaMutationCandidate<number>) & __UserSchemaD1DefinitionProof2 & HsonSchemaMutationCandidate<__UserSchemaDefinition1MutationCandidate>;
type __Value = Readonly<{ readonly user: __UserSchemaDefinition0; }> & __UserSchemaRootObjectProof3 & HsonSchemaMutationCandidate<{ user: __UserSchemaDefinition0MutationCandidate; }>;
declare const __Identity: unique symbol;
export type Evidence = Readonly<{ value: __Value; mode: "data"; identity: typeof __Identity }>;
