/* Generated by Hson Schema hson-schema-mvp-7. Do not edit. */
import type { HsonNumber, HsonSchemaMutationCandidate } from "hson-live";
import type { HsonCanonical } from "hson-live/hson";
abstract class __UserSchemaRootM0ObjectProof0 { declare private readonly __hsonSchemaProof0: void; }
abstract class __UserSchemaRootObjectProof1 { declare private readonly __hsonSchemaProof1: void; }
abstract class __UserSchemaHsonProof2 { declare private readonly __hsonSchemaProof2: void; }
export type UserSchemaType = Readonly<{ readonly user: Readonly<{ readonly age: HsonNumber & HsonSchemaMutationCandidate<number>; }> & __UserSchemaRootM0ObjectProof0 & HsonSchemaMutationCandidate<{ age: number; }>; }> & __UserSchemaRootObjectProof1 & HsonSchemaMutationCandidate<{ user: { age: number; }; }>;
export type UserSchemaHson = HsonCanonical & __UserSchemaHsonProof2;
